<table width="100%" height="100%" bgcolor="#FFFFFF">
	<tr>
		<td valign="TOP" align="center">
			<!-- ###################### start #######################-->
			<table border="0" width="100%" cellpadding="0" cellspacing="5" style="background:#F3FDF9 url(/stock/img/bg_header.gif) repeat-x;">
				
				<tr height="30">
					<td width="30%" align="right">DOCUMENT</td>
					<td width="20%">
						<?php 
							$arr_typecancel=array(
															"SL"=>"บิลเงินสดอย่างย่อ (SL)",
															"VT"=>"บิลเงินสดใบกำกับภาษี (VT)",
															"AI"=>"โอนสินค้าเข้า (AI)",
															"TO"=>"โอนสินค้าออก (TO)",
															"AO"=>"โอนสินค้าออก (AO)",
															"CN"=>"ลดหนี้ลูกค้า (CN)",
															"OR"=>"สั่งสินค้า (OR)",
															"DN"=>"ใบเบิกสินค้า (DN)",
															"RQ"=>"คำขอโอนสินค้าออก (RQ)",
															"IQ"=>"คำขอแจ้งสินค้าเกิน (IQ)"
														);
						?>
						<select id="sel_typecancel" class="input-text-pos ui-corner-all">
							<option value="">DOCUMENT TYPE</option>
							<?php
								foreach($arr_typecancel as $key=>$value){
									?>
									<option value="<?php echo $key;?>"><?php echo $value;?></option>
									<?php
								} //
							?>
						</select>					
					</td>
					<td align="left">
						CANCEL THE TIME<span id="n_cancel"> ___</span>
					</td>
				</tr>
			
				<tr height="30">
					<td width="30%" align="right">DOCUMENT NO.</td>
					<td width="20%">
						<input type="text" name="acc_doc_no" id="acc_doc_no" size="25" class="input-text-pos ui-corner-all"></input>
						<input type="hidden" name="acc_status_no" id="acc_status_no"></input>
					</td>
					<td align="left">
						<a href="#" name="bws_docstatus" id="bws_docstatus" class="btnGrayClean">...</a>
					</td>
				</tr>
				<tr height="30">
					<td>&nbsp;</td>
					<td>
						<a href="#" name="btn_commit" id="btn_commit" class="btnGrayClean">OK</a>
					</td>
					<td>&nbsp;</td>
				</tr>
			</table>
			<div id="dlgDocNoCancel"></div>
			<!-- ###################### stop #######################-->
		</td>
	</tr>
</table>
<input type="hidden" name="csh_lock_status" id="csh_lock_status" value="<?php echo $this->lock_status;?>"></input>
<div id="dlgSaleMan"></div>
<div id="dlgFormCancelDoc" style="display:none;"></div>
<script type="text/javascript" src="/sales/js/accessory/canceldoc.js"></script>