<table border="0" cellpadding="5" cellspacing="5" width="100%">
<tr>
	<td width="35%" align="right">ป้อนรหัสผ่าน&nbsp;:</td>
	<td><input type="text" size="15" id="cpassword" name="cpassword"></td>	
</tr>
<tr>
	<td width="35%" align="right">ป้อนรหัสพนักงาน&nbsp;:</td>
	<td><input type="password" size="15" id="chk_saleman_id" name="chk_saleman_id"></td>	
</tr>
<tr>
	<td width="35%" align="right">เหตุผลการยกเลิก&nbsp;:</td>
	<td>
		<select id="cancel_description">
			<option value="">-เลือก-</option>
			<option value="1">ลูกค้าสมัครสมาชิก</option>
			<option value="2">ลูกค้าเปลี่ยนสินค้าและซื้อสินค้าเพิ่ม</option>
			<option value="3">พนักงานขายเลือกโปรโมชั่นผิด</option>
			<option value="4">พนักงานขายลืมตัดรายการของแถมให้ลูกค้า</option>
			<option value="5">ลูกค้าใช้คูปองในการซื้อสินค้า</option>
			<option value="6">อื่นๆ</option>			
		</select>
	</td>	
</tr>
</table>