
 <style type="text/css">  
		.tableNavSelCooperation
			{
				width:100%;
				background:#333;
			}
		.tableNavSelCooperation ul
			{
				float:right;
				width:100%;
				margin:0;
				padding:0;
				border:1px solid #C9C9C9;
			}
	 
	  .tableNavSelCooperation ul li{
			cursor:pointer;
				list-style-type:none;
				line-height:40px;
				font-family:"PSLKittithadaBold","Garuda","Tahoma", "Geneva", "Arial", sans-serif;
				font-weight: normal;
				font-size:25px;/*16*/
				text-decoration:none;
				color:#303030;
				padding-left:1em;
				border-bottom:1px solid  #78777C;
				text-shadow: 0px 1px 0px #dddddd;
				vertical-align: middle;
				white-space:nowrap;
				background:#B2B2B8;
				background:  -moz-linear-gradient(     #D4D7E0,     #B0B0B0);;
				background: -webkit-gradient(linear, left top, left bottom, color-stop(0,#D4D7E0), color-stop(1, #B0B0B0));
				-moz-user-select:none;
				-moz-user-select:-moz-none;/*latest ff*/
				-webkit-user-select:none;
	  }
	  ul li.active {
				cursor:pointer;
				list-style-type:none;
				line-height: 40px;
				font-family:"PSLKittithadaBold", "Garuda","Helvetica World","Tahoma", "Geneva", "Arial", sans-serif;
				font-weight: normal;
				font-size:25px;/*16*/
				text-decoration:none;
				color:#ffffff;/*#303030*/
				padding-left:1em;
				border-bottom:1px solid  #000;/*78777C*/
				text-shadow: 0px 1px 0px #dddddd;
				vertical-align: middle;
				white-space:nowrap;
				background:#B2B2B8;
				background:  -moz-linear-gradient(#9DDCCF,#265541);/*#D4D7E0, #B0B0B0||#777777,#444444*/
				background: -webkit-gradient(linear, left top, left bottom, color-stop(0, #D4D7E0), color-stop(1, #B0B0B0));
				-moz-user-select:none;
				-moz-user-select:-moz-none;/*latest ff*/
				-webkit-user-select:none;
	  }
	  ul li.nokeyboard {
		color: #999;
		background:#0000ff;
	  }
	</style>
	<div >
		<input type="radio" name="th" id="r1" value="1" /><label for="r1"> ไทย</label> &nbsp; 
		<input type="radio" name="th" id="r2" value="2" /><label for="r2"> ต่างชาติ</label>
		<select name='country' id='country'>
			<option value='NUL'>ไม่ระบุ</option>
			<?php
			while($r = array_shift($this->arr_country)){
				echo "<option value='".$r['cc']."'>".$r['en']."(".$r['th'].")</option>";
			}
			?>
		</select>
	</div>
	<hr width="95%">
	<div >
		<input type="radio" name="ss" id="s1" value="1" /><label for="s1"> ชาย</label> &nbsp; 
		<input type="radio" name="ss" id="s2" value="2" /><label for="s2"> หญิง</label>
	</div>
	<hr width="95%">
	<div>
		<label for="age"> อายุ</label>
		<input type='number' name='age' id='age' max='100'>
	</div>
	<script>

$(document).ready(function() {
 $('#country').hide();
    $('input[type=radio][name=th]').change(function() {
        if (this.value == '1') {
            $('#country').hide();
        }else{
			$('#country').show();
		}

    });
});
	</script>