<style type="text/css">
	#ajaxBusy{
		  display: none;
		  margin: 0px 0px 0px -50px; /* left margin is half width of the div, to centre it */
		  padding: 30px 10px 10px 10px;
		  position: absolute;
		  left: 30%;
		  top: 325px;
		  width:150px;
		  height:80px;
		  text-align: center;
		  background:transparent url(/sales/img/activity_indicators_02.gif) no-repeat center center;
		  border:0px solid #000;
	}
</style>
<div id="ajaxBusy"></div>
<table width="100%" height="100%" bgcolor="#FFFFFF">
	<tr>
		<td valign="TOP">
			<!-- ######### start ##########-->
			<table border="0" width="100%" cellpadding="2" cellspacing="3" style="background:#F3FDF9 url(/stock/img/bg_header.gif) repeat-x;">
				<tr>
					<td colspan="3">
						<table width="100%" border="0" cellpadding="2" cellspacing="0">
							<tr>
								<td align="right" width="20%">START DATE&nbsp;:</td>
								<td align="left" >
									<input type="text" size="10" id="start_date" name="start_date" class="input-text-pos ui-corner-all" >
									<input type="hidden" id="sel_start_date_alternate" size="15"></input>
								</td>
							</tr>
							<tr>
								<td align="right" width="20%">END DATE&nbsp;:</td>
								<td align="left" >
									<input type="text" size="10" id="end_date" name="start_date" class="input-text-pos ui-corner-all" >
									<input type="hidden" id="sel_end_date_alternate" size="15"></input>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td align="right" width="20%">DOCUMENT NO.&nbsp;:</td>
					<td width="21%"><input type="text" name="doc_no_start" id="doc_no_start" size="25" class="input-text-pos"></input></td>
					<td>
						<a href="#" name="bws_doc_start" id="bws_doc_start" class='btnGrayClean'>...</a>
					</td>
				</tr>
				<tr>
					<td align="right">END DOCUMENT NO.&nbsp;:</td>
					<td><input type="text" name="doc_no_stop" id="doc_no_stop" size="25" class="input-text-pos"></input></td>
					<td>
						<a href="#" name="bws_doc_stop" id="bws_doc_stop" class="btnGrayClean">...</a>
					</td>
				</tr>
				<tr height="35">
					<td>&nbsp;</td>
					<td>
						<a href="#" name="btn_commit" id="btn_commit" class="btnGrayClean">OK</a>
						&nbsp;
						<a href="#" name="btn_cancel" id="btn_cancel" class="btnGrayClean">Cancel</a>
					</td>
					<td>&nbsp;</td>
				</tr>
			</table>
			<!-- ######### stop ##########-->
		</td>
	</tr>
</table>
<input type="hidden" name="doc_type_question" id="doc_type_question" value="<?php echo $this->doc_tp;?>"></input>
<div id="dlgDocNoQst"></div>
<div id="dlgQstDetail"></div>
<script type="text/javascript" src="/sales/js/accessory/questiondoc.js"></script>