<?php
$data=$this->data;
$doc_no=$this->doc_no;
$count=count($data);
if($count>0){
?>	
<table width='100%' border='0' cellspacing='1' cellpadding='1'>
	<tr bgcolor="#f4f2f2">
		<td>เลขที่เอกสาร : <?php echo $doc_no;?></td>
	</tr>
</table>
<table width='100%' border='0' cellspacing='1' cellpadding='1'>
	<tr bgcolor="#eae8e8">
		<td>รหัส Shelf</td>
		<td>รายละเอียด</td>
		<td align="right">จำนวน</td>
		<td align="right">ราคา</td>
	</tr>
<?php 
$sum_onhand="";
$sum_price="";
foreach($data as $val){
	$onhand=number_format($val['qty'], 0, '.', ',');
	$price=number_format($val['sum_price'], 2, '.', ',');
	$sum_price=$sum_price+$val['sum_price'];
	$sum_onhand=$sum_onhand+$val['qty'];
	$desc=substr($val['desc'],0,20);
?>
	<tr>
		<td><?php echo $val['shelf_no'];?></td>
		<td><?php echo $desc;?></td>
		<td align="right"><?php echo $onhand;?></td>
		<td align="right"><?php echo $price;?></td>
	</tr>
<?php 
}
$sum_onhand=number_format($sum_onhand, 0, '.', ',');
$sum_price=number_format($sum_price, 2, '.', ',');
?>
	<tr>
		<td colspan="4"><hr size="1"></hr></td>
	</tr>
	<tr>
		<td align="right" colspan="2">รวม : </td>
		<td align="right"><?php echo $sum_onhand;?></td>
		<td align="right"><?php echo $sum_price;?></td>
	</tr>
	<tr>
		<td colspan="4"><hr size="1"></hr></td>
	</tr>
</table>
<?php 	
}else{
	echo "ไม่มีรายการเอกสาร";	
}
?>
