<script>
$(document).ready( function() {
	getcountshelfdata();
});
</script>
<div id="dialog_product" title="รายการสินค้า"></div>
<div id="dialog_preview" title="Print"></div>
<?php 
$json_doc_no=$this->jsondata;
$doc_no=json_decode($json_doc_no,true);

echo "
<table width='100%' border='0'>
	<tr>
		<td class='sub_text_head'>พิมพ์รายงานการตรวจนับ</td>
		<td align='right' width='35%'>
		เอกสารเลขที่ : 
		<select id='doc_no' onChange='return getcountshelfdata();'>
		";
			foreach($doc_no as $val_doc_no){
				echo "<option value='".$val_doc_no['doc_no']."'>".$val_doc_no['doc_no']."</option>";
			}
		echo "
		</select>
		</td>
	</tr>
	<tr>
		<td colspan='2'><hr size='1'></td>
	</tr>
	<tr>
		<td colspan='2'><div id='view_count_shelf'></div></td>
	</tr>
</table>

";
?>
