<script>
viewgenlisttag();
jQuery(document).bind('keydown', 'f1',
function (evt){
	print_list_tag();
});

function add_shelf_audit(){
	var txt="Confirm Add Shelf Audit";
	jConfirm(txt, 'Confirm Process', function(r) {
		if(r==true){
			$( "#dialog_process" ).html("<center><font color='#059562'><img src='/stock/img/ajax-loader.gif' border='0' align='absmiddle'><br><b>กำลังสร้าง Shelf Audit...</b></font></center>");
			$( "#dialog_process" ).dialog( "open" );
			$.ajax({type: "POST",url: "/stock/checkstock/genshelfaudit",data:{},success:
				function(data){
					if(data=="Y"){
						$( "#dialog_process" ).dialog( "close" );
						viewgenlisttag();
					}else{
						jAlert('Error Can not process', 'Alert', function(r){return false;});
					}
				}
			}); 
		}
	});
}

</script>
<?php 
$doc_no=$this->doc_no;
$shelf=$this->shelf;
?>
<div id="dialog_get_docno" title="Count Product Doc. No."></div>
<div id="dialog_process" title="Process"></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="sub_text_head">Inventory Tag </td>
  </tr>
  <tr>
    <td height="30"><hr size="1"></hr></td>
  </tr>
  <tr>
    <td>
    <table width="100%" border="0" cellspacing="2" cellpadding="2">
    	<tr bgcolor="#f5f4f4">
    		<td width="1%"><input type="checkbox" name="checker" id="checker" onclick="jqCheckAll2( this.id, 'myCB' )" checked="checked"></td>
    		<td>Select/Cancle All</td>
    		<td align="right">
    		<a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_list_tag();"><span class="ui-icon ui-icon-gear"></span>Run and Print Doc. (F1)</a>
    		<a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_doc_no();"><span class="ui-icon ui-icon-print"></span>Print from Doc. No. </a>
    		<a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_shelf();"><span class="ui-icon ui-icon-print"></span>Print Shelf</a>
    		<a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return add_shelf_audit();"><span class="ui-icon ui-icon-gear"></span>Add Shelf Audit</a>
    		</td>
    	</tr>
    </table>
    </td>
  </tr>
  <tr>
    <td height="30"><hr size="1"></hr></td>
  </tr>
  <tr>
    <td>
   	<div id="viwgenlisttag"></div>
	</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>