<a href="/stock/checkstock/configshelf" target="_blank">กำหนด Shelf สินค้า & ผูกสินค้ากับ Shelf</a><br>
<a href="/stock/checkstock/genlisttag" target="_blank">พิมพ์ Inventory Tag</a><br>
<a href="/stock/checkstock/keylisttag" target="_blank">บันทึกข้อมูลการตรวจนับ</a><br>
<a href="/stock/checkstock/gencountlisttag" target="_blank">สอบถามยอดรวมของแต่ละ Shelf No.</a><br>
<a href="/stock/checkstock/difcheck" target="_blank">สอบถาม ยอด ขาดเกิน(dif check)</a><br>