<?php 
$data=$this->data;
$doc_no=$this->doc_no;
$shop=$this->shop;
$shop_name=$this->branch_name;
include(FPDF_PATH."/fpdf.php");
$pdf=new FPDF('P','mm','a23');
$pdf->SetThaiFont();
$pdf->AddPage();
$pdf->SetAutoPageBreak("off",1);
$startY=2;
$startX=0;//4
$pdf->SetY($startY);
$pdf->SetX($startX);	
$date=date("d/m/Y");
$time=date("h:i:s");
$line="---------------------------------------------------------------------------------------------------------------------";

$head_doc_no=iconv('UTF-8','cp874',"เลขที่เอกสาร  : ");
$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(51,1,"$head_doc_no".$doc_no,0,0,'L',0);
$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(45,1,"DATE : ".$date,0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(0,1,"TIME : ".$time,0,0,'L',0);
$shop=$this->shop;
$line7_col_1=iconv('UTF-8','cp874',"รหัสจุดขาย : ");
$branch_name=iconv('UTF-8','cp874',$shop_name);
$shop_no=$shop." ".$branch_name;
$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(51,1,$line7_col_1.$shop_no,0,0,'L',0);

$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->SetFont('CordiaNew','',8);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->Cell(51,0,$line,0,0,'L',0);

$qty=iconv('UTF-8','cp874',"จำนวน");
$desc=iconv('UTF-8','cp874',"รายละเอียด");
$price=iconv('UTF-8','cp874',"มูลค่า");
$startY=$startY+3;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(13,1,"Shelf",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(26,1,$desc,0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(14,1,$qty,0,0,'C',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(15,1,$price,0,0,'C',0);

$startY=$startY+3;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->SetFont('CordiaNew','',8);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->Cell(51,0,$line,0,0,'L',0);

$j=1;
$count_page=null;
$sum_onhand="";
$sum_price="";
foreach($data as $val){
	$desc=substr($val['desc'],0,15);
	/*if(!empty($desc)){
		$desc=iconv('UTF-8','cp874',$desc);
	}else{
		$desc="";
	}*/
	$onhand=number_format($val['qty'], 0, '.', ',');
	$price=number_format($val['sum_price'], 2, '.', ',');
	$sum_price=$sum_price+$val['sum_price'];
	$sum_onhand=$sum_onhand+$val['qty'];
	$startY=$startY+5;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->Cell(2,1,"",0,0,'L',0);
	$pdf->SetFont('CordiaNew','B',11);
	$pdf->Cell(13,1,$val['shelf_no'],0,0,'L',0);
	$pdf->SetFont('CordiaNew','B',11);
	$pdf->Cell(26,1,$desc,0,0,'L',0);
	$pdf->SetFont('CordiaNew','B',11);
	$pdf->Cell(14,1,$onhand,0,0,'R',0);
	$pdf->SetFont('CordiaNew','B',11);
	$pdf->Cell(15,1,$price,0,0,'R',0);
	$j++;
	$count_page=$count_page+1;
	if($count_page==23){
		$pdf->AddPage();
		$pdf->SetAutoPageBreak("off",1);
		$startY=6;
		$startX=0;//4
		$pdf->SetY($startY);
		$pdf->SetX($startX);	
		$count_page=0;
	}
}
$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->SetFont('CordiaNew','',8);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->Cell(51,0,$line,0,0,'L',0);

$txt_sum=iconv('UTF-8','cp874',"ยอดรวม");
$sum_onhand=number_format($sum_onhand, 0, '.', ',');
$sum_price=number_format($sum_price, 2, '.', ',');
$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(40,1,$txt_sum,0,0,'R',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(13,1,$sum_onhand,0,0,'R',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(15,1,"",0,0,'R',0);

$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,1,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(40,1,"",0,0,'R',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(13,1,"",0,0,'R',0);
$pdf->SetFont('CordiaNew','B',12);
$pdf->Cell(15,1,$sum_price,0,0,'R',0);

$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->SetFont('CordiaNew','',8);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->Cell(51,0,$line,0,0,'L',0);

$startY=$startY+10;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',11);
$pdf->Cell(18,0,iconv('UTF-8','cp874',"หัวหน้าจุดขาย : "),0,0,'L',0);
$pdf->Cell(20,0,iconv('UTF-8','cp874',"_____________"),0,0,'L',0);
$pdf->Cell(15,0,iconv('UTF-8','cp874',"ผู้ตรวจสอบ : "),0,0,'L',0);
$pdf->Cell(20,0,iconv('UTF-8','cp874',"_____________"),0,0,'L',0);

$startY=$startY+5;
$pdf->SetY($startY);
$pdf->SetX($startX);
$pdf->Cell(2,0,"",0,0,'L',0);
$pdf->SetFont('CordiaNew','B',11);
$pdf->Cell(18,0,"",0,0,'L',0);
$pdf->Cell(20,0,iconv('UTF-8','cp874',"(......./......./........)"),0,0,'C',0);
$pdf->Cell(15,0,"",0,0,'L',0);
$pdf->Cell(20,0,iconv('UTF-8','cp874',"(......./......./........)"),0,0,'C',0);

$name="print".".pdf";
$output=REPORT_PATH.$name;
$output="/var/www/pos/htdocs/stock/report/".$name;
@chmod(REPORT_PATH,0777);
$pdf->Output($output,'F');
echo shell_exec("lp -o media=Letter $output");
if(@file_exists($output)){
	echo shell_exec("rm $output");
}
