<script type="text/javascript">
$(function() {	
	//all hover and click logic for buttons
		$(".fg-button")
		.hover(
			function(){ 
				$(this).addClass("ui-state-hover"); 
			},
			function(){ 
				$(this).removeClass("ui-state-hover"); 
			}
		)
		.mousedown(function(){
				$(this).parents('.fg-buttonset-single:first').find(".fg-button.ui-state-active").removeClass("ui-state-active");
				if( $(this).is('.ui-state-active.fg-button-toggleable, .fg-buttonset-multi .ui-state-active') ){ $(this).removeClass("ui-state-active"); }
				else { $(this).addClass("ui-state-active"); }	
		})
		.mouseup(function(){
			if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button,  .fg-buttonset-multi .fg-button') ){
				$(this).removeClass("ui-state-active");
			}
		});
	});
function jqCheckAll2( id, name )
{
   $("INPUT[@name=" + name + "][type='checkbox']").attr('checked', $('#' + id).is(':checked'));
}
</script>
<?php 
$data=$this->data;
$room_no=$this->room_no;
$data_product=$this->data_product;
?>
<form name="frm_tranfer_product" id="frm_tranfer_product">
<table width="100%" border="0" cellspacing="2" cellpadding="2">
  <tr>
    <td align="center">
    	<table width="100%" border="0" cellspacing="2" cellpadding="2">
    		<tr>
    			<td colspan="3">Room ID : <?php echo $room_no;?></td>
    		</tr>
    		<tr bgcolor="#e6e4e4">
    			<td colspan="2" align="right">
    				<select name="new_room" id="new_room">
    					<option value="">Choose Room</option>
    					<?php 
    					foreach($data as $val_room){
    						echo "<option value='".$val_room['room_no']."'>".$val_room['room_no']."</option>";
    					}
    					?>
    				</select>
    			</td>
    			<td><a class="fg-button ui-state-default fg-button-icon-solo ui-corner-all" onClick="return go_tranfer_room();"><span class="ui-icon ui-icon-arrowthick-1-ne"></span>โอนสินค้าระหว่างห้อง </a></td>
    		</tr>
    		<tr>
    			<td width="8%" height="25" align="center" background="/stock/img/bg_header_blue.gif"><input type="checkbox" name="checker" id="checker" onclick="jqCheckAll2( this.id, 'myCB' )" checked></td>
    			<td background="/stock/img/bg_header_blue.gif">&nbsp;Product ID</td>
    			<td width="28%" background="/stock/img/bg_header_blue.gif" align="center">Quantity</td>
    		</tr>
    		<?php 
    		if(!empty($data_product)){
    			$i=1;
	    		foreach($data_product as $val_product){
	    		if($i%2){$color="#eaebeb";}else{$color="#f2f3f3";}
	    		$onhand=number_format($val_product['onhand'], 0, '.', ',');
	    		?>
	    		<tr bgcolor="<?php echo $color;?>">
	    			<td><input type="checkbox" name="tranf_product[]" id="tranf_product[]" value="<?php echo $val_product['product_id'];?>" class="sel_checkbox" checked></td>
	    			<td>&nbsp;<?php echo $val_product['product_id'];?></td>
	    			<td align="center"><?php echo $onhand;?></td>
	    		</tr>
	    		<?php 
	    		$i++;
	    		}
    		}
    		?>
    	</table>
	</td>
  </tr>
</table>
<input type="hidden" name="send_room_no" id="send_room_no" value="<?php echo $room_no;?>"></input>
</form>