<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>POS ONLINE</title>
	<link href='/sales/css/style.css' rel='stylesheet' type='text/css'>
	<link href="/sales/css/themes/dark-hive/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css"/>	
	<script type="text/javascript" src="/sales/js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="/sales/js/jquery-ui-1.8.18.custom.min.js"></script>	
	<script type="text/javascript" src="/sales/js/plugin/jquery.center.js"></script>	
</head>
<body>
       <?php		      		
       		echo $this->layout()->content;
		?>
</body>
</html>