<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=tis-620">
<title>POS</title>
<link rel='stylesheet' type='text/css' href='/sales2011/css/style.css'>
<link type="text/css" href="/sales2011/css/themes/cupertino/jquery-ui-1.8.10.custom.css" rel="stylesheet" />
<script type="text/javascript" src="/sales2011/js/jquery-1.4.4.min.js"></script>
<!--  
<script language='javascript' src='/pos/js/js_index.js'></script>
-->
<script type="text/javascript" src="/sales2011/js/jquery-ui-1.8.10.custom.min.js"></script>
</head>
<!-- 
	onLoad="MM_preloadImages('/sales2011/img/icon/icon_sale_up.jpg','/sales2011/img/icon/icon_stock_up.jpg','/sales2011/img/icon/icon_member_up.jpg')"
 -->
<body>
<div id="dialog" title=""></div>
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="1" colspan="2">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
      
      <tr>
        <td width="17"><img src="/sales2011/img/top/top_08.jpg" width="17" height="50"></td>
        <td>
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td width="141"><img src="/sales2011/img/top/top_09.jpg" width="141" height="50"></td>
              <td width="7"><img src="/sales2011/img/top/top_10.jpg" width="7" height="50"></td>
              <td width="141"><img src="/sales2011/img/top/top_11.jpg" width="141" height="50"></td>
              <td width="8"><img src="/sales2011/img/top/top_12.jpg" width="8" height="50"></td>
              <td width="141"><img src="/sales2011/img/top/top_13.jpg" width="141" height="50"></td>
              <td width="8"><img src="/sales2011/img/top/top_14.jpg" width="8" height="50"></td>
              <td width="141"><img src="/sales2011/img/top/top_15.jpg" width="141" height="50"></td>
              <td width="8"><img src="/sales2011/img/top/top_16.jpg" width="8" height="50"></td>
              <td width="141" background="/sales2011/img/top/top_16.jpg"><img src="/sales2011/img/top/top_17.jpg" width="141" height="50"></td>
              <td background="/sales2011/img/top/top_16.jpg" align='right'><img src="/sales2011/img/top/top_19.jpg" width="243" height="50"></td>
            </tr>
        </table>		</td>
        <td width="19"><img src="/sales2011/img/top/top_20.jpg" width="19" height="50"></td>
      </tr>
      <tr>
        <td><img src="/sales2011/img/top/top_21.jpg" width="17" height="24"></td>
        <td background="/sales2011/img/top/top_23.jpg"></td>
        <td><img src="/sales2011/img/top/top_33.jpg" width="19" height="24"></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="94%" valign="top">
	<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="22" height="27"><img src="/sales2011/img/body/body_01.jpg" width="22" height="27"></td>
        <td background="/sales2011/img/body/body_02.jpg"></td>
        <td width="22" height="27"><img src="/sales2011/img/body/body_04.jpg" width="22" height="27"></td>
      </tr>
      <tr>
        <td background="/sales2011/img/body/body_05.jpg">&nbsp;</td>
        <td valign="top">
     		<?php		
				echo $this->layout()->content;
			?>
        </td>
        <td background="/sales2011/img/body/body_07.jpg">&nbsp;</td>
      </tr>
      <tr>
        <td height="1"><img src="/sales2011/img/body/body_10.jpg" width="22" height="27"></td>
        <td background="/sales2011/img/body/body_11.jpg"></td>
        <td><img src="/sales2011/img/body/body_12.jpg" width="22" height="27"></td>
      </tr>
    </table>
	</td>
    
  </tr>
  <tr>
    <td height="54" colspan="2" bgcolor="#EDF6FD">&nbsp;</td>
  </tr>
</table>
</body>
</html>
