<html>
<head>
	<title></title>
	<meta http-equiv='Content-Type' content='text/html; charset=tis-620'/>
	<link type="text/css" href="/sales2011/css/style.css" rel="stylesheet">	
	<link type="text/css" href="/sales2011/css/themes/Aristo/jquery-ui-1.8.7.custom.css" rel="stylesheet">			
	<script type="text/javascript" src="/sales2011/js/jquery-1.4.4.min.js"></script>
	<script type="text/javascript" src="/sales2011/js/jquery-ui-1.8.10.custom.min.js"></script>
</head>
<body>
<table border="0" width="100%">
<thead>
	<tr>
		<th class="ui-widget-header"></th>
	</tr>
</thead>
<tbody class="ui-widget-content">
<tr>
	<td>
	<?php		
		echo $this->layout()->content;
	?>
	</td>
</tr>
</tbody>
<tfoot>
	<tr><td></td></tr>
</tfoot>
</table>
</body>
</html>