<?php

        // echo "this date=".$this->date;
        // echo "</br>";
        // echo "To count=".$this->count;
        // echo "</br>";
        // echo "request password=".$this->reqpwd;
        // echo "</br>";
        // echo "true password=".$this->truepwd;
        if($this->reqpwd==$this->truepwd){
            echo "Y";
        }else{
            // echo "N".$this->truepwd;
            echo "N";
        }



?>