<script>
$(document).ready( function() {
	$("#product_id").focus();
	viewproductinventories();
});
function process(event){
	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
	keyCode = event.which; // Firefox    
	if (keyCode == 13) {
		viewproductinventories();
	}
}
function viewproductinventories(){
	var product_id=$("#product_id").val();
	$.ajax({type: "POST",url: "/stock/stock/getproductinventories",data:{product_id:product_id},success:
	function(data){
		$("#viewproductinventories").html(data);
	}}); 
}

</script>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="20" width="12%" align="right" class="servBodL_right">ป้อนรหัสสินค้า : </td>
    <td><input type="text" name="product_id" id="product_id" class="NFText" autocomplete="off" onkeypress="return process(event)"></td>
  </tr>
  <tr>
    <td colspan="2">
		<div id="viewproductinventories"></div>
	</td>
  </tr>
</table>