<table width="40%" border="0" cellpadding="0" cellspacing="0">
<tr></tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="3" align="right"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="71%">&nbsp;</td>
          <td width="29%" align="right"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_form_count_stock();"><span class="ui-icon ui-icon-print"></span>Print Form </a></td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td colspan="3" align="center">Summary Result of Counting Stock Form</td>
    </tr>
    <tr>
      <td colspan="3">--------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="44%">[ &nbsp;&nbsp;&nbsp;] OP</td>
          <td width="38%">[ &nbsp;&nbsp;&nbsp;] CPS</td>
          <td width="18%">[ &nbsp;&nbsp;&nbsp;] GNC</td>
          </tr>
      </table></td>
      </tr>
    <tr>
      <td colspan="3">Counting Type</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Normal Cycle</td>
      <td>[ &nbsp;&nbsp;&nbsp;] 100% Transfer/Resign</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;] Random Check 1,2</td>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Close Shop</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Normal Cycle</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">[ &nbsp;&nbsp;&nbsp;]  100% Others</td>
    </tr>
    <tr>
      <td colspan="3">Branch.........................................................................................................................................</td>
      </tr>
    <tr>
      <td>No.........................................</td>
      <td>Check Date...................................................................</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">--------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
  </table></td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td>&nbsp;</td>
      <td align="center">UNIT</td>
      <td align="center">BAHT</td>
    </tr>
    <tr>
      <td>Stock Branch (Onhand) on Check Date</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Amount of product actually counted (Random...SKU)</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Summary of Counted Stock : </td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Excess product from counted for adjust in STOCK</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Lack of giveaway product from counted for adjust Out TO</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Lack of product from counted for open bill Tester</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Lack of product</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Total</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="10%" rowspan="3" valign="top">Note</td>
          <td width="90%">............................................................................................................................</td>
        </tr>
        <tr>
          <td>............................................................................................................................</td>
        </tr>
        <tr>
          <td>............................................................................................................................</td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="2">Document........................................................................................................................</td>
          </tr>
        <tr>
          <td width="26%">On Month....................................</td>
          <td width="74%">If unsettled bring to CLEAR</td>
        </tr>
        <tr>
          <td colspan="2">Within.........................................................................................................................</td>
          </tr>
      </table></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table></td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td>Manager......................................................................................................................</td>
          </tr>
        <tr>
          <td>Counting person..........................................................................................................................</td>
          </tr>
        <tr>
          <td>Assistant store manager...........................................................................................................</td>
          </tr>
      </table></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="3">Clear Result of Lack/Excess Stock with AUDIT Department</td>
          </tr>
        <tr>
          <td width="2%">1.</td>
          <td colspan="2">Summary result on branch Lack/Excess........................................Baht</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">Adjust as per document/Attachment evidence .................................Baht</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td width="53%">&nbsp;</td>
          <td width="45%">&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2"><table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td>OPERATION :</td>
              </tr>
            <tr>
              <td>...............................................................................................................................................</td>
              </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
              </tr>
          </table></td>
          </tr>
        <tr>
          <td>2.</td>
          <td colspan="2">Amount of bring forward STOCK At the accounting department checked and confirmed</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">[&nbsp;&nbsp;&nbsp;&nbsp;]Correct.............................Piece</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">[&nbsp;&nbsp;&nbsp;&nbsp;] InCorrect ........................................................Piece</td>
          </tr>
        <tr>
          <td colspan="3">Summary Check net STOCK [&nbsp;&nbsp;&nbsp;&nbsp;] Lack  [&nbsp;&nbsp;&nbsp;&nbsp;] Excess Amount....................Baht</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2"><table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td>OPERATION :</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
          </table></td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">APPROVED BY......................................................</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">INTERNAL AUDIT</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">Signature....................................................................</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">ROM/ROC</td>
          </tr>
      </table></td>
    </tr>
  </table></td>
</tr>
</table>