<table width="40%" border="0" cellpadding="0" cellspacing="0">
<tr></tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="3" align="right"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="71%" bgcolor="#EAEAEA">&nbsp;</td>
          <td width="29%" align="right" bgcolor="#EAEAEA"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_form_count_stock();"><span class="ui-icon ui-icon-print"></span>พิมพ์แบบฟอร์ม </a></td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td colspan="3" align="center">แบบฟอร์มสรุปผลการตรวจนับ Stock สินค้า</td>
    </tr>
    <tr>
      <td colspan="3">--------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="44%">[ &nbsp;&nbsp;&nbsp;] OP</td>
          <td width="38%">[ &nbsp;&nbsp;&nbsp;] CPS</td>
          <td width="18%">[ &nbsp;&nbsp;&nbsp;] GNC</td>
          </tr>
      </table></td>
      </tr>
    <tr>
      <td colspan="3">ประเภทการตรวจนับ</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% ตามรอบปกติ</td>
      <td>[ &nbsp;&nbsp;&nbsp;] 100% โอนย้าย/ลาออก</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;] สุ่มตรวจ 1,2</td>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% ปิด Shop</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% ตามรอบปกติ</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">[ &nbsp;&nbsp;&nbsp;]  100% อื่นๆ</td>
    </tr>
    <tr>
      <td colspan="3">จุดขาย.........................................................................................................................................</td>
      </tr>
    <tr>
      <td>รหัส........................................</td>
      <td>วันที่ตรวจนับ...................................................................</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">--------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
  </table></td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td>&nbsp;</td>
      <td align="center">UNIT</td>
      <td align="center">BAHT</td>
    </tr>
    <tr>
      <td>Stock สินค้าคงเหลือจุดขาย ณ วันตรวจนับ</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>ยอดจำนวนสินค้าที่ตรวจนับได้จริง (สุ่ม...SKU)</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>สรุปการตรวจนับสต๊อก : </td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>สินค้าเกินจากตรวจเพื่อปรับเข้า STOCK</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>สินค้าแถมขาด จากการตรวจนับเพื่อ ปรับออก TO</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>สินค้าขาดจากการตรวจนับ เพื่อเปิดปิล Tester</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>สินค้าขาด</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>Ref. Doc. No. :</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>รวม</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
      <td align="center">[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="10%" rowspan="3" valign="top">หมายเหตุ</td>
          <td width="90%">............................................................................................................................</td>
        </tr>
        <tr>
          <td>............................................................................................................................</td>
        </tr>
        <tr>
          <td>............................................................................................................................</td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="2">เอกสาร........................................................................................................................</td>
          </tr>
        <tr>
          <td width="26%">ประจำเดือน....................................</td>
          <td width="74%">ที่ยังไม่เรียบร้อย ให้นำมา CLEAR</td>
        </tr>
        <tr>
          <td colspan="2">ภายใน.........................................................................................................................</td>
          </tr>
      </table></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table></td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td>ผู้จัดการร้าน......................................................................................................................</td>
          </tr>
        <tr>
          <td>ผู้ตรวจนับ..........................................................................................................................</td>
          </tr>
        <tr>
          <td>ผู้ช่วยผู้จัดการร้าน...........................................................................................................</td>
          </tr>
      </table></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td colspan="3">การเคลียร์ผล ขาด/เกิน Stock กับแผนก AUDIT</td>
          </tr>
        <tr>
          <td width="2%">1.</td>
          <td colspan="2">ยอดสรุป ณ จุดขาย ขาด/เกิน จำนวน........................................บาท</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">ปรับปรุงตามเอกสาร/หลักฐานแนบ จำนวน.................................บาท</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td width="53%">&nbsp;</td>
          <td width="45%">&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2"><table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td>OPERATION :</td>
              </tr>
            <tr>
              <td>...............................................................................................................................................</td>
              </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
              </tr>
          </table></td>
          </tr>
        <tr>
          <td>2.</td>
          <td colspan="2">ยอด STOCK ยกมาที่ทางบัญชีตรวจสอบ และ Confirm แล้ว</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">[&nbsp;&nbsp;&nbsp;&nbsp;] ถูกต้อง เป็นจำนวน.............................ชิ้น</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">[&nbsp;&nbsp;&nbsp;&nbsp;] ไม่ถูกต้อง เนื่องจาก........................................................</td>
          </tr>
        <tr>
          <td colspan="3">สรุปผลเช็ค STOCK สุทธิ [&nbsp;&nbsp;&nbsp;&nbsp;] ขาด  [&nbsp;&nbsp;&nbsp;&nbsp;] เกิน จำนวน....................บาท</td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2"><table width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td>OPERATION :</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
            <tr>
              <td>...............................................................................................................................................</td>
            </tr>
          </table></td>
          </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">APPROVED BY......................................................</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">INTERNAL AUDIT</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">&nbsp;</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">ลงชื่อ....................................................................</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2" align="center">ROM/ROC</td>
          </tr>
      </table></td>
    </tr>
  </table></td>
</tr>
</table>