<table width="40%" border="0" cellpadding="0" cellspacing="0">
<tr></tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="3" align="right"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="71%" >&nbsp;</td>
          <td width="29%" align="right"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return print_form_check_cash();"><span class="ui-icon ui-icon-print"></span>Print Form </a></td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td colspan="3" align="center">Documentation for counting money on branch</td>
    </tr>
    <tr>
      <td colspan="3">--------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
    <tr>
      <td colspan="3"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="44%">[ &nbsp;&nbsp;&nbsp;] OP</td>
          <td width="38%">[ &nbsp;&nbsp;&nbsp;] CPS</td>
          <td width="18%">[ &nbsp;&nbsp;&nbsp;] GNC</td>
          </tr>
      </table></td>
      </tr>
    <tr>
      <td colspan="3">Counting Type</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Normal Cycle</td>
      <td>[ &nbsp;&nbsp;&nbsp;] 100% Transfer/Resign</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;] Random Check 1,2</td>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Close Shop</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>[ &nbsp;&nbsp;&nbsp;]  100% Normal Cycle</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">[ &nbsp;&nbsp;&nbsp;]  100% Others</td>
    </tr>
    <tr>
      <td colspan="3">Branch.........................................................................................................................................</td>
      </tr>
    <tr>
      <td>No........................................</td>
      <td>Check Date...................................................................</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">-------------------------------------------------------------------------------------------------------------------------</td>
      </tr>
  </table></td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td>reserve change on branch :.................................................................Baht</td>
    </tr>
    <tr>
      <td>No. of Sales bill before check STOCK SL...........................................</td>
    </tr>
    <tr>
      <td>No. of Sales bill Start on Check Date </td>
    </tr>
    <tr>
      <td>STOCK SL..........................................To SL..........................................</td>
    </tr>
    <tr>
      <td>Total of cash on counted at branch....................................................Baht</td>
    </tr>
    <tr>
      <td>Deduction of bill sales that as a Cash...............................................................Baht</td>
    </tr>
    <tr>
      <td>On hand reserve change at branch.........................................................Baht</td>
    </tr>
  </table></td>
</tr>
<tr>
  <td>&nbsp;</td>
</tr>
<tr>
  <td><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td colspan="2">Documents with receipts Documents without receipts</td>
      </tr>
    <tr>
      <td>1._______________________________</td>
      <td>1._______________________________</td>
      </tr>
    <tr>
      <td>2._______________________________</td>
      <td>2._______________________________</td>
      </tr>
    <tr>
      <td>3._______________________________</td>
      <td>3._______________________________</td>
      </tr>
    <tr>
      <td>4._______________________________</td>
      <td>4._______________________________</td>
      </tr>
    <tr>
      <td>5._______________________________</td>
      <td>5._______________________________</td>
      </tr>
    <tr>
      <td>6._______________________________</td>
      <td>6._______________________________</td>
      </tr>
    <tr>
      <td>7._______________________________</td>
      <td>7._______________________________</td>
      </tr>
    <tr>
      <td>8._______________________________</td>
      <td>8._______________________________</td>
      </tr>
  </table></td>
</tr>
<tr>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>Amount of Summary total expenses that can accrual withdraw money at the company. ________________Baht</td>
</tr>
<tr>
  <td>Amount of Summary total expenses in this month___________________Baht</td>
</tr>
<tr>
  <td>[&nbsp;&nbsp;&nbsp;&nbsp;] Excess___________Baht [&nbsp;&nbsp;&nbsp;&nbsp;] Lack________________Baht</td>
</tr>
<tr>
  <td>&nbsp;</td>
</tr>
<tr>
  <td align="center">Counting person_______________________________</td>
</tr>
<tr>
  <td align="center">INTERNAL AUDIT</td>
</tr>
<tr>
  <td align="center">&nbsp;</td>
</tr>
<tr>
  <td align="center">Manager/Assistant store manager__________________________</td>
</tr>
<tr>
  <td align="center">(Branch)</td>
</tr>
<tr>
  <td align="center">&nbsp;</td>
</tr>
<tr>
  <td align="center"><table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td width="15%">Note : </td>
      <td width="85%">________________________________________________________</td>
      </tr>
    <tr>
      <td>&nbsp;</td>
      <td>________________________________________________________</td>
      </tr>
    <tr>
      <td>&nbsp;</td>
      <td>________________________________________________________</td>
      </tr>
    </table></td>
</tr>
</table>