<script>
$(document).ready( function() {
	viewproductinventories();
});
function viewproductinventories(){
	$.ajax({type: "POST",url: "/stock/stock/getrq",data:{},success:
	function(data){
		$("#viewproductinventories").html(data);
	}}); 
}

</script>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td colspan="2">
		<div id="viewproductinventories"></div>
	</td>
  </tr>
</table>