<script>
$(document).ready( function() {
	$("#product_id").focus();
	viewproductfixstock();
});
function process(event){
	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
	keyCode = event.which; // Firefox    
	if (keyCode == 13) {
		viewproductfixstock();
	}
}
function viewproductfixstock(){
	var product_id=$("#product_id").val();
	$.ajax({type: "POST",url: "/stock/stock/getproductfixstock",data:{product_id:product_id},success:
	function(data){
		$("#viewproductfixstock").html(data);
	}}); 
}

</script>
<?php 
$data=$this->data;
$data_stock=$this->data_stock;
?>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="20" width="12%" align="right" class="servBodL_right">PRODUCT CODE : </td>
    <td><input type="text" name="product_id" id="product_id" class="NFText" autocomplete="off" onkeypress="return process(event)"></td>
  </tr>
  <tr>
    <td colspan="2">
		<div id="viewproductfixstock"></div>
	</td>
  </tr>
  <tr>
  	<td colspan="2">
		<table border="0" width="100%">
			<tr>
				<td width="10%" class="servBodL_right">FIX QUANTITY : </td>
				<td width="8%" align="left"><?php echo number_format($data[0]['sum_qty'], 0, '.', ',');?></td>
				<td width="8%" class="servBodL_right">FIX AMOUNT : </td>
				<td align="left"><?php echo number_format($data[0]['sum_price'], 2, '.', ',');?></td>
			</tr>
			<tr>
				<td width="10%" class="servBodL_right">INVENTORY QUANTITY : </td>
				<td width="8%" align="left"><?php echo number_format($data_stock[0]['sum_qty'], 0, '.', ',');?></td>
				<td width="8%" class="servBodL_right">INVENTORY AMOUNT : </td>
				<td align="left"><?php echo number_format($data_stock[0]['sum_price'], 2, '.', ',');?></td>
			</tr>
		</table>
	</td>
  </tr>
</table>