
<style>
.flexigrid div.fbutton .view_product {
	background: url(/stock/img/view_choose.png) no-repeat center left;
}

.flexigrid div.fbutton .print {
	background: url(/stock/img/emblem_print.png) no-repeat center left;
}
</style>
<?php
$doc_no=$this->doc_no;
$sum=$this->sum;
$status_no=$this->status_no;
$chkdocno=$this->chkdocno;
?>
<center>
<table width="100%" bgcolor="#c6ffe8">
	<tr>
		<td><table id="flex1" style="display:none"></table></td>
	</tr>
	<tr>
		<td>
			<table width="100%" border="0" cellpadding="2" cellspacing="2" align="center">
				<tr>
					<td colspan="3" width="38%" height="35" align="right" background="/stock/img/bg_g.gif" class="font_sum">Total :&nbsp;</td>
					<td width="10%" align="center" background="/stock/img/bg_y.gif" class="font_sum"><?php echo number_format($sum[0]['quantity'], 0, '.', ',');?></td>
					<td align="center" width="10%" background="/stock/img/bg_y.gif" class="font_sum"><?php echo number_format($sum[0]['price'], 2, '.', ',');?></td>
					<td align="left" colspan="2" background="/stock/img/bg_g.gif"></td>
				</tr>
				<tr>
					<td colsapan="3" height="30"></td>
					<td width="10%" align="right" class="longfont"></td>
					<td align="center" colspan="4">
					<table width="100%" border="0" cellpadding="2" cellspacing="2">
							<tr>
								<td><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="<?php if($status_no=="61"){?>return tranfer_tranin2shopheadtodiary();<?php }else{?>tranfer_tranin2shopheadtodiary_checkstock();<?php }?>"><span class="ui-icon ui-icon-disk"></span>Save (F3)</a>
								<a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return tranfer_cancel();"><span class="ui-icon ui-icon-cancel"></span>Cancle (F4) </a></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<input type="hidden" name="doc_no" id="doc_no" value="<?php echo $doc_no;?>">
<input type=hidden name="chk" id="chk" value="<?php echo $chkdocno;?>">
</center>
<script type="text/javascript">
$(function() {	
	//all hover and click logic for buttons
		$(".fg-button")
		.hover(
			function(){ 
				$(this).addClass("ui-state-hover"); 
			},
			function(){ 
				$(this).removeClass("ui-state-hover"); 
			}
		)
		.mousedown(function(){
				$(this).parents('.fg-buttonset-single:first').find(".fg-button.ui-state-active").removeClass("ui-state-active");
				if( $(this).is('.ui-state-active.fg-button-toggleable, .fg-buttonset-multi .ui-state-active') ){ $(this).removeClass("ui-state-active"); }
				else { $(this).addClass("ui-state-active"); }	
		})
		.mouseup(function(){
			if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button,  .fg-buttonset-multi .fg-button') ){
				$(this).removeClass("ui-state-active");
			}
		});
	});
var pWidth=(screen.width-(screen.width*(20/100)))-20;
var pWidth=(screen.width-(screen.width*(2/100)))-20;
var pWidth=(screen.width-(screen.width*(3/100)))-20;
var txt="Transfer In <?php if(!empty($doc_no)){echo " : ".$doc_no;}?>";
$("#flex1").flexigrid({
	url: 'getdataproducttranfer?doc_no=<?php echo $doc_no;?>',
	dataType: 'json',
	colModel : [
		{display: '#', name : 'seq', width : 45, sortable : true, align: 'center'},
		{display: 'Product ID', name : 'product_id', width : 95, sortable : true, align: 'center'},
		{display: 'Description', name : 'product_name', width : 250, sortable : true, align: 'left'},
		{display: 'Price', name : 'price', width : 95, sortable : true, align: 'center'},
		{display: 'Quantity', name : 'quantity', width : 90, sortable : true, align: 'center'},
		{display: 'Amount', name : 'dif', width : 95, sortable : false, align: 'center'},
		{display: 'Product Type', name : 'product_status', width : 95, sortable : true, align: 'center'}
		],
		searchitems : [
		{display: 'รหัสสินค้า', name : 'procuct_id'}
		],
	sortname: "seq",
	sortorder: "asc",
	usepager: true,
	title: txt,
	useRp: true,
	rp: 30,
	showTableToggleBtn: true,
	onSubmit: addFormData,
	height: 300
});

function productaction(com, grid) {
	var doc_no=$("#doc_no").val();
	if($('.trSelected',grid).length>0){
		var items = $('.trSelected',grid);
		var itemlist ='';
		for(i=0;i<items.length;i++){
			itemlist+= items[i].id.substr(3)+",";
			//itemlist= items[i].id.substr(3);
		}
	}
	if (com == 'แสดงรายการสินค้า') {
		if(itemlist==undefined){
			jAlert('คุณยังไม่เลือกรายการสินค้า!', 'แจ้งเตือน');
		}else{
			$.ajax({type: "POST",url: "/stock/checkstock/viewporductcheckdif",data:{product_id:itemlist,doc_no:doc_no},success:
				function(data){
					$( "#view_productcheckdif" ).html(data);
					$( "#view_productcheckdif" ).dialog( "open" );
				}
			});
		} 
	}
}

function addFormData(){
	var dt = $('#sform').serializeArray();
	$("#flex1").flexOptions({params: dt});
	return true;
}
	
$('#sform').submit(function (){
	$('#flex1').flexOptions({newp: 1}).flexReload();
	return false;
});
</script>