<?php

        // echo "this date=".$this->date;
        // echo "</br>";
        // echo "To count=".$this->count;
        // echo "</br>";
        // echo "request password=".$this->reqpwd;
        // echo "</br>";
        // echo "true password=".$this->truepwd;
        if($this->key_branch_id==$this->dest_branch_id){
            echo "Y";
        }else{
            echo "N";
            // echo "N".$this->key_branch_id.$this->dest_branch_id;
        }



?>