<?php 
$doc_tp=$this->doc_tp;
$status_no=$this->status_no;
$status_lock=$this->status_lock;
//status->y=ล็อค key,n=ไม่ล็อค key
?>
<script>
$(document).ready( function() {
	$("#invoice").focus();
	form_data();
	$('input[name="qty"]').keyup(function(e){
	    this.value = this.value.replace(/\D/g,'');
	});
		
});
function form_data(){
	var doc_tp=$("#ti_doc_no").val();
	var status_no=$("#ti_status_no").val();
	$.ajax({type: "POST",url: "/stock/stock/formdata",data:{doc_tp:doc_tp,status_no:status_no},success:
		function(data){
			$("#viewproducttranfer").html(data);
		}
	});
}
function process(event,p){
	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
	keyCode = event.which; // Firefox    
	if (keyCode == 13) {
		if(p=="check_docno"){
			$("#doc_remark").focus();
		}
		if(p=="check_doc_remark"){
			$("#product_id").focus();
		}
		if(p=="check_product"){
			var product_id=$("#product_id").val();
			var flag=product_id_master(product_id);
			if(flag=="y"){
				$("#qty").focus();
			}
		}
		if(p=="gen_tmpdiary"){
			gen_tmp2headshop('<?php echo $doc_tp;?>','<?php echo $status_no;?>');
		}
	}
}
</script>
<form id="frm_tranferkeyti">
<div id="dialog_disable" title=""></div>
<div id="dialog_process" title="Process"></div>
<table width="100%" border="0" cellpadding="0" cellspacing="3" background="/stock/img/bg_header.gif">
  <tr>
  	<td colspan="6" height="5"></td>
  </tr>
  <tr>
    <td width="17%" align="right" class="servBodL_right">Transfer Type : </td>
    <td width="5"><input type="text" name="type_tranfer" id="type_tranfer" size="28" value="62 - Key In Data Transfer In" class="NFText_hidden" disabled="disabled" onkeypress=""></td>
    <td width="2%">&nbsp;</td>
    <td width="10%" align="right" class="servBodL_right">Product Type : </td>
    <td width="3%"><input type="text" name="type_product" id="type_product" value="N" size="2" disabled="disabled" class="NFText_hidden" onkeypress=""></td>
 	<td>&nbsp;</td> 
  </tr>
  <tr>
    <td align="right" class="servBodL_right">Insert Invoice No. :</td>
    <td colspan="5"><input type="text" name="invoice" id="invoice" size="25" onkeypress="return process(event,'check_docno')" class="NFText" /></td>
  </tr>
  <tr>
    <td align="right" class="servBodL_right">Note :</td>
    <td colspan="5"><input type="text" name="doc_remark" id="doc_remark" size="50" onkeypress="return process(event,'check_doc_remark')" class="NFText" /></td>
  </tr>
  <tr>
    <td width="17%" align="right" class="servBodL_right">Product ID : </td>
    <td width="5" colspan="2"><input type="text" name="product_id" id="product_id" size="25" onkeypress="return process(event,'check_product')" class="NFText" onkeypress=""></td>
    <td width="10%" align="right" class="servBodL_right">Quantity : </td>
    <td width="3%" colspan="2"><input type="text" name="qty" id="qty" size="3" class="NFText" onkeypress="return process(event,'gen_tmpdiary')"></td>
  </tr>
  <tr>
	 <td colspan="6" height="5"></td>
  </tr>
</table>
</form>
<input type="hidden" name="ti_doc_no" id="ti_doc_no" value="<?php echo $doc_tp;?>"></input>
<input type="hidden" name="ti_status_no" id="ti_status_no" value="<?php echo $status_no;?>"></input>
<input type="hidden" name="check_lock" id="check_lock" value="<?php echo $status_lock;?>"></input>
<table width="100%" bgcolor="#fff">
<tr>
	<td align="center"><table id="viewproducttranfer"></table></td>
</tr>
</table>
<script>
check_lock();
function check_lock(){
	var check_lock=$("#check_lock").val();
	if(check_lock=="Y"){
		page_disable("<center>ไม่สามารถคีย์รับเข้าได้</center>");
	}
}
</script>