<?php
//@header("Content-type:text/html; charset=utf=8");
include(FPDF_PATH."/fpdf.php");
$pdf=new FPDF('P','mm','a23');
$pdf->SetThaiFont();
$pdf->SetMargins( 0,2,0 );  // ซ้าย , บน , ขวา

$pdf->AddPage();
$pdf->SetFont('CordiaNew','',5);
//$pdf->Cell( 0  , 4 , iconv( 'UTF-8','cp874' ,'วันที่ออกเอกสาร '.$this->print_time ) , 0 , 1,'R' );

$pdf->Image('/var/www/pos/htdocs/report/img/logo/op/op-logo.gif',8 ,0,0);
$pdf->SetFont('CordiaNew','B',10);
//$title1=iconv('UTF-8','cp874',"รายงานสรุปโอนสินค้าเข้า");

$line="----------------------------------------------------------------------------------------------";

$pdf->Ln(7);
$pdf->Cell(0,3,iconv('UTF-8','cp874','รายงานสรุปยอดคูปอง'),0,0,'C');
$pdf->Ln(3);
$pdf->Cell(0,3,iconv('UTF-8','cp874',"ประจำวันที่  ".$this->s_date." - ".$this->e_date),0,1,'C');
$pdf->Ln(2);
$pdf->Cell( 40  , 3 , iconv( 'UTF-8','cp874' ,'วันที่พิมพ์เอกสาร '.$this->print_time ),0,0,'L');
$pdf->Cell( 28  , 3 , iconv( 'UTF-8','cp874' ,'เวลา '.$this->ptime ),0,0,'R');
$pdf->Ln(3);
$pdf->Cell(0,3,iconv('UTF-8','cp874','จุดขาย : '.$this->branch_id .' ('.$this->branch_name .')' ));
$pdf->Ln(3);

$pdf->SetFont('CordiaNew','',11);
$pdf->Cell(0,3,$line);
$pdf->Ln(4);

$a = 5;
$b = 18;
$c = 30;
$d = 27;

$pdf->Cell( $a  , 4 , iconv( 'UTF-8','cp874' , '#' ) , 0 , 0 );
$pdf->Cell( $b  , 4 , iconv( 'UTF-8','cp874' , 'วันที่' ) , 0 , 0 ,'L' );
$pdf->Cell( $c  , 4 , iconv( 'UTF-8','cp874' , 'รายละเอียด' ) , 0 , 0,'L' );
$pdf->Cell( $d  , 4 , iconv( 'UTF-8','cp874' , 'ยอดรวม' ) , 0 , 1,'L' );

$pdf->Ln(1);
$pdf->Cell(0,3,$line,0,1);
$pdf->Ln(1);

$i=1;$bl=0;$ds=0; foreach ($this->get_data as $v){
	if ($v['countcoupon'] != '0'){
		$vcount = $v['countcoupon'];
	}else{
		$vcount = $v['count_promo_coupon'];
	}
	$pdf->Cell( $a  , 4 , iconv( 'UTF-8','cp874' , $i ) , 0 , 0  );
	$pdf->Cell( $b  , 4 , iconv( 'UTF-8','cp874' , $v['doc_date'] ) , 0 , 0 ,'L' );
	$pdf->Cell( $c  , 4 , iconv( 'UTF-8','cp874' , 'COUPON' ) , 0 , 0,'L' );
	$pdf->Cell( $d  , 4 , iconv( 'UTF-8','cp874' , $vcount ) , 0 , 1,'L' );
	$i++;
	$ba = $ba + $vcount ;
}
	
$pdf->Ln(2);
$pdf->Cell(0,2,$line,0,1);
$pdf->Ln(2);

	$pdf->Cell( $a  , 4 , iconv( 'UTF-8','cp874' , 'รวม' ) , 0 , 0 );
	$pdf->Cell( $a  , 4 , iconv( 'UTF-8','cp874' , $ba ) , 0 , 1  );

$pdf->Ln(4);
$pdf->Cell(0,2,$line,0,1);

$pdf->Ln(8);

$pdf->Cell( 28  , 4 , iconv( 'UTF-8','cp874' , 'ลายเซ็นต์พนักงานขาย  :  __________________________________' ) , 0 , 0 );

//$pdf->Ln(20);
//$pdf->Cell( 0  , 4 , iconv( 'UTF-8','cp874' , '.' ) , 0 , 0 );
//$pdf->Output();
$name='printcountcoupon.pdf';
$output="/var/www/pos/htdocs/reportshop/printreport/".$name;
//$pdf->Output($output,'F');
@chmod($output,0777);  
if(@file_exists($output)){
		 shell_exec("rm $output");
		@unlink($output);
	}
 
$pdf->Output($output,'F'); 
shell_exec("lp -o media=Letter $output");
	

?>

<script type="text/javascript">
//self.close();
</script>
		
