<style type="text/css">   
    .div-table{display:table; width: 600px; border: 1px; }
    .div-table-row{display:table-row;}
 
    .div-table-col1{display:table-cell; padding-left:  10px; padding-right:  100px; width: 250px;}
    .div-table-col2{display:table-cell; padding-left:  50px; }
    .div-table-col3{display:table-cell; padding-left:  50px; float: right;}
	.div-table-col4{display:table-cell; padding-left:  10px; width: 600px;}
	.div-table-col5{display:table-cell; padding-left:  20px; width: 30px;}
    .div-table-col6{display:table-cell; padding-left:  20px; width: 70px; }
    .div-table-col7{display:table-cell; padding-left:  20px; width: 70px; }
	.div-table-col8{display:table-cell; padding-left:  40px; width: 70px;}
	.div-table-col9{display:table-cell; padding-left:  50px; width: 150px;}
    
</style>

<p align="center">
    <img src="/report/img/logo/op/op-logo.gif">
    <br><br>สรุปยอดคูปอง<br>
    ประจำวันที่ <?php echo $this->s_date. " - " .$this->e_date ; ?><br>
	รหัสคูปอง <?php echo $this->c_start. " ถึง " .$this->c_end ; ?><br>     
</p>
    
<div class="div-table">
<div class="div-table-row">   
    <div class="div-table-col1">วันที่พิมพ์เอกสาร <?php echo $this->print_time ;?></div>
    
    <div class="div-table-col3">เวลา  <?php echo $this->ptime ;?></div>
    
</div>

<div class="div-table-row">
    <div class="div-table-col1">จุดขาย :  <?php echo $this->branch_id ." (".$this->branch_name.")" ;?></div>
    
    
</div>
</div>

<hr>

<div class="div-table">

	<div class="div-table-row">
          <div class="div-table-col5">#</div>
          <div class="div-table-col6">วันที่</div>
          <div class="div-table-col7">รายละเอียด</div>
          <div class="div-table-col8">ยอดรวม</div>
	</div>
</div>

<hr>

<div class="div-table">
	<?php $i=1;$b=0;$d=0; foreach($this->get_data as $v){	
	if ($v['countcoupon'] != '0'){
		$vcount = $v['countcoupon'];
	}else{
		$vcount = $v['count_promo_coupon'];
	}
		echo "<div class='div-table-row'>
					<div class='div-table-col5'>$i</div>
			        <div class='div-table-col6'>$v[doc_date]</div>
			        <div class='div-table-col7'>COUPON</div>
			        <div class='div-table-col8'>$vcount</div>
			  </div>";
		$i++;
		$b = $b + $vcount ;
		//$d = $d + $v[dis] ;
	}?>
	
</div>

<hr>

<div class="div-table">

	<div class="div-table-row">
          <div class="div-table-col5">รวม</div>
          <div class='div-table-col6'><?php echo $b ;?></div>
          <div class='div-table-col7'></div>
          <div class='div-table-col8'></div>
	</div>
</div>

<hr>

<?php 
	echo "<br><br><br>ลายเซ็นต์พนักงานขาย  :  __________________________________" ;
	
	$dayfrom =$this->dayfrom;
	$tofrom =$this->tofrom;
	$cstart = $this->c_start;
	$cend = $this->c_end;
	$today = date('Y-m-d');
	

	
	
	//if ($tofrom < $day ){
	    echo "<div align=right>
	<form action='/report/shop/printcountcoupon' method='post'>
	<input type=hidden id=start_date name=start_date value='$dayfrom'>
	<input type=hidden id=end_date name=end_date value='$tofrom'>
	<input type=hidden id=cstart name=cstart value='$cstart'>
	<input type=hidden id=cend name=cend value='$cend'>
	<input type=submit value= พิมพ์รายงาน  id=print>
	</form>
	
	</div>" ;
	/*}  else {
	echo "";    
	}*/

?>

