     <style type="text/css">  
			.tableNavLastOtherPro
				{
					width:100%;
					background:#333;
				}
			.tableNavLastOtherPro ul
				{
					float:right;
					width:100%;
					margin:0;
					padding:0;
					border:1px solid #C9C9C9;
				}
         
          .tableNavLastOtherPro ul li{
          		cursor:pointer;
					list-style-type:none;
					line-height:40px;
					font-family:"PSLKittithadaBold","Garuda","Tahoma", "Geneva", "Arial", sans-serif;
				
					font-weight: normal;
					font-size:25px;/*16*/
					text-decoration:none;
					color:#303030;
					padding-left:1em;
					
					border-bottom:1px solid  #78777C;
					text-shadow: 0px 1px 0px #dddddd;
				
					vertical-align: middle;
					white-space:nowrap;
					background:#B2B2B8;
					background:  -moz-linear-gradient(     #D4D7E0,     #B0B0B0);;
					background: -webkit-gradient(linear, left top, left bottom, color-stop(0,      #D4D7E0), color-stop(1, #B0B0B0));
					-moz-user-select:none;
					-moz-user-select:-moz-none;/*latest ff*/
					-webkit-user-select:none;
          }
          ul li.active {
            cursor:pointer;
          			list-style-type:none;
					line-height: 40px;
					font-family:"PSLKittithadaBold", "Garuda","Tahoma", "Geneva", "Arial", sans-serif;
				
					font-weight: normal;
					font-size:25px;/*16*/
					text-decoration:none;
					color:#ffffff;/*#303030*/
					padding-left:1em;
					
					border-bottom:1px solid  #000;/*78777C*/
					text-shadow: 0px 1px 0px #dddddd;
				
					vertical-align: middle;
					white-space:nowrap;
					background:#B2B2B8;
					background:  -moz-linear-gradient(#9DDCCF,#265541);/*#D4D7E0, #B0B0B0||#777777,#444444*/
					background: -webkit-gradient(linear, left top, left bottom, color-stop(0, #D4D7E0), color-stop(1, #B0B0B0));
					-moz-user-select:none;
					-moz-user-select:-moz-none;/*latest ff*/
					-webkit-user-select:none;
          }
          
          ul li.nokeyboard {
            color: #999;
            background:#0000ff;
          }
        </style>
    <div class="tableNavLastOtherPro">
    	<ul>
	    <?php
	    		//print_r($this->arr_promo);
	    		$str_promo="";	    		
		    	if(!empty($this->arr_promo)){ 
			        	$i=1;
			        	foreach($this->arr_promo as $data){
							$rows_json=json_encode($data);							
			  				$id_tmp="n_".$i;
				  			echo "<li id='$id_tmp' name='$id_tmp'  idpromo='".$rows_json."'>".$data['promo_code']."&nbsp;&nbsp;".$data['promo_des']."</li>";  
				  			$i++;
			  			}//foreach			  			
		    	}else{
		    		echo "<li align='center' id='n_1' name='n_1' idpromo='".$str_promo."'>ไม่พบโปรโมชั่น กรุณาตรวจสอบอีกครั้ง</li>";
		    	}
	        ?>
	    </ul>
     </div>