<div>
<table width="100%" border="0" cellpadding="0" cellspacing="3" bgcolor="#CFE2E5">
	<tr>
		<td width="40%">
		<!--	group search	-->
		<table width="100%" border="0" cellpadding="0" cellspacing="3" bgcolor="#CFE2E5">
			<tr>
				<td width="80" align="right"><span style="color:#000">MEMBER ID.&nbsp;</span></td>
				<td width="180">
					<input type="text" id="sch_member_no" size="25" class="input-text-pos"></input>
				</td>	
			</tr>
			<tr>
				<td width="80" align="right"><span style="color:#000">NAME&nbsp;</span></td>
				<td width="180">
					<input type="text" id="sch_member_name" size="25" class="input-text-pos"></input>
				</td>
			</tr>
			<tr>
				<td width="80" align="right"><span style="color:#000">SURNAME&nbsp;</span></td>
				<td>
					<input type="text" id="sch_member_surname" size="25" class="input-text-pos"></input>
				</td>
			</tr>
			<tr>
			
				<td width="80" align="right"><span style="color:#000">ID CARD&nbsp;</span></td>
				<td width="180">
					<input type="text" id="sch_id_card" size="25" class="input-text-pos"></input>
				</td>
			</tr>
			<tr>
				<td width="80" align="right"><span style="color:#000">TEL&nbsp;</span></td>
				<td>
					<input type="text" id="sch_mobile_no" size="25" class="input-text-pos"></input>
				</td>
			</tr>
			</table>
				<!--	group search	-->
				</td>
				<td width="60%" >
				<!--	group info	-->
				<textarea rows="7" cols="55" id="sch_member_info">
				</textarea>
				<!--	group info	-->
				</td>
			</tr>
			<tr>
				<td colspan="2">
				<div id="sch_member_content"></div>
				</td>
			</tr>
		</table>
</div>