<table width="100%" height="100%" border="0">
	<tr>
		<td>
		<table border="0" cellpadding="2" cellspacing="0">
			<tr>
			<td>จำนวน</td>
			<td><input type="text" size="2" id="input_giftset_quantity" name="input_giftset_quantity" value="1" class="input-text-pos ui-corner-all" readonly></input></td>
			<td>สินค้า</td>
			<td><input type="text" id="input_giftset_product" name="input_giftset_product" size="20" class="input-text-pos ui-corner-all"></input></td>
			<td>
			<button id="btn_giftset_submit">ตกลง</button>
			</td>
			</tr>			
		</table>
		</td>
	</tr>
</table>