<form id="frmReceiveReward">
<table width="100%" border="0" cellpadding="2" cellspacing="1" bgcolor="#cccccc">
<tr bgcolor="#F3FDF9">
	<td align="center">วันที่</td>
	<td align="center">เลขที่เอกสาร</td>
	<td align="center">รหัสของรางวัล</td>
	<td align="center">จำนวนที่แลก</td>
	<td align="center">รับไปแล้ว</td>
	<td align="center">คงเหลือ</td>
	<td align="center">จำนวนที่รับ</td>
</tr>
<?php
	if(!empty($this->arr_data)){
		$i=0;
		foreach($this->arr_data as $data){
			$arr_docdate=explode('-',$data['doc_date']);
			$doc_date=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
			$doc_no=$data['doc_no'];
			$product_id=$data['product_id'];
			$seq=$data['seq'];
			
			$balance=$data['quantity']-$data['promo_qty'];
			$balance=intval($balance);
			$quantity=intval($data['quantity']);
			($i%2==0)?$bg_color="#FFFFFF":$bg_color="#F4F4F4";
			echo "<tr bgcolor='$bg_color'>
					<td align='center'>$doc_date</td>
					<td align='center'>$doc_no</td>
					<td align='center'>$product_id</td>
					<td align='center'>$quantity</td>
					<td align='center'>$data[promo_qty]</td>
					<td align='center'><input type='text'  class='listrwd_balance' size='5' value='$balance' disabled style='text-align:right'></td>
					<td align='center'><input type='text' id='$doc_no@$product_id@$seq' txt_balance='$balance'  class='listrwd' size='5' style='text-align:right'></td>
				</tr>";
			$i++;
		}
		
	}else{
		echo "<tr bgcolor='#f2f2f2'>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>";
	}
?>
</table>
<table width="100%" height="80" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
		<tr>
			<td>&nbsp;</td>
			<td width="5%">
				<a href="#" name="btnSave" id="btnSave" class='btnGrayClean'>บันทึก</a>
			</td>
			<td width="1%">&nbsp;</td>
			<td width="5%">
				<a href="#" name="btnCancel" id="btnCancel" class='btnGrayClean'>ยกเลิก</a>
			</td>
			<td width="10%">&nbsp;</td>
		</tr>
	</table>
	</form>