<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge, chrome=1" />
<meta name="description" content="Retail Soft" />
<title>POS2011</title>
<link rel="stylesheet" href="/pos/theme/assets/css/reset.css" />
<link rel="stylesheet" href="/pos/theme/assets/css/desktop.css" />
<script src="/pos/theme/assets/js/jquery-1.5.1.min.js"></script>
<script src="/pos/theme/assets/js/jquery-ui-1.8.12.custom.min.js"></script>
<script src="/pos/theme/assets/js/jquery.tools.min.js"></script>
<link rel="stylesheet" href="/pos/theme/assets/css/clock.css" />
<script src="/pos/theme/assets/js/jquery.clock.js"></script>
<script src="/pos/js/jquery.jclock-1.2.0.js"></script>
<script>
  !window.jQuery && document.write(unescape('%3Cscript src="/pos/theme/assets/js/jquery.js"%3E%3C/script%3E'));
  !window.jQuery.ui && document.write(unescape('%3Cscript src="/pos/theme/assets/js/jquery.ui.js"%3E%3C/script%3E'));
</script>
<script src="/pos/theme/assets/js/jquery.desktop.js"></script>
<link href="/sales/js/plugin/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen"/>
<script type="text/javascript" src="/sales/js/plugin/jquery.alerts.js"></script>
<link rel='stylesheet' type='text/css' href='/stock/css/style.css'>
<script type="text/javascript" src="/pos/plugin/jquery.marquee/lib/jquery.marquee.js"></script>
<link type="text/css" href="/pos/plugin/jquery.marquee/css/jquery.marquee.css" rel="stylesheet" title="default" media="all" />
<script type="text/javascript" src="/pos/js/index/index.js"></script>

</head>
<body autocomplete="off">
<ul id='marquee6' class='marquee'><li><span class='author'>Pook says:</span>ข่าวสั้นวันนี้</li></ul>
<div class="abs" id="wrapper">
  <div id="program_info">POS Online V.1.0.01</div>
  <div id="msgmonitor"><a href="" class="hide_message"></a></div>
  <div id="xxlogoretail" class="draggable" style="z-index:10"></div> 
  <div id="ssup_logo" class="draggable" style="z-index:10"></div> 
  <div id="desktop" class="abs">
  <?php echo $this->layout()->content;?>
</div>  
  <div class="abs" id="bar_bottom">
    <a class="float_left" href="#" onclick='logoutConfirm()' title="LogOut">
      <img src="/pos/images/icon/big_logout.png" />
    </a>
    <ul id="dock"></ul> 
    <span class="float_right">USER LOGIN : 
    <?php
     echo $this->name; 
     echo " ";
     echo $this->surname;
    ?>
    </span>
  </div>  
  
  
</div>

</body>
</html>