<script>
$(document).ready( function() {
	$("#passw").focus();
});
function process(event){
	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
	keyCode = event.which; // Firefox    
	if (keyCode == 13) {
		var passw=$("#passw").val();
		check_password(passw);
	}
}
</script>

<?php 
$date=$this->date;
?>
<table width="100%" border="0" cellpadding="0" cellspacing="2" bgcolor="#e9f2f8" background="/stock/img/bg_header.gif">
  <tr>
  	<td colspan="5" height="5"></td>
  </tr>
  <tr>
    <td width="15%" align="right" class="servBodL_right">วันที่เช็คสต๊อก : </td>
    <td width="5"><input type="text" name="check_date" id="check_date" size="25" value="<?php echo $date;?>" class="NFText" disabled="disabled" onkeypress=""></td>
    <td width="2%">&nbsp;</td>
 	<td>&nbsp;</td> 
  </tr>
  <tr>
  	<td colspan="5" height="2%"></td>
  </tr>
  <tr>
    <td height="20" align="right" class="servBodL_right">ป้อนรหัสผ่าน : </td>
    <td width="10%"><input type="password" name="passw" id="passw" size="25" class="NFText" autocomplete="off" onkeypress="return process(event)"></td>
    <td colspan="3"><div id="showname"></div></td>
  </tr>
  <tr>
    <td></td>
    <td colspan="4"><div id="button_process"></div></td>
 </tr>
 <tr>
 	<td colspan="5"><div id="view_random_stock"></div></td>
 </tr>
</table>
