<style type="text/css">
	/* Button Gray Clean */
a.btnGrayClean{
		border:#BBB 1px solid;
		color:#5f5e5e;
		display:block;
		float:left;
		padding:2px 10px;
		margin-right:10px;
		cursor:pointer;
		text-decoration:none;
	}
a:hover.btnGrayClean{text-decoration:none; background:#FFF;}

/* Rounded Corners */
.rounded, a.btnGrayClean{
		-webkit-border-radius:6px;
		-moz-border-radius:6px;
		border-radius:6px;
		-khtml-border-radius: 6px;
}

/* Drop Shadow */
.shadow, a.btnGrayClean{
		-moz-box-shadow: 0px 1px 3px #AAA;
		-webkit-box-shadow: 0px 1px 3px #AAA;
		box-shadow: 0px 1px 3px #AAA;
}

/* Default Grey Gradient */
.gradient, a.btnGrayClean{
		background: #FFF; /* for non-css3 browsers */
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFFFFF', endColorstr='#DDDDDD'); /* for IE */
		background: -webkit-gradient(linear, left top, left bottom, from(#FFF), to(#DDD)); /* for webkit browsers */
		background: -moz-linear-gradient(top,  #FFF,  #DDD); /* for firefox 3.6+ */
}
a.btnGrayDisabled{
		border:#BBB 1px solid;
		color:#5f5e5e;
		display:block;
		float:left;
		padding:2px 10px;
		margin-right:10px;
		cursor:pointer;
		text-decoration:none;
	}
a:hover.btnGrayDisabled{text-decoration:none; background:#CCC;}

/* Rounded Corners */
.rounded, a.btnGrayDisabled{
		-webkit-border-radius:6px;
		-moz-border-radius:6px;
		border-radius:6px;
		-khtml-border-radius: 6px;
}

/* Drop Shadow */
.shadow, a.btnGrayDisabled{
		-moz-box-shadow: 0px 1px 3px #AAA;
		-webkit-box-shadow: 0px 1px 3px #AAA;
		box-shadow: 0px 1px 3px #AAA;
}

/* Default Grey Gradient */
.gradient, a.btnGrayDisabled{
		background: #FFF; /* for non-css3 browsers */
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#CCCCCC', endColorstr='#222222'); /* for IE */
		background: -webkit-gradient(linear, left top, left bottom, from(#CCC), to(#222)); /* for webkit browsers */
		background: -moz-linear-gradient(top,  #FFF,  #DDD); /* for firefox 3.6+ */
}

/* TEST ACCORDION 05042012*/
</style>
<table width="100%" height="100%" bgcolor="#FFFFFF">
	<tr>
		<td valign="TOP">
			<!-- ######### start ##########-->
			<table border="0" width="100%" cellpadding="2" cellspacing="3" style="background:#F3FDF9 url(/stock/img/bg_header.gif) repeat-x;">
				<tr>
					<td colspan="2">
						<table width="100%" border="0" cellspacing="0" cellpadding="0"  style="background:#F3FDF9 url(/stock/img/bg_header.gif) repeat-x;">
							<tr bgcolor="#B9E7CF" height="40">
								<td>
								<img src="http://localhost/sales/img/icon_bag_32x32.png" align="absmiddle"/>
								&nbsp;<span style='font-size:24px;color:#454545;'>Daily Sales Report</span>		
								</td>
							</tr>							
						</table>
					</td>
				</tr>
				
			
				
				<tr>
					<td align="right" width="20%">Start&nbsp;:</td>
					<td><input type="text" name="date_start" id="date_start" size="15" class="input-text-pos"></input></td>
					<input type="hidden" name="date_start_alternate" id="date_start_alternate"></input>
				</tr>
				<tr>
					<td align="right">To&nbsp;:</td>
					<td><input type="text" name="date_stop" id="date_stop" size="15" class="input-text-pos" readonly></input></td>
					<input type="hidden" name="date_stop_alternate" id="date_stop_alternate"></input>
				</tr>
				
				<tr height="35">		
					<td>&nbsp;</td>		
					<td>
						<a href="#" name="btn_commit" id="btn_commit" class="btnGrayClean">ตกลง</a>
						&nbsp;
						<a href="#" name="btn_cancel" id="btn_cancel" class="btnGrayClean">ยกเลิก</a>
					</td>
					
				</tr>
			</table>
			<!-- ######### stop ##########-->
		</td>
	</tr>
</table>
<input type="hidden" name="doc_type_question" id="doc_type_question" value="<?php echo $this->doc_tp;?>"></input>
<div id="dlgRptPreviews"></div>
<div id='dlgFormSelPrinter'></div>
<script type="text/javascript">
	function popup(url,name,windowWidth,windowHeight){
		/**
		*@descselectPrinter()
		*@param String url
		*@param String name
		*@param Integer windowWidth
		*@param Integer windowHeight
		*@return
		*/
	    myleft=(screen.width)?(screen.width-windowWidth)/2:100;
	    mytop=(screen.height)?(screen.height-windowHeight)/2:100;
	    properties = "width="+windowWidth+",height="+windowHeight;
	    properties +=",scrollbars=yes, top="+mytop+",left="+myleft;
	    window.open(url,name,properties);
	} 
	
	function printBill(date_start,date_stop,str_printer){
		/**
		*@desc
		*@param String doc_no
		*@param String doc_tp
		*@return
		*/
		var arr_printer=str_printer.split('#');
		var printer_name=arr_printer[0];
		var printer_type=arr_printer[1];
		var url2print='/report/summary/rptdailysales';
		if(printer_type=='INKJET'){
			url2print='/report/summary/rptdailysalesa4';
		}
		//alert("date_start=>" + date_start + "date_stop=>" + date_stop + " url2print :: " +url2print);
		//popup(url2print + "?date_start=" + date_start + "&date_stop=" + date_stop + "&rnd="+Math.random(),"",500,500);//for test
		//return false;
		var opts_report={
				type:'post',
				url:url2print,
				cache:false,
				data:{
					date_start:date_start,
					date_stop:date_stop,
					printer_name:printer_name,
					rmd:Math.random()
				},
				success:function(){		
					//window.parent.$('.ui-dialog-content:visible').dialog('close');
				}
			};		
		$.ajax(opts_report);		
	}//func

	/**
	*@desc
	*@param String doc_no
	*@return Printer name
	*/

	
	function selectPrinter(date_start,date_stop){
// 		if($("#dlgFormSelPrinter").dialog( "isOpen" )===true) {
// 			$("#dlgFormSelPrinter").close();			
//          }//if
		
		$("#dlgFormSelPrinter").dialog({
// 		$("<div id='dlgFormSelPrinter'></div>").dialog({
	       	   		autoOpen:true,
	  				width:'35%',		
	  				height:'200',	
	  				modal:true,
	  				resizable:true,
	  				position: { my: "center bottom", at: "center center", of: window },
	  				showOpt: {direction: 'up'},		
	  				closeOnEscape: false,
	  				title:"<span style='font-size:20px;font-weigth:bold;'>SELECT PRINTER</span> ",
	  				open: function(){ 	  			
						$("#dlgFormSelPrinter").html('');
		            	//print by printer name
		            	$.ajax({
			            	type:'post',
			            	url:'/report/summary/formselprinter',
			            	cache:false,
			            	data:{
				            	rnd:Math.random()
				            },
				            success:function(data){
				            	$("#dlgFormSelPrinter").html(data);
				            	
					        }
			            });
		            	//print by printer name
	  				},
	  				///////////////////////////XXX//////////////////////////
	  				  			
	  				
					buttons: [ 
					    { 
					        text: "PRINT",
					        id:"btnPrint",
					        class: 'ui-btndlgpos', 
					        click: function(evt){ 
								evt.preventDefault();
								//evt.stopPropagation();									
	 							var str_printer=$('select#printer').find('option:selected').val();	 							
	 							str_printer=$.trim(str_printer);
	 				           	if(str_printer.length<1){		
	 				           					 			
	 					 			jAlert('Please select printer.','Warning',function(){		
	 					 				$('#dlgFormSelPrinter').dialog('close');		
	 					 				$('#popup_ok').focus();
	 		    						setTimeout(function(){				    							
	 		    							if($('#popup_ok').not(":focus")){
	 				    						$('#popup_ok').focus();
	 				    					}
	 		    						},1000);
	 		    						$('#printer').focus();
	 									return false;
	 								});	
	 					 			return false;
	 					 		}else{
	 					 			printBill(date_start,date_stop,str_printer);
									$('#dlgFormSelPrinter').dialog('close');		
									
	 						 	}		
																							 		
						}
					   }					   
					],	


					
	  				
	  				
// 	  				buttons: {
// 					"PRINT":function(e){ 
// 						    e.preventDefault();
// 							var str_printer=$('select#printer').find('option:selected').val();
// 							//alert(str_printer);
// 							str_printer=$.trim(str_printer);
// 				           	if(str_printer.length<1){							 			
// 					 			jAlert('Please select printer name.','Warning',function(){		
// 					 				$('#popup_ok').focus();
// 		    						setTimeout(function(){				    							
// 		    							if($('#popup_ok').not(":focus")){
// 				    						$('#popup_ok').focus();
// 				    					}
// 		    						},1000);
// 		    						$('#printer').focus();
// 									return false;
// 								});	
// 					 			return false;
// 					 		}else{
// 					 			$(this).closest("#dlgFormSelPrinter").dialog('close');
// 					 			printBill(date_start,date_stop,str_printer);
// 						 	}		
// 				           	window.parent.$('.ui-dialog-content:visible').dialog('close');
// 				           	//$(this).parents(".ui-dialog-content").dialog('close');
// 				           	//window.parent.jQuery('#dlgFormSelPrinter').dialog('close');
// 				           	//$(this).dialog('close');					
// 				            //$(this).closest("#dlgFormSelPrinter").dialog('close');
// 							//$("#dlgFormSelPrinter").dialog('close');
// 							return false;
// 					}
// 				},
	  				///////////////////////////XXX//////////////////////////
	  				close:function(evt){
		            	$('#dlgFormSelPrinter').dialog('destroy');
		   			}
	          });
	}//func
	
	function resSearch(date_start,date_stop){
		var opts_QstDetail={
				autoOpen:false,
				width:'60%',
				height:'650',
				modal:true,
				resizeable:true,
				position:'top',
				showOpt: {direction:'up'},		
				closeOnEscape:true,	
				title:"Report Details",
				open:function(){					
					 $(this).parents(".ui-dialog:first").find(".ui-dialog-content").css({"padding":"0 .1em 0 .1em","margin":"0 0 0 0","background-color":"#FFFFFF"});
					$("*:focus").blur();
					$("#dlgRptPreviews").html("");
					$.ajax({
						type:'post',
						url:'/report/summary/rptdailysalespreviews',
						cache:false,
						data:{
						    date_start:date_start,
						    date_stop:date_stop,
							actions:'brows_docstatus',
							now:Math.random()
						},
						success:function(data){
							$("#dlgRptPreviews").html('');
							$("#dlgRptPreviews").html(data);
							$(this).parent().find('select, input, textarea').blur();
						}//end success function
					});//end ajax pos
				},
				buttons: {
					"PRINT":function(){ 	
							//printBill(date_start,date_stop);
							selectPrinter(date_start,date_stop);
							$('#dlgRptPreviews').dialog('close');
							
					}
				},
				close:function(){				
					$('#dlgRptPreviews').dialog('destroy');
				}
		};
		$('#dlgRptPreviews').dialog('destroy');
		$("#dlgRptPreviews").dialog(opts_QstDetail);
		$("#dlgRptPreviews").dialog("open");
	}//func
	
	$(function(){
		$("#date_start").datepicker({
			dateFormat: 'dd/mm/yy',altField: '#date_start_alternate',altFormat:'yy-mm-dd',
			onSelect: function(selectedDate) {
			    //alert(selectedDate);
			    var date_start=$('#date_start').val();
			    var alt_date_start=$('#date_start_alternate').val();
			    $('#date_stop').val(date_start);
			    $('#date_stop_alternate').val(alt_date_start);
			  }
			}
			
		);
		//$("#date_stop").datepicker({dateFormat: 'dd/mm/yy',altField: '#date_stop_alternate',altFormat:'yy-mm-dd'});
		$("#btn_commit").click(function(evt){
			evt.preventDefault();
			var date_start=$("#date_start_alternate").val();
			var date_stop=$("#date_stop_alternate").val();

//             alert(date_start + " :: " +date_stop);
// 			return false;

			
			resSearch(date_start,date_stop);			
		});
	});//ready
</script>