<?php	
	include(FPDF_PATH."/fpdf.php");
        $hl=5;
        $hl1=4;
        $hl2=3;
        $l2br=4;
        $maxdoc=72;
        $logo="/ssup_logo.gif";
        $pdf=new FPDF('P','mm','a23');
        $pdf->SetThaiFont();
        $pdf->AddPage();    
        $startY=2;
        $startX=0;
        $pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->SetMargins(0,2,0); 
        $pdf->SetAutoPageBreak("off",1);  
        $pdf->Image(LOGO_PATH.$logo,20,0,35);
        
        $startY+=10;
        $pdf->SetY($startY);
		$pdf->SetX($startX);
        $pdf->SetFont('CordiaNew','B',13); 
        $str_copy="";
        if($this->act=='reprint'){        	
        	$pdf->Cell(2,$hl,"*",0,0,'L',0); 
        	$str_copy="(COPY)";
        }      
       
       	$pdf->Cell($maxdoc,$hl,"SSUP (CAMBODIA) CO.LTD.",0,0,'C',0);
       	$startY+=$l2br;
       	$pdf->SetY($startY);
       	$pdf->SetX($startX);
       
		$str_cancel='';
		if($this->arr_h[0]['flag']=='C'){
			$str_cancel='<ยกเลิก>';
			$str_cancel=iconv('UTF-8','cp874',$str_cancel);
		}       
       
        $pdf->Cell($maxdoc,$hl,"$str_cancel www.orientalprincess.com $str_copy",0,0,'C',0);        
        
//         $startY+=$l2br;
//         $pdf->SetY($startY);
//         $pdf->Cell($maxdoc,$hl2,"(Daily Sales Report)",0,0,'C',0);
        $startY+=$l2br;
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->SetX($startX);
        
        $pdf->SetFont('CordiaNew','B',11);
        $pdf->Cell(18,$hl1,"Tenant code :",0,0,'L',0);
        $pdf->Cell(20,$hl1,"0000287",0,0,'L',0);
        $pdf->Cell(5,$hl1,"",0,0,'L',0);
        
        //$arr_docdate=explode("-",$this->doc_date);
        $arr_docdate=explode("-",date("Y-m-d"));
        $doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
        $pdf->Cell(29,$hl1,"Print Date : ".$doc_date_show,0,0,'R',0);
        
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->SetX($startX);
        $pdf->Cell(18,$hl1,"Tenant name :",0,0,'L',0);
        $pdf->Cell(54,$hl1,"SSUP (Cambodia) Co.LTD.",0,0,'L',0);
        
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->SetX($startX);
        $pdf->Cell(21,$hl1,"Document Date :",0,0,'L',0);
        $pdf->Cell(51,$hl1,$this->date_start." To ".$this->date_stop,0,0,'L',0);
        
      	$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
		$pdf->SetFont('CordiaNew','B',11);
		$pdf->Cell($maxdoc,$hl1,"Branch NO : ".$this->branch_id."  (".iconv('UTF-8','cp874',$this->branch_name).")",0,0,'L',0); 
						
		$pdf->SetFont('CordiaNew','',11);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		
		$pdf->Cell($maxdoc,1,"------------------------------------------------------------------------------------------",0,0,'L',0);
		$startY+=$hl;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		
		$pdf->Cell(33,$hl1,"Daily sales report ",0,0,'C',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,"Amount",0,0,'C',0);
		$startY+=$hl;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell($maxdoc,1,"------------------------------------------------------------------------------------------",0,0,'L',0);
		
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"1.Total Sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_sales_show,0,0,'R',0);
		
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"2.Vat ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->vat_show,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"3.Net Sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->net_sales_show,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"4.Number of customers ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_bill,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"5.Sattlement Number ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,'1',0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"6.Cash Sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_cash_sales_show,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"7.Credit/Debit Sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_credit_sales_show,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"8.Number of Credit/Debit Sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_credit_bill,0,0,'R',0);
      
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"9.Sales by other means ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,'0',0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"10.Number of cash voucher sales ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,'0',0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"11.Refund/Return Amount ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_cn_sales_show,0,0,'R',0);
		
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell(33,$hl1,"12.Number of Refund/Return ",0,0,'L',0);
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$pdf->Cell(33,$hl1,$this->total_cn,0,0,'R',0);
		
		$startY+=$hl;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->Cell($maxdoc,$hl2,"------------------------------------------------------------------------------------------",0,0,'L',0);
		$startY+=$hl;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		
	
		$startY+=$l2br;
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);		
       
        $pdf->SetFont('CordiaNew','B',11);
        $pdf->Cell($maxdoc,$hl1,"  ",0,0,'L',0);         
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 	
        
        $name='/billvatshort.pdf';
	    $output=REPORT_PATH.$name;    	    
	    @chmod(REPORT_PATH,0777);
	    $pdf->Output($output,'F');
		$print2ip=$this->arr_h[0]['print2ip'].":631";
		if($this->arr_h[0]['print2ip']=='LOCAL'){
			echo shell_exec("lp -o media=Letter $output");
		}else{
			echo shell_exec("lpr -H $print2ip $output");
		}
		if(@file_exists($output)){
			echo shell_exec("rm $output");
			//@unlink($output);
		}
?>