<table width="100%" height="100%" border="0" cellpadding="2" cellspacing="0" bgcolor="#FFFFFF">
<tr>
<td valign="TOP">
<table width="100%" border="0" cellpadding="2" cellspacing="1" >
	  <tr>
		<td width="10%" align="right" bgcolor="#e2e2e2">เลือกชุดข้อมูล</td>
		<td width="10%"><input type="radio" id="cardtype" name="cardtype" value="0" checked></input>ยังไม่บันทึกข้อมูล</td>
		<td><input type="radio" id="cardtype" name="cardtype" value="1"></input>บันทึกข้อมูลแล้ว</td>
	</tr>
</table>
<table id="tblRegCard"></table>
</td>
</tr>
</table>