<!-- 
<link href="/sales/css/themes/cupertino/jquery-ui-1.8.10.custom.css" rel="stylesheet" type="text/css"/>
-->
<style type="text/css">
.ui-datepicker {
    background: #99CCCC;
    border: 1px solid #ccc;
    color: #EEE;
}
.ui-datepicker-calendar {
    background:#ffffcc;
    border: 1px solid #ccc;
    color: #222;
}
.ui-datepicker th {
    background: #669999;
    border: 1px solid #ccc;
    color: #000;
}
</style>
<table width="100%" border="0" cellspacing="0" cellpadding="3" >
<tr>
	<td width='25%' align="right">วันที่ผลิต&nbsp;:</td>
	<td>
		<input type="text" size="10" id="lot_expire" class="input-text-pos"></input><span style="color:red;">*</span>
		<input type="hidden" name="lot_expire_alternate" id="lot_expire_alternate"></input>
	</td>
	
</tr>
<tr>
	<td width='25%' align="right">เลขที่ Lot ที่ผลิต&nbsp;:</td>
	<td><input type="text" size="10" id="lot_no" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
<tr>
	<td width='25%' align="right" valign="top">ระบุสาเหตุ&nbsp;:</td>
	<td>
		<textarea rows="3" cols="35" id="cn_remark2" name="cn_remark2" class="input-textarea-pos"></textarea><span style="color:red;">*</span>
	</td>
</tr>
</table>