<table width="100%" border="0" cellspacing="0" cellpadding="3" >
<tr>
	<td width='25%' align="right">ชื่อบัญชี&nbsp;:</td>
	<td><input type="text" size="25" id="acc_name" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
<tr>
	<td width='25%' align="right">เลขที่บัญชี&nbsp;:</td>
	<td><input type="text" size="25" id="bank_acc" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
<tr>
	<td width='25%' align="right">ชื่อธนาคาร/สาขา&nbsp;:</td>
	<td><input type="text" size="25" id="bank_name" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
<tr>
	<td width='25%' align="right">โทรศัพท์1&nbsp;:</td>
	<td><input type="text" size="10" id="tel1" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
<tr>
	<td width='25%' align="right">โทรศัพท์2&nbsp;:</td>
	<td><input type="text" size="10" id="tel2" class="input-text-pos"></input><span style="color:red;">*</span></td>
</tr>
</tr>
</table>