<?php
set_time_limit(0);
//include("toserver_stock_bk.php");
//include("toserver_stock_day.php");
//include("/var/www/pos/htdocs/download_promotion/keep_promotion_input_history_quick.php");
//include("/var/www/pos/htdocs/download_promotion/keep_promotion_input_history.php");
include("/var/www/pos/htdocs/download_promotion/toserver_bill_auto.php");
//include("/var/www/pos/htdocs/download_promotion/id_card_quick/send_change_profile.php");
//include("/var/www/pos/htdocs/download_promotion/id_card_quick/send_member_idcard.php");
?>