<?php
	include(FPDF_PATH."/fpdf.php");
	//------------------------------- Setup
	$hl=5;
	$ln2br=4;
	$maxdoc=72;
	$logo="/op-logo.gif";
	$pdf=new FPDF('P','mm','a23');
	$pdf->SetThaiFont();
	$pdf->AddPage();
	$startY=2;
	$startX=0;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetMargins(0,2,7); 
	$pdf->SetAutoPageBreak("off",1);
	$pdf->Image(LOGO_PATH.$logo,2,0,65);
	$pdf->SetY(8);
	$pdf->SetFont('FreesiaUPC','B',11); 

	//------------------------------ Data
	
	
	$pdf->Cell(0,$hl,iconv('UTF-8','cp874',"ใบรับ Picking List"),0,0,'C',0); 
	/*if($this->print_no > 0)
	{
		$pdf->Cell(0,$hl,iconv('UTF-8','cp874',"ใบรับ Picking List"),0,0,'C',0); 
	}*/
	$startY+=12;
	$pdf->SetY($startY);
	$pdf->SetX($startX);

	$doc_date = strtotime($this->data[0]["doc_date"]);
	$doc_date = date('d/m/Y', $doc_date);
	$limit_doc_no = 35;
	
	if(strlen($this->data[0]["doc_no"]) > $limit_doc_no)
	{
		$this->data[0]["doc_no"] = substr($this->data[0]["doc_no"],0,$limit_doc_no);
	}
	
	$pdf->SetFont('AngsanaNew','B',10);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"เลขที่ ".$this->data[0]["doc_no"]." "),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"วันที่ ".$doc_date." "),0,0,'R',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	//$this->branch_data = "SHOP พรอมเมนาดา เชียงใหม่ หกดไำดเพะ้ั้ะั้ห";
	if(strlen($this->branch_data) > 100)
	{
		$this->branch_data = substr($this->branch_data,0,100);
	}
	
    $pdf->Cell(150,$ln2br,iconv('UTF-8','cp874',"สาขา ".$this->branch_data." "),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"เวลา ".$this->data[0]["doc_time"]." "),0,0,'R',0);
    
	
	$pdf->SetMargins(5, 2, 7);
	
	$pdf->Cell(0,5,'',0,0,'C',0);
	$pdf->Ln();	
	
	//Column widths
	$w=array(7,33,10,10);
	$header=array('#','Picking No','จำนวน','หมายเหตุ');
	//Header	
	for($i=0;$i<count($header);$i++)
	{
		$pdf->Cell($w[$i],5,iconv('UTF-8','cp874',$header[$i]),1,0,'C',0);
	}
	$pdf->Ln();
	$startY+=5;
	
	$count=1;
	foreach($this->data as $row)
	{
		$pdf->Cell($w[0],5,$count++,'LR',0,'C',0);
		$pdf->Cell($w[1],5,$row["product_id"],'LR',0,'L',0);
		$pdf->Cell($w[2],5,number_format($row["quantity"]),'LR',0,'R',0);
		$pdf->Cell($w[3],5,$row["product_status"],'LR',0,'C',0);
		$pdf->Ln();
		$startY+=5;	    
	}
	$pdf->Cell(array_sum($w),0,'','T');
	$startY+=6;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->SetMargins(0,2,7); 
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"G : รหัสบาร์โค้ดสรุป Picking List / P : Picking List ที่ไม่มีสินค้าส่งมา"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	//$this->data[0]["doc_remark"] = "G : รหัสบาร์โค้ดสรุป Picking List / P : Picking List ที่ไม่มีสินค้าส่งมา 1345687923 regergergerger";
	
	if($this->data[0]["doc_remark"] != "")
	{
		if(strlen($this->data[0]["doc_remark"]) > 150)
		{
			$this->data[0]["doc_remark"] = substr($this->data[0]["doc_remark"],0,150);
		}
	    $pdf->MultiCell(70,$ln2br,iconv('UTF-8','cp874',"หมายเหตุ : ".$this->data[0]["doc_remark"]." "));
	    $startY+=$ln2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX);
	}
	
	$startY+=5;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"ผู้ออกเอกสาร __________________"),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"ผู้รับเอกสาร __________________"),0,0,'R',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"                     ( ".$this->data_emp." )"),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"(                                 )"),0,0,'R',0);
    $startY+=10;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->SetFont('AngsanaNew','',8);
	$pdf->Cell(0,$ln2br,' _ ',0,0,'C',0);
?>
		