<?php
	include(FPDF_PATH."/fpdf.php");
	//------------------------------- Setup
	$hl=5;
	$ln2br=4;
	$maxdoc=72;
	$logo="/op-logo.gif";
	$pdf=new FPDF('P','mm','a23');
	$pdf->SetThaiFont();
	$pdf->AddPage();
	$startY=2;
	$startX=0;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetMargins(0,2,7); 
	$pdf->SetAutoPageBreak("off",1);
	$pdf->Image(LOGO_PATH.$logo,2,0,65);
	$pdf->SetY(8);
	$pdf->SetFont('FreesiaUPC','B',11); 

	//------------------------------ Data
		
	$pdf->Cell(0,$hl,iconv('UTF-8','cp874',"ใบตรวจรับการส่งสินค้า"),0,0,'C',0); 
	$startY+=12;
	$pdf->SetY($startY);
	$pdf->SetX($startX);	

	$doc_date = strtotime($this->data[0]["doc_date"]);
	$doc_date = date('d/m/Y', $doc_date);
	$limit_doc_no = 35;
	
	if(strlen($this->data[0]["doc_no"]) > $limit_doc_no)
	{
		$this->data[0]["doc_no"] = substr($this->data[0]["doc_no"],0,$limit_doc_no);
	}
	
	$pdf->SetFont('AngsanaNew','B',10);	
	if($this->print_no > 0)
	{
	    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"พิมพ์ซ้ำครั้งที่ ".$this->print_no." "),0,0,'R',0);
	    $startY+=$ln2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX);	
	}
	else
	{
		if($this->page == "real")
		{
			$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"ต้นฉบับ"),0,0,'R',0);
		    $startY+=$ln2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX);	
		}
		else
		{
			$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"สำเนา"),0,0,'R',0);
		    $startY+=$ln2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX);	
		}
	}	
	
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"เลขที่ ".$this->data[0]["doc_no"]." "),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"วันที่ ".$doc_date." "),0,0,'R',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);	
	
	if(strlen($this->branch_data) > 100)
	{
		$this->branch_data = substr($this->branch_data,0,100);
		$this->branch_data = $this->branch_data."...";
	}
	
    $pdf->Cell(150,$ln2br,iconv('UTF-8','cp874',"สาขา ".$this->branch_data." "),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"เวลา ".$this->data[0]["doc_time"]." "),0,0,'R',0);
    
	
	$pdf->SetMargins(1, 2, 7);
	
	$pdf->Cell(0,5,'',0,0,'C',0);
	$pdf->Ln();	
	
	//Column widths
	$w=array(7,33,10,10,10);
	$header=array('#','Document No','สถานะ','จำนวน','หมายเหตุ');
	//Header	
	for($i=0;$i<count($header);$i++)
	{
		$pdf->Cell($w[$i],5,iconv('UTF-8','cp874',$header[$i]),1,0,'C',0);
	}
	$pdf->Ln();
	$startY+=5;
	
	$count=1;
	foreach($this->data as $row)
	{		
			$pdf->Cell($w[0],5,$count++,'LR',0,'C',0);
			$product_id = $row["product_id"];
			$product_status = $row["product_status"];
			if($product_id == "BOX001")
			{
				$product_id = "BOX001 (จำนวนกล่องที่ส่งคืน)";
				$product_status = intval($row['amount'],10);
			}
			$pdf->Cell($w[1],5,iconv('UTF-8','cp874',$product_id),'LR',0,'L',0);
			$pdf->Cell($w[3],5,$row["promo_st"],'LR',0,'C',0);
			$pdf->Cell($w[2],5,number_format($row["quantity"]),'LR',0,'R',0);
			$pdf->Cell($w[3],5,$product_status,'LR',0,'C',0);
			$pdf->Ln();
			$startY+=5;	    
		
	}
	/*$pdf->Cell(array_sum($w),0,'','T');
	$pdf->Cell(0,0,'',0,0,'C',0);
	$pdf->Ln();	
	foreach($this->data as $row)
	{		
		if($row["product_status"] == "P")
		{
			$pdf->Cell($w[0],5,$count++,'LR',0,'C',0);
			$pdf->Cell($w[1],5,$row["product_id"],'LR',0,'L',0);
			$pdf->Cell($w[2],5,number_format($row["quantity"]),'LR',0,'R',0);
			$pdf->Cell($w[3],5,$row["product_status"],'LR',0,'C',0);
			$pdf->Ln();
			$startY+=5;	    
		}
	}*/
	$pdf->Cell(array_sum($w),0,'','T');
	$startY+=6;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->SetMargins(0,2,7); 
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"G : ใบจัดส่งสินค้า / I : ใบกำกับสินค้า / P : ใบ Picking List"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"สถานะ    N : ปกติ / O : กล่องที่เกิน"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	//$this->data[0]["doc_remark"] = "ขออ้างอิงโค้ดจากนะครับ เนื่องจากเป็นเว็บ ที่ผมได้นำ โค้ดมาประยุกต์ พอทำไปเจอปัญหาที่เรียกว่าไม่สามารถทำ Loop ที่ดึงค่าจากฐานข้อมูลได้ และไม่สามารถหาวิธีแก้ไขได้";
		
	if($this->data[0]["doc_remark"] != "")
	{
		/*if(strlen($this->data[0]["doc_remark"]) > 150)
		{
			$this->data[0]["doc_remark"] = substr($this->data[0]["doc_remark"],0,150);
			$this->data[0]["doc_remark"] = $this->data[0]["doc_remark"]."...";			
		}*/
		$y=$pdf->GetY();
	    $pdf->MultiCell(0,$ln2br,iconv('UTF-8','cp874',"หมายเหตุ : ".$this->data[0]["doc_remark"]." "));
	    $y1=$pdf->GetY();
		
		$nrowPrinted=($y1-$y) /$ln2br;
		$pdf->SetY($y);
		for ($i=0; $i < $nrowPrinted; $i++) {
		$pdf->Cell(0, $ln2br,'', 0 ,0,'L',0);
			$startY+=$ln2br;
			$pdf->SetY($startY);
			$pdf->SetX($startX);
		}
	}
	
	$startY+=5;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"ผู้ออกเอกสาร __________________"),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"ผู้รับเอกสาร __________________"),0,0,'R',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"                     ( ".$this->data_emp." )"),0,0,'L',0);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"(                                 )"),0,0,'R',0);
    $startY+=10;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	
	$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"หมายเหตุ : "),0,0,'L',0);
	$startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX(3);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"1. พนักงานผู้รับสินค้าเซ็นต์ชื่อผู้ออกเอกสารทั้ง 2 ใบ"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX(5);
	$pdf->Cell(0,$ln2br,iconv('UTF-8','cp874'," ผู้ส่งสินค้าเซ็นต์ชื่อผู้รับเอกสารทั้ง 2 ใบ"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX(3);
    $pdf->Cell(0,$ln2br,iconv('UTF-8','cp874',"2. ต้นฉบับส่งคืนให้ผู้ส่งสินค้า 1 ใบ สาขาเก็บสำเนา 1 ใบ"),0,0,'L',0);
    $startY+=$ln2br;
    $pdf->SetY($startY);
	$pdf->SetX(5);
	
	$pdf->SetFont('AngsanaNew','',8);
	$pdf->Cell(0,$ln2br,' . ',0,0,'C',0);
	
	


	//$pdf->Output();

	 	$name='/rppicking';
        $name.='.pdf';
	    $output=REPORT_PATH.$name;
	    @chmod(REPORT_PATH,0777);	    
	    $pdf->Output($output,'F');	    
		$print2ip=$this->arr_h[0]['print2ip'].":631";
		if($this->arr_h[0]['print2ip']=='LOCAL'){
			echo shell_exec("lp -o media=Letter $output");
		}else{
			echo shell_exec("lpr -H $print2ip $output");
		}
		if(@file_exists($output)){
			echo shell_exec("rm $output");			
		}
?>
		