<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>photobooth</title>

<link rel="stylesheet" type="text/css" href="/pos/plugin/photobooth/assets/css/styles.css" />
<link rel="stylesheet" type="text/css" href="/pos/plugin/photobooth/assets/fancybox/jquery.fancybox-1.3.4.css" />

</head>
<body>


<div id="photos"></div>

<div id="camera">
	<span class="tooltip"></span>
	<span class="camTop"></span>
    
    <div id="screen"></div>
    <div id="buttons">
    	<div class="buttonPane">
        	<a id="shootButton" href="" class="blueButton">Shoot!</a>
        </div>
        <div class="buttonPane hidden">
        	<a id="cancelButton" href="" class="blueButton">Cancel</a> <a id="uploadButton" href="" class="greenButton">Upload!</a>
        </div>
    </div>
    
    <span class="settings"></span>
</div>

<script src="/pos/js/jquery-1.6.1.min.js"></script>
<script src="/pos/plugin/photobooth/assets/fancybox/jquery.easing-1.3.pack.js"></script>
<script src="/pos/plugin/photobooth/assets/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script src="/pos/plugin/photobooth/assets/webcam/webcam.js"></script>
<script src="/pos/plugin/photobooth/assets/js/script.js"></script>

</body>
</html>
