<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>บันทึกข้อมูลบริษัท</title>
<script src="/pos/js/jquery-1.7.1.min.js"></script>
<script src="/pos/plugin/MoleskineNotebook/booklet/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="/pos/plugin/MoleskineNotebook/booklet/jquery.booklet.1.1.0.min.js" type="text/javascript"></script>

<script src="/pos/plugin/MoleskineNotebook/cufon/cufon-yui.js" type="text/javascript"></script>
<script src="/pos/plugin/MoleskineNotebook/cufon/ChunkFive_400.font.js" type="text/javascript"></script>
<script src="/pos/plugin/MoleskineNotebook/cufon/Note_this_400.font.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="/pos/plugin/xhtml/css/screen.css" media="screen" />
		
<link href="/pos/plugin/MoleskineNotebook/booklet/jquery.booklet.1.1.0.css" type="text/css" rel="stylesheet" media="screen" />
<link rel="stylesheet" href="/pos/plugin/MoleskineNotebook/css/style.css" type="text/css" media="screen"/>

<link rel="stylesheet" href="/pos/css/black-tie/jquery-ui-1.8.10.custom.css" />
<script src="/pos/js/jquery-ui-1.8.18.custom.min.js"></script>
<script src="/pos/js/company/company.js"></script>

<link rel='stylesheet' type='text/css' href='/pos/css/style.css'>
 
</head>
<body>
<div  style='display:none' id='dialogupdatecompany'></div>
<div id='loading'  align='center' class='loading'></div>

<div class='book_wrapper'>		
<a id='next_page_button'></a>
<a id='prev_page_button'></a>

<div id='mybook' style='display:none;'>

	<div class='b-load'>
	<div  align='center'>
<table border="0" align="center">
	  <tr>
	    <td>&nbsp;</td>
	    <td><img src="/pos/images/logo/logo_ssup_new.jpg" /></td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td>รหัสบริษัท</td>
	    <td><div align="left">
	      <input name="texsearch" type="text"  id="texsearch" size="10" />
	      <input type="button" name="searchpage" id="searchpage" onclick='gotopagecompany()' value="ค้นหา" />
	      <input type="button" name="gotopage" id="gotopage" onclick='gotopage1()' value="เพิ่มใหม่" />
	      </div></td>
      </tr>
	</table>
	</div>
<form action='/pos/admin/insertcompany' method='post' enctype='multipart/form-data' name='formupdatcompany' id='formupdatcompany'>
				<fieldset >
					<legend class='ui-widget ui-widget-header ui-corner-all'>บันทึกข้อมูลบริษัท</legend>
									<div align='left'>
			  <table width='100%' border='0' align='center'>
			    <tr>
			      <td width='40%'><div align='right'>รหัสประเทศ</div></td>
			      <td width='60%'>
			      <?php echo $this->com_country_list;?></td>
	            </tr>
		        
		        <tr>
			      <td><div align='right'>จังหวัด</div></td>
			      <td><div id='div_province'><select name='zip_province_id' id='zip_province_id'> </select></div></td>
	            </tr>
		     	 <tr>
			      <td><div align='right'>เขต/อำเภอ</div></td>
			      <td><div id='div_amphur'><select name='zip_amphur_id' id='zip_amphur_id'>
			      </select></div>      </td>
	            </tr>   
		        
		       <tr>
			      <td><div align='right'>แขวง/ตำบล</div></td>
			      <td><div id='div_tambon'> <select name='zip_tambon_id' id='zip_tambon_id'>
			      </select></div></td>
	            </tr>
		        
		        <tr>
			      <td><div align='right'>รหัสไปรษณีย์</div></td>
			      <td><input name='postcode' type='text' id='postcode' size='10' /></td>
	            </tr>
		        
			    <tr>
			      <td><div align='right'>รหัสบริษัท</div></td>
			      <td><input name='corporation_id' type='text' id='corporation_id' size='10' /></td>
	            </tr>
			    <tr>
			      <td><div align='right'>รหัสช่องทางจำหน่าย</div></td>
			      <td><input name='company_id' type='text' id='company_id' size='10' /></td>
	            </tr>
			    <tr>
			      <td><div align='right'>ชื่อบริษัท</div></td>
			      <td><input name='company_name' type='text' id='company_name' size='25' /></td>
	            </tr>
			    
			    <tr valign='top'>
			      <td><div align='right'>ที่อยู่</div></td>
			      <td><input name="address" type="text" id="address" value="" size="25" /></td>
	            </tr>
				<tr valign='top'>
			      <td><div align="right">ชื่อบริษัทสำหรับพิมพ์</div></td>
			      <td><input name='company_name_print' type='text' id='company_name_print' size='25' /></td>
	            </tr>
			    <tr>
			      <td><div align='right'>ถนน</div></td>
			      <td><input name='road' type='text' id='road' size='25' /></td>
	            </tr>
			    <tr>
			      <td><div align='right'>เบอร์โทรศัพท์</div></td>
			      <td><input name='tel' type='text' id='tel' size='10' />
		           Fax. 
	              <input name='fax' type='text' id='fax' size='10' /></td>
	            </tr>
			    
			    <tr>
			      <td><div align='right'>เลขประจำตัวผู้เสียภาษี</div></td>
			      <td><input name='tax_id' type='text' id='tax_id' size='25' /></td>
	            </tr>
			    <tr>
			      <td><div align='right'>สถานะการใช้งาน</div></td>
			      <td>
			      <select name='active' id='active'>
			        <option value='Y'>Enable</option>
  					<option value='N'>Disible</option>
                  </select>                  </td>
	            </tr>
			    <tr>
			      <td><div align='right'>logo</div></td>
			      <td><input name='logo' type='file' id="logo" size='10' /></td>
	            </tr>
			    <tr>
			      <td>&nbsp;</td>
			      <td><a href='#' onclick="insertcompany('formupdatcompany')"  class=article>บันทึก</a></td>
	            </tr>
			  </table>
			</div>
			</fieldset>
</form>
	<?php echo $this->com_company_list;?>

	</div>
</div>
</div>



</body>
</html>


