<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Google Map API 3 - 01</title>
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.4/themes/gray/easyui.css"/>
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.4/themes/icon.css"/>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.4/jquery-1.6.min.js"></script>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.4/jquery.easyui.min.js"></script>
<script type="text/javascript">
var geocoder; 
var map; 
var my_Marker; 
var GGM; 
function initialize() { 
	GGM=new Object(google.maps); 
	geocoder = new GGM.Geocoder(); 
	var my_Latlng  = new GGM.LatLng(13.760105416539924,100.5471068774633);
	var my_mapTypeId=GGM.MapTypeId.ROADMAP;
	var my_DivObj=$("#map_canvas")[0];
	var myOptions = {
		zoom: 13, 
		center: my_Latlng , 
		mapTypeId:my_mapTypeId 
	};
	map = new GGM.Map(my_DivObj,myOptions); 
	my_Marker = new GGM.Marker({ 
		position: my_Latlng,  
		map: map, 
		draggable:true,
		title:"คลิกลากเพื่อหาตำแหน่งจุดที่ต้องการ!" 
	});
	GGM.event.addListener(my_Marker, 'dragend', function() {
		var my_Point = my_Marker.getPosition();  
        map.panTo(my_Point); 	
        $("#lat_value").val(my_Point.lat());  
        $("#lon_value").val(my_Point.lng()); 
        $("#zoom_value").val(map.getZoom());  	
	});		
	GGM.event.addListener(map, 'zoom_changed', function() {
		$("#zoom_value").val(map.getZoom());   
	});
}
$(function(){
	var searchPlace=function(){ 
		var AddressSearch=$("#namePlace").val();
		if(geocoder){ 
			geocoder.geocode({
				 address: AddressSearch 
			},function(results, status){ 
      			if(status == GGM.GeocoderStatus.OK) { 
					var my_Point=results[0].geometry.location; 
					map.setCenter(my_Point);
					my_Marker.setMap(map); 				
					my_Marker.setPosition(my_Point); 
					$("#lat_value").val(my_Point.lat());  
					$("#lon_value").val(my_Point.lng());  
					$("#zoom_value").val(map.getZoom());  							
				}else{
					alert("Geocode was not successful for the following reason: " + status);
					$("#namePlace").val("");
				 }
			});
		}		
	}
	$("#SearchPlace").click(function(){ 
		searchPlace();	
	});
	$("#namePlace").keyup(function(event){
		if(event.keyCode==13){	
			searchPlace();		
		}		
	});

});
$(function(){
	$("<script/>", {
	  "type": "text/javascript",
	  src: "http://maps.google.com/maps/api/js?v=3.2&sensor=false&language=th&callback=initialize"
	}).appendTo("body");	
});
</script>  
<style type="text/css">
#map_canvas { 
	width:550px;
	height:350px;
	margin:auto;
	margin-top:50px;
}
</style>
</head>
<body>
  <div id="map_canvas"></div>
 <div id="showDD" style="margin:auto;padding-top:5px;width:550px;">
Search Place 
  <input name="namePlace" type="text" id="namePlace" size="40" />
  <input type="button" name="SearchPlace" id="SearchPlace" value="Search" />
  <hr />
  <form id="form_get_detailMap" name="form_get_detailMap" method="post" action="">    Latitude  
    <input name="lat_value" type="text" id="lat_value" value="0" size="17" />  
    Longitude  
    <input name="lon_value" type="text" id="lon_value" value="0" size="17" />  
  Zoom  
  <input name="zoom_value" type="text" id="zoom_value" value="0" size="5" />  
  <input type="submit" name="button" id="button" value="บันทึก" />  
  </form>  
</div> 


</body>
</html>