<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>Slablet</title>
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

<link rel="stylesheet" href="/pos/plugin/fellowshiptech/assets/stylesheets/master.css" />
<!--[if IE 8]>
<link rel="stylesheet" href="assets/stylesheets/ie8.css" />
<![endif]-->
<!--[if !IE]><!-->
<script src="/pos/plugin/fellowshiptech/assets/javascripts/iscroll.js"></script>
<!--<![endif]-->
<script src="/pos/plugin/fellowshiptech/assets/javascripts/jquery.js"></script>
<script src="/pos/plugin/fellowshiptech/assets/javascripts/master.js"></script>

<link rel="stylesheet" href="/pos/plugin/touch/codebase/touchui.css" type="text/css" media="screen" charset="utf-8">
<script src="/pos/plugin/touch/codebase/touchui.js" type="text/javascript" charset="utf-8"></script>


<script src="/pos/js/flexigrid.js"></script>
<link type="text/css" rel="stylesheet" media="screen" href="/pos/css/flexigrid/flexigrid.css" />	
<script src="/pos/js/groupshop/groupshop.js"></script>
<link rel='stylesheet' type='text/css' href='/stock/css/style.css'>


<link rel="stylesheet" href="/pos/plugin/ipad/style/grid.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/pos/plugin/ipad/style/main.css" type="text/css" media="screen"/>     
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.4/themes/gray/easyui.css"/>
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.4/themes/icon.css"/>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.4/jquery-1.6.min.js"></script>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.4/jquery.easyui.min.js"></script>    
<script type="text/javascript" src="/pos/plugin/ipad/js/cookies.js"></script>
<link rel='stylesheet' type='text/css' href='/stock/css/style.css'>
        

</head>
<body>
<div id="main" class="abs">
	<div class="abs header_upper chrome_dark">
		Group Shop 
	</div>
	<div id="main_content" class="abs">
		<div id="main_content_inner">
			<h1>จัดกลุ่มสาขา
			</h1><hr />
				<div class="easyui-layout" style="width:700px;height:400px;">
					<div region="west" split="true" title="West" style="width:100px;"></div>
					<div region="center" title="Main Title" style="background:#fafafa;"></div>
					<div region="south" split="true" style="height:50px;background:#fafafa;"></div>
					<div region="east" icon="icon-reload" title="East" split="true" style="width:180px;"></div>
				</div>
		</div>
	</div>
	<div class="abs footer_lower chrome_dark">

	</div>
</div>


</body>
</html>