<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100%;width:100%; }
</style>
   	<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.5/jquery-1.7.1.min.js"></script>
  	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>

    <script type="text/javascript">
    $(document).ready(function(){
        var myLatlng = new google.maps.LatLng(13.77436,100.53458);
        var myOptions = {
          zoom: 8,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
            var map = new google.maps.Map(document.getElementById("map"),    myOptions);
            get_location();
        });


        function get_location() {
          navigator.geolocation.getCurrentPosition(show_map);
        }

        function show_map(position){
          var latitude = position.coords.latitude;
          var longitude = position.coords.longitude;

              var myLatlng = new google.maps.LatLng(latitude,longitude);
              var myOptions = {
                zoom: 4,
                center: myLatlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
              }
             var map = new google.maps.Map(document.getElementById("map"), myOptions);

             var marker = new google.maps.Marker({
                  position: myLatlng,
                  title:"Hello World!"
              });

              // To add the marker to the map, call setMap();
              marker.setMap(map);

        }
    </script>

</head>
<body>
  <div id="map" style="width:100%; height:100%"></div>
</body>
</html>
