<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<head>
    <title>Ipad simulator</title>
    <meta name="description" content="This is a jquery iPad simulator, this is only an experiment o what can be done with javascript in ast browsers">
    <meta name="keywords" content="Ipad, ipad simulator, apple ipad, alexw.me, altryne, alex wolkov, ipad javascript simulator">
    <meta http-equiv="Content-Type" content="text/html; charset=tis-620">
    
    <link rel="stylesheet" href="/pos/plugin/ipad/style/grid.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="/pos/plugin/ipad/style/main.css" type="text/css" media="screen"/>
    <link rel="stylesheet" href="/pos/plugin/ipad/style/notes.css" type="text/css" media="screen"/>
    <script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.5/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="/pos/plugin/ipad/js/plugins.js"></script>
    <script type="text/javascript" src="/pos/plugin/ipad/js/notes.js"></script>
    
</head>
<body>
    <div id="notes_container">
        <div id="left_side">
            <div id="search">
                <div id="counter">
                    <span id="number">0</span> Notes
                </div>
                <div id="search_cont">
                    <input type="search" id="text" placeholder="search"/>
                </div>
            </div>
            <div id="notes_list_cont">
                <ul id="notes_list">

                </ul>
            </div>
            <div id="pocket"></div>
        </div>
        <div id="right_side">
            <div id="header">
                <span id="main_title"></span>
                <div id="add_btn">+</div>
            </div>
            <div id="note_wrap">
                <time id="relative_date" class="timeago">Today</time>
                <time id="date_time">Sep 13, 2010 11:42 AM</time>
                <div id="note">
                    <textarea id="note_area"></textarea>
                </div>
            </div>
            <div id="navigation">
                <div id="prev"><-</div>
                <div id="send">mail</div>
                <div id="remove_btn" class="enabled">del</div>
                <div id="next">-></div>
            </div>
        </div>
    </div>

<!--    <script>-->
<!--   var _gaq = [['_setAccount', 'UA-7437527-1'], ['_trackPageview']];-->
<!--   (function(d, t) {-->
<!--    var g = d.createElement(t),-->
<!--        s = d.getElementsByTagName(t)[0];-->
<!--    g.async = true;-->
<!--    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';-->
<!--    s.parentNode.insertBefore(g, s);-->
<!--   })(document, 'script');-->
<!--  </script>-->
</body>
</html>