<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<title>Permission</title>
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.5/themes/gray/easyui.css"/>
<link rel="stylesheet" type="text/css" href="/pos/plugin/jquery-easyui-1.2.5/themes/icon.css"/>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.5/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.5/jquery.easyui.min.js"></script>
<script src="/pos/js/flexigrid.js"></script>
<link type="text/css" rel="stylesheet" media="screen" href="/pos/css/flexigrid/flexigrid.css" />	
<script type="text/javascript" src="/pos/js/permission/permission.js"></script>	
<script type="text/javascript" src="/pos/js/ajaxfileupload.js"></script>
<link rel='stylesheet' type='text/css' href='/pos/css/style.css'>

<script type="text/javascript" src="/pos/plugin/jquery.hotkeys/jquery.hotkeys.js"></script>

</head>
<body class="easyui-layout"  style="width:100%;height:100%;">
<div region="west" split="true" title="เมนูระบบ" style="width:300px;">
		<ul id="treesysmenu"></ul>
</div>
<div region="center" title="สิทธิ์การเข้าถึงเมนู" style="background:#fafafa;width:300px;" >
	<ul id="treepermission"></ul>
	<?php include 'permissionform.phtml';?>		
</div>
<div region="east"  title=" กลุ่มผูใช้งานระบบ " split="true" style="width:300px;" >
	<ul id="treeusergroup"></ul>
</div>
</body>
</html>