<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>Product</title>

<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

<link rel="stylesheet" href="/pos/plugin/fellowshiptech/assets/stylesheets/master.css" />
<!--[if IE 8]>
<link rel="stylesheet" href="assets/stylesheets/ie8.css" />
<![endif]-->
<!--[if !IE]><!-->
<script src="/pos/plugin/fellowshiptech/assets/javascripts/iscroll.js"></script>
<!--<![endif]-->
<script src="/pos/plugin/fellowshiptech/assets/javascripts/jquery.js"></script>
<script src="/pos/plugin/fellowshiptech/assets/javascripts/master.js"></script>

<link rel="stylesheet" href="/pos/css/black-tie/jquery-ui-1.8.10.custom.css" />
<script src="/pos/js/jquery-ui-1.8.18.custom.min.js"></script>

<script src="/pos/js/flexigrid.js"></script>
<link type="text/css" rel="stylesheet" media="screen" href="/pos/css/flexigrid/flexigrid.css" />	

<script src="/pos/js/product/product.js"></script>



</head>
<body>
<div  style='display:none' id='dialog_productdetail'></div>
<div id="main" class="abs">
	<div class="abs header_upper chrome_dark">
		Product
	</div>
	<div id="main_content" class="abs">
		<div id="main_content_inner">
			<form action="/pos/product/productprofile" method="post" enctype="multipart/form-data" name="sform" id="sform">
			<table id='fixgrids'></table>
			</form>
		</div>
	</div>
	
</div>


</body>
</html>