<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>Ipad simulator</title>
       <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        
        <link rel="stylesheet" href="/pos/plugin/ipad/style/grid.css" type="text/css" media="screen"/>
        <link rel="stylesheet" href="/pos/plugin/ipad/style/main.css" type="text/css" media="screen"/>
        <script type="text/javascript" src="/pos/plugin/jquery-easyui-1.2.5/jquery-1.7.1.min.js"></script>
		
        <script type="text/javascript" src="/pos/plugin/ipad/js/cookies.js"></script>
        <script type="text/javascript"> </script>
    </head>
    <body>
    <div id="safari">
        <div id="navbar">
            <div id="title"> Untitled </div>
            <div id="back" class="icon">&lt;</div>
            <div id="forward" class="icon">&gt;</div>
            <div id="tabs" class="icon">0</div>
            <div id="bookmarks" class="icon">book</div>
            <div id="add" class="icon">+</div>
            <div id="urlCont">
                <form id="urlgo">
                    <input type="text" id="url" value=""/>
                </form>
                <div id="refresh">R</div>
                <div id="stop">S</div>
            </div>
            <div id="searchCont">
                <form id="searchgo">
                    <input type="text" id="search"/>
                </form>
            </div>
        </div>
        <div id="tabs_cont">
            <div id="browser_overlay">

                <iframe src="" width="884" height="591" scrolling="no"></iframe>
            </div>
            <div id="tab0" class="tab">
                <div class="iframe_overlay"></div>
                <iframe src="" width="884" height="591" scrolling="no"></iframe>
                <div class="tabtitle">Untitled</div>
            </div>
            <div id="tab1" class="tab">
                <div class="iframe_overlay"></div>
                <iframe src="" width="884" height="591" scrolling="no"></iframe>
                <div class="tabtitle">Untitled</div>
            </div>
            <div id="tab2" class="tab">
                <div class="iframe_overlay"></div>
                <iframe src="" width="884" height="591" scrolling="no"></iframe>
                <div class="tabtitle">Untitled</div>
            </div>
            <div id="tab3" class="tab">
                <div class="iframe_overlay"></div>
                <iframe src="" width="884" height="591" scrolling="no"></iframe>
                <div class="tabtitle">Untitled</div>
            </div>
            <div id="tab4" class="tab">
                <div class="iframe_overlay"></div>
                <iframe src="" width="884" height="591" scrolling="no"></iframe>
                <div class="tabtitle">Untitled</div>
            </div>
            <div id="newtab" class="tab100">
                <div class="iframe_overlay"></div>
                <div class="tabtitle">New Page</div>
            </div>
        </div>

    </div>
</body>
</html>