
<style>
.flexigrid div.fbutton .view_product {
	background: url(/stock/img/view_choose.png) no-repeat center left;
}

.flexigrid div.fbutton .delete {
	background: url(/stock/img/delete.png) no-repeat center left;
}

</style>
<?php
$doc_no=$this->doc_no;
//$sum_inv=$this->sum_inv;
$sum=$this->sum_inv;
$chkdocno=$this->chkdocno;
//echo $sum[0]['quantity'];
//print_r($sum_inv);
/*if(!empty($sum[0]['quantity'])){
	$sumall=($sum[0]['price']*$sum[0]['quantity']);
}else{
	$sumall=null;
}*/
?>
<center>
<table width="100%" bgcolor="#d1d1d1">
	<tr>
		<td><table id="flex1" style="display:none"></table></td>
	</tr>
	<tr>
		<td>
			<table width="100%" border="0" cellpadding="2" cellspacing="2" bgcolor="#e9f2f8" align="center">
				<tr>
					<td width="5%" height="30"></td>
					<td width="10%"></td>
					<td width="21%"></td>
					<td width="10%" align="right"><b>Total</b></td>
					<td width="10%" align="center"><input type="text" value="<?php echo number_format($sum[0]['quantity'], 0, '.', ',');?>" size="10" class="NFText" disabled="disabled"></td>
					<td width="10%" align="center"><input type="text" value="<?php echo number_format($sum[0]['price'], 2, '.', ',');?>" size="10" class="NFText" disabled="disabled"></td>
					<td width="10%"></td>
					<td></td>
				</tr>
				<tr>
					<td width="5%" height="30"></td>
					<td width="10%"></td>
					<td width="21%"></td>
					<td width="10%" align="right"></td>
					<td width="10%" colspan="2">
						<table width="100%" border="0" cellpadding="2" cellspacing="2">
							<tr>
								<td align="right"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return tempor2diaryor();"><span class="ui-icon ui-icon-disk"></span>Save  (F3)</a></td>
								<td align="left"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return order_cancel();"><span class="ui-icon ui-icon-cancel"></span>Cancle (F4)</a></td>
							</tr>
						</table>
					</td>
					<td></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<input type="hidden" name="doc_no" id="doc_no" value="<?php echo $doc_no;?>">
<input type=hidden name="chk" id="chk" value="<?php echo $chkdocno;?>">
</center>
<script type="text/javascript">
var pWidth=(screen.width-(screen.width*(20/100)))-10;
var pWidth=(screen.width-(screen.width*(2/100)))-10;
var pWidth=(screen.width-(screen.width*(3/100)))-10;
var txt="Order Items";
$("#flex1").flexigrid({
	url: '/order/order/getdataproductorderfix',
	method:'POST',
	dataType: 'json',
	colModel : [
		{display: '#', name : 'seq', width : 40, sortable : true, align: 'center'},
		{display: 'Product id', name : 'product_id', width : 95, sortable : true, align: 'center'},
		{display: 'Product Name', name : 'name_product', width : 190, sortable : false, align: 'center'},
		{display: 'Price', name : 'price', width : 95, sortable : false, align: 'center'},
		{display: 'Suggested Qty', name : 'suggest_qty', width : 95, sortable : false, align: 'center'},
		{display: 'Order Qty <br> (Double click to edit) <br> Max = Suggested Qty', name : 'order_qty', width : 130, sortable : false, align: 'center',process:edit},
		{display: 'Amount', name : 'amount', width : 95, sortable : false, align: 'center'},
		{display: 'Onhand', name : 'onhand', width : 95, sortable : false, align: 'center'},
		{display: 'Fix', name : 'ret_short_qty', width : 90, sortable : false, align: 'center'},
		],
		buttons : [
      	{name: 'Delete', bclass: 'delete', onpress : productaction},
		  {separator: true},
		// {name: 'Edit', bclass: 'edit', onpress : productaction},
		//   {separator: true}
      	],
		searchitems : [
		{display: 'Product id', name : 'procuct_id'}
		],
	sortname: "seq",
	sortorder: "asc",
	usepager: true,
	title: txt,
	useRp: true,
	rp: 30,
	showTableToggleBtn: true,
	onSubmit: addFormData,
	height: 300
});

function productaction(com, grid) {
	var doc_no=$("#doc_no").val();
	if($('.trSelected',grid).length>0){
		var items = $('.trSelected',grid);
		var itemlist ='';
		for(i=0;i<items.length;i++){
			itemlist+= items[i].id.substr(3)+",";
			//itemlist= items[i].id.substr(3);
		}
	}
	if (com == 'Delete') {
		if(itemlist==undefined){
			jAlert('you did not select any items!', 'Alert');;
		}else{
			jConfirm('Confirm to Delete items?', 'Alert', function(r) {
				if(r==false){
					return false;
				}else{
					$.ajax({type: "POST",url: "/order/order/deletetmplist",data:{seq:itemlist},success:
						function(data){
							if(data=="y"){
								vieworderfix("s");
							}
						}
					});
				}
			});
		} 
	}
	// else if (com == 'Edit') {
	// 	if(items.length>0) {
	// 		if( items.length>1) {
	// 			jAlert('You can select only 1 item before edit!', 'Alert');;
	// 		} else {
	// 			// var id  = items[0].id.substr(3);
	// 			// $.fancybox({'href'	: 'edit_form.php?id='+id});
	// 		}
	// 	} else {
	// 		alert('กรุณาเลือกข้อมูลที่ต้องการแก้ไข!!');
	// 	}
	// }
}

function edit(celDiv, id){
    $( celDiv ).click( function() {
 var idTd = $(celDiv).parent().parent().children()[1];
 $(celDiv).editInPlace({
    url: "/order/order/updateorder",
	params: "address="+$(idTd.children).html(),
	params: "seq="+id,
    error:function(obj){
  alert(JSON.stringify(obj));
    },
    success:function(obj){
			  //$("#flex1").flexReload();
			 //window.location.reload();
								 vieworderfix("s");
								 
  var str = m[JSON.parse(obj).status+""][window.curLanguage];
  alert(str);
    }
 });
	});
}

function addFormData(){
	var dt = $('#sform').serializeArray();
	$("#flex1").flexOptions({params: dt});
	return true;
}
	
$('#sform').submit(function (){
	$('#flex1').flexOptions({newp: 1}).flexReload();
	return false;
});
</script>