<?php 
$date=$this->date;
$data=$this->data;
$amount_default="0.00";
if(empty($data[0]['month_amount'])){$month_amount= $amount_default;}else{$month_amount= number_format($data[0]['month_amount'], 2, '.', ',');}
if(empty($data[0]['month_order'])){$month_order= $amount_default;}else{$month_order= number_format($data[0]['month_order'], 2, '.', ',');}
if(empty($data[0]['balance_amount'])){$balance_amount= $amount_default;}else{$balance_amount= number_format($data[0]['balance_amount'], 2, '.', ',');}
?>
<script>
$(document).ready( function() {
	$("#doc_remark").focus();
});
function process(event,p){
	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
	keyCode = event.which; // Firefox    
	if (keyCode == 13) {
		if(p=="check_doc_remark"){
			$("#product_id").focus();
		}
		if(p=="check_product"){
			check_product();
		}
		if(p=="insert_tdiary_or"){
			insert_tdiary_or();
		}
	}
}
jQuery(document).bind('keydown', 'f7',
function (evt){
	search_type_product();
});

jQuery(document).bind('keydown', 'f8',
function (evt){
	search_product();
});

jQuery(document).bind('keydown', 'f3',
function (evt){
	tempor2diaryor();
});

jQuery(document).bind('keydown', 'f4',
function (evt){
	order_cancel();
});

jQuery(document).bind('keydown', 'f2',
function (evt){
	select_status_no();
});
</script>
<div id="dialog_type_product" title="Pruduct Order Type"></div>
<div id="dialog_product" title="Product"></div>
<form id="frm_order">
<table width="100%" border="0" cellpadding="0" cellspacing="3" background="/order/img/bg_header.gif">
  <tr>
  	<td colspan="6" height="5"></td>
  </tr>
  <tr>
    <td align="right" class="servBodL_right"><b>Quata Amt. : </b></td>
    <td width="5" colspan="4"><input type="text" name="month_amount" id="month_amount" size="13" value="<?php echo $month_amount;?>" class="NFText_hidden" disabled="disabled" onkeypress=""></td>
  </tr>
  <tr>
    <td width="15%" align="right" class="servBodL_right"><b>Order Amt. : </b></td>
    <td width="5"><input type="text" name="month_order" id="month_order" size="13" value="<?php echo $month_order;?>" class="NFText_hidden" disabled="disabled" onkeypress=""></td>
    <td width="2%">&nbsp;</td>
    <td width="10%" align="right" class="servBodL_right"><b>Balance Amt. : </b></td>
    <td width="3%"><input type="text" name="balance_amount" id="balance_amount" value="<?php echo $balance_amount;?>" size="13" disabled="disabled" class="NFText_hidden" onkeypress=""></td>
 	<td>&nbsp;</td> 
  </tr>
  <tr>
    <td width="15%" align="right" class="servBodL_right"><b>Product Order Type : </b></td>
    <td width="5"><input type="text" name="type_dec" id="type_dec" size="13" value="Normal Product" class="NFText_hidden" disabled="disabled" onkeypress=""></td>
    <td width="2%"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return search_type_product();"><span class="ui-icon ui-icon-search"></span> (F7)</a></td>
    <td width="10%" align="right" class="servBodL_right"><b>Date : </b></td>
    <td width="3%"><input type="text" name="date" id="date" value="<?php echo $date;?>" size="13" disabled="disabled" class="NFText_hidden" onkeypress=""></td>
 	<td>&nbsp;</td> 
  </tr>
  <tr>
    <td align="right" class="servBodL_right"><b>Note :</b></td>
    <td colspan="5"><input type="text" name="doc_remark" id="doc_remark" size="50" onkeypress="return process(event,'check_doc_remark')" class="NFText" /></td>
  </tr>
  <tr>
    <td width="15%" align="right" class="servBodL_right"><b>Product ID : </b></td>
    <td width="5"><input type="text" name="product_id" id="product_id" size="13" onkeypress="return process(event,'check_product')" class="NFText" onkeypress=""></td>
    <td width="2%"><a class="fg-button ui-state-default fg-button-icon-left ui-corner-all" onClick="return search_product();"><span class="ui-icon ui-icon-search"></span> (F8)</a></td>
    <td width="10%" align="right" class="servBodL_right"><b>Quantity : </b></td>
    <td width="3%" colspan="2"><input type="text" name="qty" id="qty" size="13" class="NFText" onkeypress="return process(event,'insert_tdiary_or')"></td>
  </tr>
	<tr class="ddisplay">
		<td width="15%" align="right" class="servBodL_right"><b>Last Order : </b></td>
		<td width="5"><input type="text" name="orderdate" id="orderdate" size="11" class="NFText" readonly>/</td>
		<td width="2%"><input type="text" name="lastqty" id="lastqty" size="8" class="NFText" readonly></td>
		<td width="10%" align="right" class="servBodL_right"><b>KM : </b></td>
		<td width="3%" colspan="2"><input type="text" name="km" id="km" size="13" class="NFText" readonly></td>
	</tr>

	<tr class="ddisplay">
		<td width="15%" align="right" class="servBodL_right" ><b>BALANCE : </b></td>
		<td width="5"><input type="text" name="balance" id="balance" size="7" class="NFText" readonly><b>FIX : </b></td>
		<td width="2%"><input type="text" name="fix" id="fix" size="7" class="NFText" readonly></td>
		<td width="10%" align="right" class="servBodL_right" readonly><b>AVG : </b></td>
		<td width="3%" colspan="2"><input type="text" name="avg" id="avg" size="13" class="NFText" readonly></td>
	</tr>
  <tr>
	 <td colspan="6" height="5"></td>
  </tr>
</table>
<input type="hidden" name="doc_tp" id="doc_tp" value="OR"></input>
<input type="hidden" name="status_no" id="status_no" value="70"></input>
</form>
<table width="100%">
	<tr>
		<td><div id="viewproductorder"></div></td>
	</tr>
</table>