<?php 
$date=$this->date;
$data=$this->data;
// $amount_default="0.00";
// $stock_default="0";
// $product_id_default="0";
// $i=0;
// foreach($data as $key){
// 	if(empty($key['product_id'])){$product_id= $product_id_default;}else{$product_id= $key['product_id'];}
// 	if(empty($key['onhand'])){$onhand= $stock_default;}else{$onhand= number_format($key['onhand'], 0, '.', ',');}
// 	if(empty($key['quantity_normal'])){$quantity_normal= $stock_default;}else{$quantity_normal= number_format($key['quantity_normal'], 0, '.', ',');}
// 	$suggested_qty= (number_format($key['quantity_normal'], 0, '.', ','))-(number_format($key['onhand'], 0, '.', ','));
// 	$order_qty= $suggested_qty;
// 	 echo "#$i <br>";
// 	 $i++;
// 	 echo " product_id = $product_id"; 
// 	 echo "<br>";
// 	 echo " Suggestes Qty = $suggested_qty"; 
// 	 echo "<br>";
// 	 echo " Order Qty = $order_qty";
// 	 echo "<br>";
// 	 echo " Onhand = $onhand"; 
// 	 echo "<br>";
// 	 echo "Fix =$quantity_normal"; 
// 	 echo "<br>";
// 	 $key['suggested_qty'] = $suggested_qty; // add new index[] to array
// 	//  echo $key['suggested_qty']; //echo new index from array

// 	  if($key['suggested_qty'] > 0){
// 		echo " Will transfer to trn_tdiary2_or <br><br>";
// 	  }else{
// 		echo " Can't transfer to trn_tdiary2_or !! <br><br>";
// 	  };
// }
?>
<!--script>
// $(document).ready( function() {
// 	$("#doc_remark").focus();
// });
// function process(event,p){
// 	var keyCode = event.keyCode ? event.keyCode : event.which ? event.which : event.charCode;
// 	keyCode = event.which; // Firefox    
// 	if (keyCode == 13) {
// 		if(p=="check_doc_remark"){
// 			$("#product_id").focus();
// 		}
// 		if(p=="check_product"){
// 			check_product();
// 		}
// 		if(p=="insert_tdiary_or"){
// 			insert_tdiary_or();
// 		}
// 	}
// }
// jQuery(document).bind('keydown', 'f3',
// function (evt){
// 	process_to_order();
// });

// jQuery(document).bind('keydown', 'f8',
// function (evt){
// 	search_product();
// });

// jQuery(document).bind('keydown', 'f3',
// function (evt){
// 	tempor2diaryor();
// });

// jQuery(document).bind('keydown', 'f4',
// function (evt){
// 	order_cancel();
// });

// jQuery(document).bind('keydown', 'f2',
// function (evt){
// 	select_status_no();
// });
//<--/script>
// <div id="dialog_type_product" title="ประเภทสั่งสินค้า"></div>
// <div id="dialog_product" title="สินค้า"></div>
// <form id="frm_order">
// <table width="100%" border="0" cellpadding="0" cellspacing="3" background="/order/img/bg_header.gif">
//   <tr>
//   	<td colspan="6" height="5"></td>
//   </tr>
//   <tr>
	


	
//   </tr>
//   <tr>
// 	 <td colspan="6" height="5"></td>
//   </tr>
// </table>
// <input type="hidden" name="doc_tp" id="doc_tp" value="OR"></input>
// <input type="hidden" name="status_no" id="status_no" value="70"></input>
// </form>