     <style type="text/css">  
			.tableNavCnTP
				{
					width:100%;
					background:#333;
				}
			.tableNavCnTP ul
				{
					float:right;
					width:100%;
					margin:0;
					padding:0;
					border:1px solid #C9C9C9;
				}
         
          .tableNavCnTP ul li{
          		cursor:pointer;
          		line-height:40px;
				font-family:"PSLKittithadaBold","Garuda","Tahoma", "Geneva", "Arial", sans-serif;
				font-weight: normal;
				font-size:20px;/*16*/
				text-decoration:none;
				color:#303030;
				padding-left:1em;					
				border-bottom:1px solid  #78777C;
				text-shadow: 0px 1px 0px #dddddd;				
				vertical-align: middle;
				white-space:nowrap;
				background:#B2B2B8;
				background:  -moz-linear-gradient(     #D4D7E0,     #B0B0B0);;
				background: -webkit-gradient(linear, left top, left bottom, color-stop(0,      #D4D7E0), color-stop(1, #B0B0B0));
				-moz-user-select:none;
				-moz-user-select:-moz-none;/*latest ff*/
				-webkit-user-select:none;
          }
          ul li.active {
            cursor:pointer;
					line-height: 40px;
					font-family:"PSLKittithadaBold", "Garuda","Tahoma", "Geneva", "Arial", sans-serif;
					font-weight: normal;
					font-size:20px;/*16*/
					text-decoration:none;
					color:#ffffff;/*#303030*/
					padding-left:1em;					
					border-bottom:1px solid  #000;/*78777C*/
					text-shadow: 0px 1px 0px #dddddd;				
					vertical-align: middle;
					white-space:nowrap;
					background:#B2B2B8;/*#B2B2B8*/
					background:  -moz-linear-gradient(#9DDCCF,#265541);/*#D4D7E0, #B0B0B0||#777777,#444444*/
					background: -webkit-gradient(linear, left top, left bottom, color-stop(0, #D4D7E0), color-stop(1, #B0B0B0));
					-moz-user-select:none;
					-moz-user-select:-moz-none;/*latest ff*/
					-webkit-user-select:none;
          }          
          ul li.nokeyboard {
            color: #999;
            background:#0000ff;
          }
        </style>
    <div class="tableNavCnTP" >
	        <ul>
	        <?php 
	        	if(!empty($this->arr_cntp)){	
		        	$i=1;
		        	$str_cn="";
		        	foreach($this->arr_cntp as $data){	        	
		        		$rows_product=json_encode($data);
		  				$id_tmp="n_".$i;		  			
			  			echo "<li id='$id_tmp' name='$id_tmp' class='btn_sel' idcntp='".$rows_product."'>".$data['cn_tp']."&nbsp;&nbsp;".$data['description']."</li>";  
			  			$i++;
		  			}
	        	}else{
	        		echo "<li id='n_1' name='n_1' class='btn_sel' idproduct='nodata'>ไม่พบข้อมูล</li>";
	        	}
	        ?>
	        </ul>
     </div>