<?php 
$data=$this->data;
?>
<form name="frm_inv" id="frm_inv">
<table width="100%" border="0" cellpadding="2" cellspacing="2">
  <tr>
  	<td height="25" width="3%" background="/order/img/bg_header_blue.gif" align="center"><b>#</b></td>
    <td height="25" width="25%" background="/order/img/bg_header_blue.gif" align="center"><b>สถานะเอกสาร</b></td>
    <td background="/order/img/bg_header_blue.gif" align="center"><b>รายละเอียด</b></td>
  </tr>
 <?php 
 $i=1;
 foreach($data as $val){
 	if($i%2){$color="#eaebeb";}else{$color="#f2f3f3";}
	 ?>
	  <tr bgcolor="<?php echo $color;?>">
	  	<td align="center" height="20"><input type="radio" name="status_no" id="status_no" value="<?php echo $val['status_no'];?>:<?php echo $val['description'];?>" <?php if($i==1){echo "checked='checked'";}?>></td>
	    <td align="center"><?php if(!empty($val['status_no'])){echo $val['status_no'];}?></td>
	    <td align="left"><?php if(!empty($val['description'])){echo $val['description'];}?></td>
	  </tr>
	 <?php 
 	$i++;
 }
 ?>
</table>
</form>