<html>
<head>
   <script type="text/javascript">
        
        $(function() {
		var dates = $( "#start").datepicker({
			dateFormat: 'yy-mm-dd',
			changeMonth: true,
                       // beforeShow: function(event,object) { alert ( "กรุณาเลือกวันแรกของเดือน" ); },
			onSelect: function( selectedDate ) {
				var option = this.id == "start_date" ? "minDate" : "maxDate",
					instance = $( this ).data( "datepicker" ),
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
                                
			}
		});
	});
</script>


                        
<style type="text/css">

body{
font-family:"Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif;
font-size:16px;
}
p, h1, form, button{border:0; margin:0; padding:0;}
.spacer{clear:both; height:1px;}
/* ----------- My Form ----------- */
.myform{
margin:0 auto;
width:400px;
padding:14px;
}

/* ----------- stylized ----------- */
#stylized{
border:solid 2px #74a782;
background:#c8e0df;
}
#stylized h1 {
font-size:16px;
font-weight:bold;
margin-bottom:8px;
}
#stylized p{
font-size:14px;
color:#666666;
margin-bottom:20px;
border-bottom:solid 1px #74a782;
padding-bottom:10px;
}
#stylized label{
display:block;
font-weight:bold;
text-align:right;
width:140px;
float:left;
}
#stylized .small{
color:#666666;
display:block;
font-size:12px;
font-weight:normal;
text-align:right;
width:140px;
}
#stylized input{
float:left;
font-size:16px;
padding:4px 2px;
border:solid 1px #74a782;
width:200px;
margin:2px 0 20px 10px;
}
#stylized select{
float:left;

padding:4px 2px;
border:solid 1px #74a782;
width:200px;
margin:2px 0 20px 10px;
}
#stylized button{
clear:both;
/*margin-left:150px;*/
float: right;
width:50px;
height:31px;
background:#666666 url(img/button.png) no-repeat;
text-align:center;
line-height:31px;
color:#FFFFFF;
font-size:14px;
font-weight:bold;
}

</style>

</head>

<body>
<div id="stylized" class="myform">
<form id="form" name="form" method="post" action="">
<h1>รายงานสินค้าแถมฟรี</h1>
<p></p>

<label>ป้อน รหัสสินค้าเริ่มต้น</label>
<input type="text" name="start_product" id="start_product" />

<label>ถึง</label>
<input type="text" name="end_product" id="end_product" />

<label>วันที่เริ่มต้น</label>
<input type="text" name="start_date" id="start" />

<label>ถึง</label>
<input type="text" name="end_date" id="end_date" />

<button type="button" id="opener">ตกลง</button>
 

<div class="spacer"></div>
</form>
</div>

    
<div id="dialog" title="รายงานสินค้าแถมฟรี"></div>    
    
</body>
</html>


<script type="text/javascript">

$(document).ready(function(){
 
    $("#opener").click(function(){       
      
        var opts_QstDetail={
                    autoOpen:false,
                    width:'50%',
                    height:'600',
                    modal:true,
                    resizeable:true,
                    position:'top',
                    showOpt: {direction:'up'},
                    closeOnEscape:true,
                    title:"",
                    open:function(){
                        $("#dialog").html("<span style='position: absolute;text-align: center;width: 100%; padding-top: 50px;'><img src='/report/img/ajax-loader.gif'> </span>");
                        $.ajax({
                            type:'post',
                            url:'/report/report/viewpremium',
                            cache:false,
                            data:{       
                                product1:$("#start_product").val(),
                                product2:$("#end_product").val(),
                                data1:$("#start").val(),
                                data2:$("#end_date").val(), 
                                now:Math.random()
                            },
                            success:function(data){
                                $("#dialog").html(data);
                            }//end success function
                        });//end ajax pos
                    }
            };
            $("#dialog").dialog("destroy");
            $("#dialog").dialog(opts_QstDetail);
            $("#dialog").dialog("open");
       
        
     
    });
   
});
	
</script>


<!--<script type="text/javascript">  Confirm Dialog

$(document).ready(function(){
    $("#confirm").click(function() {
                jConfirm('พิมพ์แบบสรุปหรือไม่', 'Confirmation Dialog', function(r) {
               
           if (+r == false){
               var opts_QstDetail={
                    autoOpen:false,
                    width:'60%',
                    height:'600',
                    modal:true,
                    resizeable:true,
                    position:'top',
                    showOpt: {direction:'up'},
                    closeOnEscape:true,
                    title:"",
                    open:function(){
                        $("#dialog").html("");
                        $.ajax({
                            type:'post',
                            url:'/report/report/viewstock',
                            cache:false,
                            data:{       
                                product1:$("#start_product").val(),
                                product2:$("#end_product").val(),
                                data1:$("#start").val(),
                                data2:$("#end_date").val(),                            
                                now:Math.random()
                            },
                            success:function(data){
                                $("#dialog").html(data);
                            }//end success function
                        });//end ajax pos
                    }
            };
            $("#dialog").dialog("destroy");
            $("#dialog").dialog(opts_QstDetail);
            $("#dialog").dialog("open");
       
           }else{
               // return false;
                         $.ajax({
                            type:'post',
                            url:'/report/report/printviewstock',
                            cache:false,
                            data:{       
                                product1:$("#start_product").val(),
                                product2:$("#end_product").val(),
                                data1:$("#start").val(),
                                data2:$("#end_date").val(),                            
                                now:Math.random()
                            },
                            success:function(data){
                                $("#dialog").html(data);
                            }//end success function
                        });//end ajax pos   
                        jAlert('print');
           }        
               
           });
            });
    
    });
   

	
</script>-->

