<?php
//@header("Content-type:text/html; charset=utf=8");
include(FPDF_PATH."/fpdf.php");
$pdf=new FPDF('P','mm','a23');
$pdf->SetThaiFont();
$pdf->SetMargins( 0,2,0 );  // ซ้าย , บน , ขวา

$pdf->AddPage();
$pdf->SetFont('CordiaNew','',5);
//$pdf->Cell( 0  , 4 , iconv( 'UTF-8','cp874' ,'วันที่ออกเอกสาร '.$this->print_time ) , 0 , 1,'R' );

$pdf->Image('/var/www/pos/htdocs/report/img/logo/op/op-logo.gif',8 ,0,0);
$pdf->SetFont('CordiaNew','B',10);
//$title1=iconv('UTF-8','cp874',"รายงานสรุปยอดขาย");

$line="----------------------------------------------------------------------------------------------";

$pdf->Ln(7);
$pdf->Cell(0,3,iconv('UTF-8','cp874','รายงานสรุปยอดขาย'),0,0,'C');
$pdf->Ln(3);
$pdf->Cell(0,3,iconv('UTF-8','cp874',"ประจำวันที่  ".$this->s_date." - ".$this->e_date),0,1,'C');
$pdf->Ln(2);
$pdf->Cell( 40  , 3 , iconv( 'UTF-8','cp874' ,'วันที่พิมพ์เอกสาร '.$this->print_time ),0,0,'L');
$pdf->Cell( 28  , 3 , iconv( 'UTF-8','cp874' ,'เวลา '.$this->ptime ),0,0,'R');
$pdf->Ln(3);
$pdf->Cell(0,3,iconv('UTF-8','cp874','จุดขาย :' .$this->branch_id.' '.$this->branch_name ));
$pdf->Ln(3);

$pdf->SetFont('CordiaNew','',11);
$pdf->Cell(0,3,$line);
$pdf->Ln(4);

$a = 5;
$b = 8;
$c = 15;
$d = 25;
$e = 30;
$f = 40;

$pdf->Cell( $a  , 4 , iconv( 'UTF-8','cp874' , '#' ) , 0 , 0 );
$pdf->Cell( $b  , 4 , iconv( 'UTF-8','cp874' , 'รหัส' ) , 0 , 0 ,'R' );
$pdf->Cell( $c  , 4 , iconv( 'UTF-8','cp874' , 'รายละเอียด' ) , 0 , 1,'R' );
$pdf->Cell( $d  , 4 , iconv( 'UTF-8','cp874' , 'จำนวน' ) , 0 , 1,'R' );
$pdf->Cell( $e  , 4 , iconv( 'UTF-8','cp874' , 'จำนวนเงิน' ) , 0 , 1,'R' );
$pdf->Cell( $f  , 4 , iconv( 'UTF-8','cp874' , 'เงินสุทธิ' ) , 0 , 1,'R' );




$pdf->Ln(3);
$pdf->Cell(0,3,$line,0,1);
$pdf->Ln(3);

$pdf->Cell( 28  , 4 , iconv( 'UTF-8','cp874' , 'จำนวน EDC  =  ' ) , 0 , 0 );
$pdf->Ln(12);

$pdf->Cell( 28  , 4 , iconv( 'UTF-8','cp874' , 'ลายเซ็นต์พนักงานขาย  :  __________________________________' ) , 0 , 0 );

$pdf->Ln(20);
$pdf->Cell( 0  , 4 , iconv( 'UTF-8','cp874' , '.' ) , 0 , 0 );
//$pdf->Output();
$name='printsalesummary.pdf';
$output="/var/www/pos/htdocs/report/printreport/".$name;
//$pdf->Output($output,'F');
@chmod($output,0777); 
if(@file_exists($output)){
		 shell_exec("rm $output");
		@unlink($output);
	}
 
$pdf->Output($output,'F'); 
//shell_exec("lp -o media=Letter $output");
	

?>

<script type="text/javascript">
//self.close();
</script>
		
