<?php
//@header("Content-type:text/html; charset=utf=8");
include(FPDF_PATH."/fpdf.php");
$pdf=new FPDF('P','mm','letter');
$pdf->SetThaiFont();
$pdf->SetMargins( 0,10,0 );  // ซ้าย , บน , ขวา

$pdf->AddPage();


$pdf->Image('/var/www/pos/htdocs/report/img/logo/op/op-logo.gif',75,0,0);
$pdf->SetFont('CordiaNew','',15);
//$title1=iconv('UTF-8','cp874',"สรุปการชำระเงินจากลูกค้า");

$line="----------------------------------------------------------------------------------------------------------------------------------------------------------------------";

$pdf->Ln(3);
$pdf->Cell(0,7, 'สรุปการชำระเงินจากลูกค้า',0,1,'C');
//$pdf->Ln(7);
$pdf->Cell(0,7,"ประจำวันที่  ".$this->s_date." - ".$this->e_date,0,1,'C');
//$pdf->Ln(7);
$pdf->Cell( 40  , 7 ,'วันที่พิมพ์เอกสาร '.$this->print_time ,0,0,'L');
$pdf->Cell( 150  , 7 ,'เวลา '.$this->ptime,0,1,'R');
//$pdf->Ln(7);
$pdf->Cell(0,7,'จุดขาย : '.$this->branch_id.' '.$this->branch_name);
$pdf->Ln(7);

$pdf->Cell(0,3,$line);
$pdf->Ln(7);

$a = 80;
$b = 60;
$c = 50;
$d = 7;

$pdf->Cell( $a  , $d , 'จำนวนเงินทั้งสิ้น' , 0 , 0 );
$pdf->Cell( $b  , $d ,  0 , 0 ,'R' );
$pdf->Cell( $c  , $d , number_format($this->amount_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'ส่วนลด' , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->discount_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'บัตรเครดิต'  , 0 , 0 );
$pdf->Cell( $b  , $d ,  '' ) , 0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->credit_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'คูปอง เงินสด / voucher'  , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->netcashcoupon, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'เงินสด'  , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->cash_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( 50  , $d ,  '(40) เปลี่ยน ส/ค  ' , 0 , 0 );
$pdf->Cell( 30  , $d ,  '(G)  '.number_format($this->getgross_data) .','  , 0 , 0 );
$pdf->Cell( 60  , $d ,  number_format($this->getquan_data).' ,' , 0 , 0,'R'  );
$pdf->Cell( 50  , $d , '(N) '.number_format($this->getamt_data, 2, '.', ','.'  บาท' ) , 0 , 1,'R' );

$pdf->Cell( 50  , $d ,  '(41) คืนเงิน  ' , 0 , 0 );
$pdf->Cell( 30  , $d ,  '(G)  '.number_format($this->qbackgross_data) .','  , 0 , 0 );
$pdf->Cell( 60  , $d , number_format($this->qback_data).' ,' , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , '(N) '. number_format($this->qbackamt_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'หักลดหนี้ เครดิต'  , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->getcn_credit, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'หักลดหนี้ เงินสด'  , 0 , 0 );
$pdf->Cell( $b  , $d ,  0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->getcn_cash, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'บิลสินค้าขาด (19)'  , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->getbill_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'ยอดเงิน PAY IN'  , 0 , 0 );
$pdf->Cell( $b  , $d ,   0 , 0  );
$pdf->Cell( $c  , $d , number_format($this->payin, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

/*$pdf->Cell( 30  , 4 ,  'ยอดสุทธิ เครดิต' ) , 0 , 0 );
$pdf->Cell( 15  , 4 , iconv( 'UTF-8','cp874' , '' ) , 0 , 0  );
$pdf->Cell( 23  , 4 , iconv( 'UTF-8','cp874' ,number_format($this->credit_data, 2, '.', ',').'  บาท' ) , 0 , 1,'R' );*/

/*$pdf->Cell( 30  , 4 , iconv( 'UTF-8','cp874' , 'เงินสด' ) , 0 , 0 );
$pdf->Cell( 15  , 4 , iconv( 'UTF-8','cp874' , '' ) , 0 , 0  );
$pdf->Cell( 23  , 4 , iconv( 'UTF-8','cp874' ,number_format($this->cash_data, 2, '.', ',').'  บาท' ) , 0 , 1,'R' );*/

$pdf->Cell(0,3,$line);
$pdf->Ln(7);

$pdf->Cell( $a  , $d ,  'โอนสินค้าเข้า'  , 0 , 0 ); 
$pdf->Cell( $b  , $d ,  number_format($this->qincome_data).' ,' , 0 , 0 ,'R' );
$pdf->Cell( $c  , $d ,  number_format($this->aincome_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'โอนสินค้าออก'  , 0 , 0 );
$pdf->Cell( $b  , $d ,  number_format($this->qoutcome_data).' ,' , 0 , 0 ,'R' );
$pdf->Cell( $c  , $d ,  number_format($this->aoutcome_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'ปรับปรุงเข้า'  , 0 , 0 );
$pdf->Cell( $b  , $d ,  number_format($this->qchincome_data).' ,' , 0 , 0 ,'R' );
$pdf->Cell( $c  , $d ,  number_format($this->chincomeamt_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );

$pdf->Cell( $a  , $d ,  'ปรับปรุงออก'  , 0 , 0 );
$pdf->Cell( $b  , $d ,  number_format($this->qchoutcome_data).' ,' , 0 , 0 ,'R' );
$pdf->Cell( $c  , $d ,  number_format($this->choutamt_data, 2, '.', ',').'  บาท'  , 0 , 1,'R' );


/*$pdf->Cell( 30  , 4 ,  '(42) เปลี่ยน ส/ค ต่างสาขา' ) , 0 , 0 );
$pdf->Cell( 15  , 4 ,  number_format($this->qother_data).' ,') , 0 , 0  );
$pdf->Cell( 23  , 4 ,  number_format($this->otheramt_data, 2, '.', ',').'  บาท' ) , 0 , 1,'R' );*/


$pdf->Cell(0,3,$line);
$pdf->Ln(4);

$pdf->Cell( $a  , $d ,  'รายละเอียดสมาชิกใหม่ :'  , 0 , 1 );

  
          $newmember = $this->getmember_data ;
          $count = count($newmember);
            if ($count > 0){ 
                
                $countsum = 0;
                $sumnew = 0;
                foreach($newmember as $m){  
                        
                    //$sumnew =$sumnew+$m['sum_net_amt'];
                    $sumnew+=$m['sum_net_amt'];
                    $countsum+=$m['count(a.doc_no)'];
                    
                        $pdf->Cell( $a  , $d ,  $m['promo_code'].' '  , 0 , 0 );
                        $pdf->Cell( $b  , $d ,  $m['count(a.doc_no)'] .' ,' , 0 , 0 ,'R');
                        $pdf->Cell( $c  , $d ,  number_format($m['sum_net_amt'], 2, '.', ',').'  บาท'  , 0 , 1 ,'R');
                        //echo "<div class=div-table-row><div class=div-table-col1>". $m['promo_code']."</div><div class='div-table-col2'>= " .$m['count(a.doc_no)']." ใบ</div><div class=div-table-col3>" .number_format($m['sum_net_amt'], 2, '.', ','). "  บาท</div></div>";    
                }
               
                // $pdf->Cell( 50  , 4 , '************* รวม   '.$countsum.'   ใบ   '. number_format($sumnew, 2, '.', ',').'   บาท' ) , 0 , 1 ,'R');
               //  echo'<div class='div-table-row'><div class=div-table-col> ************* รวม   ".$countsum."   ใบ ". number_format($sumnew, 2, '.', ',')."   บาท</div></div>"; 
                $pdf->Cell( $a  , $d ,  '************* รวม '  , 0 , 0 );
                $pdf->Cell( $b  , $d ,  $countsum .' ,' , 0 , 0 ,'R');
                $pdf->Cell( $c  , $d ,  number_format($sumnew, 2, '.', ',').'  บาท'  , 0 , 1 ,'R');
            }
 

            $pdf->Cell( $a  , $d ,  'สมาชิก'  , 0 , 0 );
            $pdf->Cell( $b  , $d ,  number_format($this->getmember_data2).' ,'  , 0 , 0 ,'R');
            $pdf->Cell( $c  , $d ,  number_format($this->getmemamt_data, 2, '.', ',').'  บาท'  , 0 , 1 ,'R');
                        
            
            $pdf->Cell( $a  , $d ,  'ลูกค้าทั่วไป'  , 0 , 0 );
            $pdf->Cell( $b  , $d ,  number_format($this->getwalkin_data).' ,'  , 0 , 0 ,'R');
            $pdf->Cell( $c  , $d ,  number_format($this->getwkamt_data, 2, '.', ',').'  บาท'  , 0 , 1 ,'R');


$pdf->Ln(7);
$pdf->Cell( $a  , $d ,  'รายละเอียดบัตรเครดิต  :' ) , 0 , 1 );
$pdf->Ln(7);

    
    $sumkbank = 0 ;
    $sumbblbank = 0 ;
    $sumscbbank = 0 ;
    
    $arr_data=$this->getpaid_data;
    $count = count($arr_data);
    if ($count > 0){ 
      
      $pdf->Cell( $a  , $d ,  'บัตรเครดิต กสิกรไทย   :'  , 0 , 1 );
        foreach($arr_data as $m){     
         $pdf->SetMargins( 0,0,5 );  // ซ้าย , บน , ขวา
         $sumkbank+=$m['net_amt'];        
         $pdf->Write( 1  ,  number_format($m['net_amt'], 2, '.', ',').' / ' ) );
         $pdf->SetMargins( 0,0,5 );
        }
        
        $pdf->Ln(8);  
        
        $pdf->Cell( 50  , $d ,  "รวม  ".number_format($sumkbank, 2, '.', ',').'    บาท'  , 0 , 1 );
        $pdf->Ln(8);
       // echo"<br> รวม ".number_format($sumkbank, 2, '.', ',')." บาท <br>";
    }
    
   
    
    $arr_data2=$this->getpaid_data2;
    $count2 = count($arr_data2);
    if ($count2 > 0){ 
      $pdf->Cell( 30  , $d ,  'บัตรเครดิต กรุงเทพ   :'  , 0 , 1 );
        foreach($arr_data2 as $m){     
         //echo "<div class="div-table-row"><div class="div-table-col">";
         $pdf->SetMargins( 0,0,5 );  // ซ้าย , บน , ขวา
         $sumbblbank+=$m['net_amt'];         
         $pdf->Write( 5  ,  number_format($m['net_amt'], 2, '.', ',').' / ' ) );
         $pdf->SetMargins( 0,0,5 );
        }
       
        $pdf->Ln(8);
        $pdf->Cell( 50  , $d ,  "รวม  ".number_format($sumbblbank, 2, '.', ',').'    บาท'  , 0 , 1 );
        $pdf->Ln(8);
    }
    
   //echo "<br>";
    
   $arr_data3=$this->getpaid_data3;
    $count3 = count($arr_data3);
    if ($count3 > 0){ 
      
      $pdf->Cell( 30  , $d ,  'บัตรเครดิต ไทยพาณิชย์   :'  , 0 , 1 );
        foreach($arr_data3 as $m){     
         //echo "<div class="div-table-row"><div class="div-table-col">";
         $pdf->SetMargins( 0,0,5 );  // ซ้าย , บน , ขวา
         $sumscbbank+=$m['net_amt'];
         $pdf->Write( 0  ,  number_format($m['net_amt'], 2, '.', ',').' / '  );
         $pdf->SetMargins( 0,0,5 );
        }   
        
        $pdf->Cell( 50  , $d ,  "รวม  ".number_format($sumscbbank, 2, '.', ',').'    บาท' , 0 , 1 );
        $pdf->Ln(8);
    }
    
     
    
    $sum_bank = $sumkbank+$sumbblbank+$sumscbbank;
    $sum_count = $count+$count2+$count3;
  
    if ($sum_bank > 0 and $sum_count > 0){
   // $pdf->Ln(5);    
    $pdf->Cell( 50  , $d , '************* รวมทั้งหมด '.$sum_count.'   ฉบับ'  , 0 , 1 );    
    $pdf->Cell( 50  , $d , '************* รวมเป็นเงิน '.number_format($sum_bank, 2, '.', ',')."  บาท" , 0 , 1 );  
    $pdf->Ln(8);
    //echo "************* รวมทั้งหมด ".$sum_count."  ฉบับ <br>" ;
   // echo "************* รวมเป็นเงิน ".number_format($sum_bank, 2, '.', ',')."  บาท";
    }
    

$line2="*******************************************************************";
$pdf->Ln(5);
$pdf->Cell(0,3,$line);
$pdf->Ln(7);

$arr_bill=$this->getbill_datano;
foreach($arr_bill as $b){ 
   
    $pdf->Cell( 70  , $d ,  $b['remark']  , 0 , 1 );
    $pdf->Cell( 40  , $d ,  $b['count'].'  ฉบับ',0,0 );
    $pdf->Cell( 40  , $d ,  number_format($b['quantity'], 0, '.', ','). '  ชิ้น ',0,0 );
    $pdf->Cell( 40  , $d ,  number_format($b['amount'], 0, '.', ','). '  บาท',0,1 );
       
    $pdf->cell( 150  , $d ,  $b['min'].' - '.$b['max']  , 0 , 1 );
    $pdf->Ln(7);  
 }

$arr_cancel=$this->getcancel_data;
$countarr = 0;
$amt = 0;

    $pdf->Cell( 30  , $d ,  'บิลยกเลิก' , 0 , 1 );
    
foreach($arr_cancel as $c){ 
    $countarr = count($arr_cancel);
    $amt += $c['amount'];
    
    $pdf->Cell( 70  , $d ,  $c['doc_no'] ,0,0 );
    $pdf->Cell( 60  , $d ,  number_format($c['quantity'], 0, '.', ','),0,0 ,'R' );
    $pdf->Cell( 60  , $d ,  number_format($c['amount'], 2, '.', ','). '  บาท',0,1,'R' );
}    

    $pdf->Ln(7);  
 
    $pdf->Cell( 70  , $d ,  '******* รวม ',0,0 );
    $pdf->Cell( 70  , $d ,  $countarr. ' บิล ',0,0 );
    $pdf->Cell( 50  , $d ,  '  เป็นเงิน   '.number_format($amt, 2, '.', ','). '  บาท',0,1,'R');
    

$pdf->Cell(0,7,$line,0,1);
$pdf->Cell( $a  , 7 ,  'รายละเอียดส่วนลดสมาชิก  :' ) , 0 , 1 );
$arr_mem5=$this->getmember5_dis_data;
foreach($arr_mem5 as $m){
$pdf->Cell( 90  , $d ,  'ส่วนลดสมาชิก 5%'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->getmember5_count_data , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}

$arr_mem15=$this->getmember15_dis_data;
foreach($arr_mem15 as $m){
$pdf->Cell( 90  , $d ,  'ส่วนลดสมาชิก 15%'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->getmember15_count_data , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}

$arr_mem15_10=$this->getmember15_10_dis_data;
foreach($arr_mem15_10 as $m){
$pdf->Cell( 90  , $d ,  'ส่วนลดสมาชิก 15% + 10%'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->getmember15_10_count_data , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}


$arr_mem25=$this->getmember25_dis_data;
foreach($arr_mem25 as $m){
$pdf->Cell( 90  , $d ,  'ส่วนลดสมาชิก 25%'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->getmember25_count_data , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}


$arr_mem50=$this->getmember50_dis_data;
foreach($arr_mem50 as $m){
$pdf->Cell( 90  , $d ,  'คูปองพนักงานส่วนลด 50%'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->getmember50_count_data , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_net_amt'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}

$pdf->Cell(0,7,$line,0,1);
$pdf->Cell( $a  , $d ,  'รายละเอียดส่วนลดโปรโมชั่น  :' ) , 0 , 1 );


$arr_disc=$this->disc_data;
foreach($arr_disc as $m){
$pdf->Cell( 90  , $d ,  'ส่วนลดโปรโมชั่น'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->count_discount_trn2 , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}

$arr_coupon_disc=$this->coupon_disc_data;
foreach($arr_coupon_disc as $m){
$pdf->Cell( 90  , $d ,  'คูปองส่วนลด'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->count_coupon_discount , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['sum_discount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}


$arr_newbirth=$this->newbirth_data;
foreach($arr_newbirth as $m){     
$pdf->Cell( 90  , $d ,  'บิลใช้สิทธิ์วันเกิด'  , 0 , 0 );
$pdf->Cell( 50  , $d ,  $this->count_newbirth , 0 , 0 ,'R' );
$pdf->Cell( 50  , $d , number_format($m['amount'], 2, '.', ',').'  บาท'  , 0 , 1,'R' );    
    
}

$pdf->Ln(7);
$pdf->Cell(0,7,$line,0,1);
$pdf->Ln(7);

$pdf->Cell( 70  , $d ,  'จำนวน EDC  =  '.$sum_count  , 0 , 0 );
$pdf->Ln();

$pdf->Cell( 7  , $d ,  'ลายเซ็นต์พนักงานขาย  :  __________________________________'  , 0 , 0 );

$pdf->Ln(7);
$pdf->Cell( 0  , $d ,  '.'  , 0 , 0 );
//$pdf->Output();
$name='printmt2.pdf';
$output="/var/www/pos/htdocs/report/printreport/".$name;
//$pdf->Output($output,'F');
@chmod($output,7777); 

if(@file_exists($output)){
		 shell_exec("rm $output");
		@unlink($output);
	}
 
$pdf->Output($output,'F');
//shell_exec("lp -o media=letter $output");
	

?>
