<style type="text/css">   
    .div-table{display:table; width: 500px;  }
    .div-table-row{display:table-row;}
    .div-table-col1{display:table-cell; padding-left:  10px; padding-right:  100px; width: 250px;}
    .div-table-col2{display:table-cell; padding-left:  50px; }
    .div-table-col3{display:table-cell; padding-left:  50px; float: right;}
	.div-table-col4{display:table-cell; padding-left:  10px; width: 400px;}
	.div-table2{display:table; width: 500px;  }
    .div-table-row2{display:table-row;}
    .div-table-coll1{display:table-cell; padding-right:  100px; width: 250px; border: 1px;}
</style>

<style type="text/css">
table.sample {
	margin-left:30px;
	border-width: 1px;
	border-spacing: 2px;
	border-style: solid;
	border-color: gray;
	border-collapse: collapse;
	background-color: white;
	width:500px;
}
table.sample th {
	border-width: 1px;
	padding: 1px;
	border-style: inset;
	border-color: gray;
	background-color: white;
	-moz-border-radius: ;
}
table.sample td {
	border-width: 1px;
	padding: 1px;
	border-style: inset;
	border-color: gray;
	background-color: white;
	-moz-border-radius: ;
}
</style>
<p align="center">
    <img src="/report/img/logo/op/op-logo.gif">
    <br><br>รายงาน Commission<br>
    ประจำวันที่ <?php echo $this->s_date. " - " .$this->e_date ; ?></p>
<div class="div-table">
<div class="div-table-row">   
    <div class="div-table-col1">วันที่พิมพ์เอกสาร <?php echo $this->print_time ;?></div>
    <div class="div-table-col3">เวลา  <?php echo $this->ptime ;?></div>
</div>
<div class="div-table-row">
    <div class="div-table-col1">จุดขาย :  <?php echo $this->branch_id.' '.$this->branch_name ;?></div>  
</div>
<div class="div-table-row">
    <div class="div-table-col1">เงื่อนไข :  <?php echo $this->dayfrom.' -  '.$this->tofrom ;?></div>   
</div>
</div> <!-- end div table -->
<br>
<table class="sample">
  <tr>
    <th>วันที่</th>
    <th>ยอดขาย</th>
    <th>ส่วนลด</th>
    <th>ยอดขายสุทธิ</th>
  </tr>
<?php 
  foreach($this->getcomm_data as $comm){ 
  	$sum_amount+=$comm['sum(`amount`)']; 
  	$sum_discount+=$comm['discount'];
  	$sum_net_amt+=$comm['sum(`net_amt`)'];
  	echo "<tr>
  			<td>".$comm['doc_date']."</td>
  			<td align=right>".number_format($comm['sum(`amount`)'], 2, '.', ',')."</td>
  			<td align=right>".number_format($comm['discount'], 2, '.', ',')."</td>
  			<td align=right>".number_format($comm['sum(`net_amt`)'], 2, '.', ',')."</td>
  		  </tr>";
}
	echo "<tr>
  			<td align=right>รวม</td>
  			<td align=right>".number_format($sum_amount, 2, '.', ',')."</td>
  			<td align=right>".number_format($sum_discount, 2, '.', ',')."</td>
  			<td align=right>".number_format($sum_net_amt, 2, '.', ',')."</td>
  		  </tr>";
?>
</table>
<br><br>
<?php
$dayfrom =$this->dayfrom;
$tofrom =$this->tofrom;
$day = $this->get_doc_date;
$today = date('Y-m-d');
if ($this->get_printer == 'N'){
	echo "<div align=right>
	<form action='/report/report/printcomm' method='post'>
	<input type=hidden id=start_date name=start_date value='$dayfrom'>
	<input type=hidden id=end_date name=end_date value='$tofrom'>
	<input type=submit value= พิมพ์รายงาน  id=print>
	</form>";  // print dot matrix
}else{
	echo "<div align=right>
			<form action='/report/report/printcomm' method='post'>
			<input type=hidden id=start_date name=start_date value='$dayfrom'>
			<input type=hidden id=end_date name=end_date value='$tofrom'>
			<input type=submit value= พิมพ์รายงาน  id=print>
			</form>";  // print dot thermal
}
?>
</div>