<?php
$datatambon=$this->datatambon;

    echo "<select class='list1' name='send_tambon_id' id='id_tambon_id' onchange=\"findpostcode('id_postcode');\" style='width:200px;'>";
    foreach($datatambon as $tambon){
    	$tambon_id=$tambon['tambon_id'];
    	$tambon_name=$tambon['tambon_name'];
    	
      	echo "<option value=\"$tambon_id\">$tambon_name</option>";
      
    }
    echo "</select>";
?>