<?php 

echo"
<br>
<table width='100%' border='0' cellpadding='0' cellspacing='0'>
<tr>
	<td width='50%' align='center'>
		<button  id='btn_payment_yes' class='ui-corner-all' style='padding: 5px; background-color: rgb(162, 163, 188); font-size: 20px;'>										
			ตกลง
		</button>
	</td>
	<td width='50%' align='center'>
		<button  id='btn_payment_no' class='ui-corner-all' style='padding: 5px; background-color: rgb(162, 163, 188); font-size: 20px;'>										
			ยกเลิก
		</button>
	</td>
 </tr>
</table>";
?>