<div>
	<label>PRODUCT ID :</label>
	<input type="text" size="20" id="stock_product_id" class="input-text-pos ui-corner-all"></input>
</div><br/>
<div id="checkstock_content">
	<table width="100%" cellspacing="1" cellpadding="2" bgcolor="#92C7C7">
				<tr bgcolor="#7BCCB5" height="30" >
					<td align="center" ><span style="color:#fff;font-size:20px;">PRODUCT ID</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">DESCRIPTION</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">BEGIN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">SALE</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">IN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">OUT</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">CN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ADJ IN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ADJ OUT</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ONHAND</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ALLOCATE</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">FIX STOCK</span></td>
				</tr>	
		<tr bgcolor="#f4f4f4"><td colspan='12'>&nbsp;</td></tr>
	</table>
</div>