<?php 
		//print_r($this->arr_stock);
		if(!empty($this->arr_stock)){
				?>
				<table width="100%" cellspacing="1" cellpadding="2" bgcolor="#92C7C7">
				<tr bgcolor="#7BCCB5" height="30" >
					<td align="center" ><span style="color:#fff;font-size:20px;">PRODUCT ID</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">DESCRIPTION</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">BEGIN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">SALE</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">IN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">OUT</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">CN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ADJ IN</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ADJ OUT</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ONHAND</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">ALLOCATE</span></td>
					<td align="center" ><span style="color:#fff;font-size:20px;">FIX STOCK</span></td>
				</tr>	
				<?php 
			$i=0;
			foreach($this->arr_stock as $data){
				$product_id=$data['product_id'];
				($i%2==0)?$bg_color="#ffffff":$bg_color="#F2F0D1";
				?>
				<tr bgcolor="<?php echo $bg_color;?>" height="27">
					<td align="center"><?php echo $data['product_id'];?></td>
					<td align="left"><?php echo $data['name_product'];?></td>
					<td align="center"><?php echo intval($data['begin']);?></td>
					<td align="center"><?php echo intval($this->arr_stock_sl[$product_id]);?></td>
					<td align="center"><?php echo intval($this->arr_stock_ti[$product_id]);?></td>
					<td align="center"><?php echo intval($this->arr_stock_to[$product_id]);?></td>
					<td align="center"><?php echo intval($this->arr_stock_cn[$product_id]);?></td>
					<td align="center"><?php echo intval($this->arr_stock_ai[$product_id]);?></td>
					<td align="center"><?php echo intval($this->arr_stock_ao[$product_id]);?></td>
					<td align="center"><?php echo intval($data['onhand']);?></td>
					<td align="center"><?php echo intval($data['allocate']);?></td>
					<td align="center"><?php echo $this->fix_stock;?></td>
				</tr>	
				<?php 
				$i++;
			}
			?>
			</table>
			<?php 
		}
	?>