     <style type="text/css">
			.tableNavDocStatus
				{
					width:100%;
					background:#333;
				}
			.tableNavDocStatus ul
				{
					float:right;
					width:100%;
					margin:0;
					padding:0;
					border:1px solid #C9C9C9;
				}
          .tableNavDocStatus ul li{
          		cursor:pointer;
					list-style-type:none;
					line-height: 40px;
					font-family:"PSLKittithadaBold","Garuda","Tahoma", "Geneva", "Arial", sans-serif;
					font-weight: normal;
					font-size:22px;
					text-decoration:none;
					color:#303030;
					padding-left:1em;
					border-bottom:1px solid  #78777C;
					text-shadow: 0px 1px 0px #dddddd;
					vertical-align: middle;
					white-space:nowrap;
					background:#B2B2B8;
					background:  -moz-linear-gradient(#D4D7E0,#B0B0B0);;
					background: -webkit-gradient(linear, left top, left bottom, color-stop(0,#D4D7E0), color-stop(1, #B0B0B0));
					-moz-user-select:none;
					-moz-user-select:-moz-none;/*latest ff*/
					-webkit-user-select:none;
          }
          ul li.active {
            cursor:pointer;
          			list-style-type:none;
					line-height: 40px;
					font-family: "PSLKittithadaBold","Garuda","Tahoma", "Geneva", "Arial", sans-serif;
					font-weight: normal;
					font-size:25px;
					text-decoration:none;
					color:#008080;/*#303030*/
					padding-left:1em;
					border-bottom:1px solid  #000;/*78777C*/
					text-shadow: 0px 1px 0px #dddddd;
					vertical-align: middle;
					white-space:nowrap;
					background:#F5F5DC;/*#B2B2B8*/
					background:  -moz-linear-gradient(#9DDCCF,#265541);
					background: -webkit-gradient(linear, left top, left bottom, color-stop(0, #D4D7E0), color-stop(1, #F5F5DC));
					-moz-user-select:none;
					-moz-user-select:-moz-none;/*latest ff*/
					-webkit-user-select:none;
          }
          ul li.nokeyboard {
            color: #999;
            background:#0000ff;
          }
    </style>
    <div class="tableNavDocStatus" >
	        <ul>
	        <?php 
	        	$chk_sl='N';
		        foreach($this->arr_data['data'] as $data){
		        	if($data['status_no']=='00'){
		        		$chk_sl='Y';
		        		break;
		        	}
		        }//foreach
		        
		        if($chk_sl=='Y'){
		        	$i=1;
		  			foreach($this->arr_data['data'] as $data){
		  				if($data['status_no']!='09' && $data['status_no']!='16' && $data['status_no']!='18'){
			  				$id_tmp="n_".$i;
			  				$rows_json=json_encode($data);
				  			echo "<li id='$id_tmp' name='$id_tmp' class='btn_sel' idd='".$rows_json."'>".$data['status_no']."&nbsp;&nbsp;".$data['description']."</li>";  
				  			$i++;
		  				}
		  			}//foreach
		        }else{	           
		        	$i=1;
		  			foreach($this->arr_data['data'] as $data){
		  				$id_tmp="n_".$i;
		  				$rows_json=json_encode($data);
			  			echo "<li id='$id_tmp' name='$id_tmp' class='btn_sel' idd='".$rows_json."'>".$data['status_no']."&nbsp;&nbsp;".$data['description']."</li>";  
			  			$i++;
		  			}//foreach
		        }
	        ?>
	        </ul>
     </div>