<?php
	if(isset($this->doc_date)){
		$arr_date=explode("-",$this->doc_date); 
		$doc_date=$arr_date[2]."/".$arr_date[1]."/".$arr_date[0];
	}
?>
<div id="frm_closeday">
	<table width="100%" height="85" border="0" cellpadding="2" cellspacing="5" >
		<tr height="27">
			<td width="35%" align="right">Date of Close Bill&nbsp;:</td>
			<td width="70%">
				<input type="text" id="sel_docdate" size="15" class="input-text-pos ui-corner-all" value="<?php echo $doc_date;?>" readonly></input>
			</td>
		</tr>
		<tr height="27">
			<td width="35%" align="right">Enter Date&nbsp;:</td>
			<td width="70%">
				<input type="text" id="sel_closeday" size="15" class="input-text-pos ui-corner-all" ></input>&nbsp;
				<input type="hidden" id="sel_closeday_alternate" size="15"></input>
			</td>
		</tr>
	</table>
</div>