<?php 	

		echo"
		<table width='100%' border='0' cellpadding='0' cellspacing='5' 
		<tr>
			<td align='right'>คูปอง Barcode&nbsp;:</td>
			<td><input type='text' size='20' id='form_tour_barcode' name='form_tour_barcode' class='keybarcode input-text-pos ui-corner-all'></input></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td align='right'>PASSPORT NO.&nbsp;:</td>
			<td><input type='text' size='20' id='form_tour_passport' name='form_tour_passport' class='input-text-pos ui-corner-all'></input></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td align='right'>Email&nbsp;:</td>
			<td>
				<input type='text' size='20' id='form_tour_email' name='form_tour_email' last='btn_check_shockprice' class='otp input-text-pos ui-corner-all'>
				<input type='hidden' id='sp_otp_ok' class='input-text-pos ui-corner-all'>
			</td>
			<td>&nbsp;(Optional)</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td align='left'><div id='opt_msg'>&nbsp;</div></td>
			<td>&nbsp;</td>
		</tr>
		</table>
		";		

	
?>

<script type="text/javascript">


$(function(){	
	$('#form_tour_barcode').keydown(function(e){
		if(e.which === 13 && $('#form_tour_barcode').val() !="" ) {
			$('#form_tour_passport').focus();
		}
	});

	$('#form_tour_passport').keydown(function(e){
		if(e.which === 13 && $('#form_tour_passport').val() !="" ) {
			$('#form_tour_email').focus();
		}
	});
});
</script>
