<?php 	

		//print_r($this->promo_req);
		
		$chk_arr = explode(',',$this->promo_req);
		//print_r($chk_arr);
				echo"
		<table width='100%' border='0' cellpadding='0' cellspacing='5' >";
		while($tmp = array_shift($chk_arr)){
			switch(strtoupper($tmp)){
				case 'T':
					echo "<tr>
					<td align='right'>Tel &nbsp;:</td>
					<td><input type='text' size='20' id='form_tour_tel' name='form_tour_tel' class='input-text-pos ui-corner-all'></input></td>
					<td>&nbsp;</td>
				</tr>";
				break;
			
			}
		}

		echo"<tr>
			<td align='right'>Code &nbsp;:</td>
			<td><input type='text' size='20' id='form_tour_barcode' name='form_tour_barcode' class='input-text-pos ui-corner-all'></input></td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td align='left'><div id='opt_msg'>&nbsp;</div></td>
			<td>&nbsp;</td>
		</tr>
		</table>
		";		

	
?>

<script type="text/javascript">


$(function(){	
	$('#form_tour_barcode').keydown(function(e){
		if(e.which === 13) {
			proussd($('#form_tour_barcode').val());
		}
	});

});
</script>
