<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?php echo $this->pageTitle;?></title>
<link rel='stylesheet' type='text/css' href='/stock/css/style.css'>
<link type="text/css" href="/stock/css/theme_op/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
<link type="text/css" href="/stock/css/check_stock.css" rel="stylesheet" />
<link type="text/css" href="/stock/css/flexigrid.css" rel="stylesheet" />

<script type="text/javascript" src="/stock/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/stock/js/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" src="/stock/js/jquery.alerts.js"></script>
<script type="text/javascript" src="/stock/js/stock.js"></script>
<script type="text/javascript" src="/stock/js/flexigrid.js"></script>
<script type="text/javascript" src="/stock/js/niceforms.js"></script>
<script type="text/javascript" src="/stock/js/jquery.hotkeys.js"></script>
<link type="text/css" href="/stock/css/jquery.alerts.css" rel="stylesheet" />
<link type="text/css" href="/stock/css/niceforms-default.css" rel="stylesheet" />
</head>
<body>
<?php		
echo $this->layout()->content;		
 ?>		
</body>
</html>