<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<meta charset="utf-8">
	
<p>
  <APPLET CODE = 'idcard.RdNationalCardID' archive='../include/RdNIDApplet090DL.jar' name='NIDApplet' WIDTH = "0" HEIGHT = "0">
  </APPLET>  
  <script>

function readIDCARD(){
		if(!document.NIDApplet.isCardInsertRD()){
			alert("คุณยังไม่ได้ Scan บัตรประชาชน");
			return false;
		}

		var id_card = document.NIDApplet.getNIDNumberRD();
		alert(id_card);

		document.getElementById('id_card').value=id_card;



}
function onreadidcheck(){
	if(!document.NIDApplet.isCardInsertRD()){
		alert("คุณยังไม่ได้ Scan บัตรประชาชน");
		return false;
	}


	if(document.NIDApplet.isCardInsertRD()){

		var data = document.NIDApplet.getNIDDataRD();
		alert(data);
		var data_arr = data.split('#');

		//var photo = document.NIDApplet.getNIDPictureRD();
		//$('img_from_card_reader').innerHTML="<img width='150' src='data:image/png;base64,"+photo+"'>";


		
		// _d[0] บัตรประชาชน
		/*var _id1=_d[0].substr(0,1);
		var _id2=_d[0].substr(1,4);
		var _id3=_d[0].substr(5,5);
		var _id4=_d[0].substr(10,2);
		var _id5=_d[0].substr(12,1);
	
		document.getElementById('idcard_1').value=_id1;
		document.getElementById('idcard_2').value=_id2;
		document.getElementById('idcard_3').value=_id3;
		document.getElementById('idcard_4').value=_id4;
		document.getElementById('idcard_5').value=_id5;*/

		document.getElementById('id_card').value=data_arr[0];
		document.getElementById('mr').value=data_arr[1];
		document.getElementById('fname').value= data_arr[2];
		document.getElementById('lname').value= data_arr[4];
		
		document.getElementById('mr_en').value=data_arr[5];
		document.getElementById('fname_en').value= data_arr[6];
		document.getElementById('lname_en').value= data_arr[8];
		
		document.getElementById('address1').value= data_arr[9];
		document.getElementById('address2').value= data_arr[10];
		document.getElementById('address3').value= data_arr[14];
		document.getElementById('address4').value= data_arr[15];
		document.getElementById('address5').value= data_arr[16];
		var sex=data_arr[17];
		var sex_show="";
			if(sex==1){
				sex_show="ชาย";
			}else{
				sex_show="หญิง";
			}
		document.getElementById('sex').value= sex_show; //เพศ
		var hbd=data_arr[18];
			hbd_d=hbd.substr(6,2);
			hbd_m=hbd.substr(4,2);
			hbd_y=hbd.substr(0,4);
			hbd_format=hbd_d+"/"+hbd_m+"/"+hbd_y;
		document.getElementById('hbd').value= hbd_format; //วันเกิด
		document.getElementById('card_at').value= data_arr[19]; //สถานที่ออกบัตร
		var start_date=data_arr[20];
			start_date_d=start_date.substr(6,2);
			start_date_m=start_date.substr(4,2);
			start_date_y=start_date.substr(0,4);
			start_date_format=start_date_d+"/"+start_date_m+"/"+start_date_y;
		document.getElementById('start_date').value= start_date_format;//วันออกบัตร
		var end_date=data_arr[21];
			end_date_d=end_date.substr(6,2);
			end_date_m=end_date.substr(4,2);
			end_date_y=end_date.substr(0,4);
			end_date_format=end_date_d+"/"+end_date_m+"/"+end_date_y;
		document.getElementById('end_date').value= end_date_format;//วันหมดอายุ



	
	}
	 	
}

function readPic(){
	if(!document.NIDApplet.isCardInsertRD()){
		alert("คุณยังไม่ได้ Scan บัตรประชาชน");
		return false;
	}
	
	
	var data = document.NIDApplet.getNIDPictureRD();

	if(data==null){
		alert("Can not get Picture");
		return false;
	}
	document.getElementById('show_pic').innerHTML="<img width='150' src='data:image/png;base64,"+data+"'>";
}
</script>
</p>
<table width="200" border="0" id='pro_renew'>
  <tr>
    <th colspan="5">ข้อมูลบัตร
    </th>
  </tr>
  <tr>
    <td>Member ID </td>
    <td><input name="member_id" type="text" id="member_id" readonly="true" class='tb3' /></td>
    <td>สาขาที่สมัคร</td>
    <td><input name="branch_id" type="text"class='tb3' id="branch_id" size="15" readonly="true" /></td>
    <td valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td>Apply Date </td>
    <td><input name="apply_date_show" type="text" class='tb3' id="apply_date_show" size="15" readonly="true"/>
        <input name="apply_date" type="hidden" id="apply_date" /></td>
    <td>Expier Date </td>
    <td><input name="expire_date_show" type="text" class='tb3' id="expire_date_show" size="15" readonly="true"/>
        <input name="expire_date" type="hidden" id="expire_date" /></td>
    <td valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td>บิลที่สมัคร</td>
    <td><input name="doc_no" type="text" id="doc_no" size="50" readonly="true" class='tb3'/></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td valign="top">&nbsp;</td>
  </tr>
</table>
<table border="0" id='pro_renew'>
  <tr>
    <th colspan="5">ข้อมูลส่วนตัว</th>
  </tr>
  <tr>
    <td height="30" colspan="5" align="center"><div id="get_idcard" onclick="onreadidcheck()" class='btn2' onmouseout="this.className='btn2' " onmouseover="this.className='btn2_over' ">Scan บัตรประชาชน</div></td>
  </tr>
  <tr>
    <td width="144">รหัสบัตรประชาชน</td>
    <td width="148"><label>
      <input name="id_card" type="text" id="id_card" class='tb6' />
    </label></td>
    <td width="148"><div align="right">วันเกิด</div></td>
    <td width="148"><input name="hbd" type="text" id="hbd" class='tb6' /></td>
    <td width="181" rowspan="9" valign="top"></td>
  </tr>
  <tr>
    <td>ชื่อ</td>
    <td colspan="3"><input name="mr" type="text" id="mr" size="10" class='tb6'>      <input name="fname" type="text" id="fname" class='tb6'>      <input name="lname" type="text" id="lname" class='tb6'></td>
  </tr>
  <tr>
    <td>Name</td>
    <td colspan="3"><input name="mr_en" type="text" id="mr_en" size="10" class='tb6'>      <label>
      <input name="fname_en" type="text" id="fname_en" class='tb6'>
      </label>      <label>
      <input name="lname_en" type="text" id="lname_en" class='tb6'>
      </label></td>
  </tr>
  <tr>
    <td>บ้านเลขที่</td>
    <td><label>
      <input name="address1" type="text" id="address1" class='tb6'>
    </label></td>
    <td><div align="right">หมู่ที่    </div></td>
    <td><input name="address2" type="text" id="address2" class='tb6' /></td>
  </tr>
  <tr>
    <td>ตำบล</td>
    <td><input name="address3" type="text" id="address3" class='tb6'></td>
    <td><div align="right">อำเภอ</div></td>
    <td><input name="address4" type="text" id="address4" class='tb6' /></td>
  </tr>
  <tr>
    <td>จังหวัด</td>
    <td><input name="address5" type="text" id="address5" class='tb6'></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>เพศ</td>
    <td><input name="sex" type="text" id="sex" class='tb6'></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>หน่วยงานที่ออกบัตร</td>
    <td colspan="3"><input name="card_at" type="text" id="card_at" size="50" class='tb6'></td>
  </tr>
  <tr>
    <td>วันออกบัตร</td>
    <td><input name="start_date" type="text" id="start_date" class='tb6'></td>
    <td><div align="right">วันบัตรหมดอายุ</div></td>
    <td><input name="end_date" type="text" id="end_date" class='tb6' /></td>
  </tr>
  <tr>
    <td colspan="5">
    <table align="center">
      <tr>
        <td><div id='button' onclick='register_save();' class='btn3' onmouseout="this.className='btn3' " onmouseover="this.className='btn3_over' ">บันทึก</div></td>
        <td><div id='Button2'  onclick='to_list();'  class='btn3' onmouseout="this.className='btn3' " onmouseover="this.className='btn3_over' ">ยกเลิก</div></td>
      </tr>
	</table>  
    </table>
