<?php	
	include(FPDF_PATH."/fpdf.php");
        //4.00" x 3.00" - (10.16cm x 7.62cm)
        $hl=5;
        $hl1=4;
        $hl2=3;
        $maxdoc=72;
        $logo="/op-logo.gif";
        $pdf=new FPDF('P','mm','tm-t88iv');
        $pdf->SetThaiFont();
        $pdf->AddPage();
        $pdf->SetY(2);
		$pdf->SetX(0);
		$pdf->SetMargins(0,2,0); 
        $pdf->SetAutoPageBreak("off",1);
        //$pdf->Image('/var/www/pos/htdocs/sales/img/op/op-logo.gif',2,0,65);
        $pdf->Image(LOGO_PATH.$logo,2,0,65);
        $pdf->SetY(8);
        $pdf->SetFont('CordiaNew','B',13); 
        $pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['company_name_print']),0,0,'C',0); 
	$str_cancel='';
	if($this->arr_h[0]['flag']=='C'){
		$str_cancel='<ยกเลิก>';
		$str_cancel=iconv('UTF-8','cp874',$str_cancel);
	}
        $pdf->Ln();      
        $pdf->Cell($maxdoc,$hl,"$str_cancel TAX INVOICE (ABB.)",0,0,'C',0); 
        $pdf->Ln();
        $pdf->Ln();
        $pdf->SetFont('CordiaNew','B',10);//B
        $pdf->Cell(10,$hl1,"TAX ID :",0,0,'L',0); 
        $pdf->Cell(25,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
        $pdf->Cell(4,$hl1,"",0,0,'L',0);
        $pdf->Cell(33,$hl1,"POS ID : ".$this->arr_h[0]['pos_id'],0,0,'R',0); 
        $pdf->Ln();
        $pdf->Cell($maxdoc,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0); 
        $pdf->Ln();
        
        $pdf->Cell(8,$hl1,"Rcpt : ",0,0,'L',0); 
		$pdf->Cell(25,$hl1,$this->arr_h[0]['doc_no'],0,0,'L',0);	
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$arr_docdate=explode("-",$this->arr_h[0]['doc_date']);
		$doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
		$pdf->Cell(33,$hl1,$doc_date_show." ".$this->arr_h[0]['doc_time'],0,0,'R',0); 
		
        $pdf->Ln();
        $pdf->Cell(15,$hl1,"Member ID : ",0,0,'L',0); 
        $pdf->Cell(32,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
        $pdf->Cell(12,$hl1,"Cashier :",0,0,'R',0); 
        $pdf->Cell(13,$hl1,$this->arr_h[0]['saleman_id'],0,0,'R',0);		
        $pdf->Ln();
        
         if($this->arr_h[0]['status_no']=='03'){
	        $pdf->Cell($maxdoc,$hl1,"Name : ".iconv('UTF-8','cp874',$this->arr_h[0]['emp_fullname']),0,0,'L',0); 
	        $pdf->Ln();
        }
        
        //--------- product item ------------------
      	$pdf->SetFont('CordiaNew','',10);
      	$discount=$this->arr_h[0]['member_percent']+$this->arr_h[0]['special_percent'];
		$member_percent=$this->arr_h[0]['member_percent'];
		$special_percent=$this->arr_h[0]['special_percent'];

        foreach($this->arr_l as $dataL){
        	$name_product=trim($dataL['name_product']);
        	//16
        	if(strlen($name_product)>8){
        		$name_product=mb_substr($name_product,0,8,'utf-8');
        		$name_product.="..";
        	}
        	
        	if(intval($dataL['member_discount1'])==0){
        		$chk_member_percent=0;
        	}else{
        		$chk_member_percent=$member_percent;
        	}
        	
        	if(intval($dataL['member_discount2'])==0){
        		$chk_special_percent=0;
        	}else{
        		$chk_special_percent=$special_percent;
        	}
        	
	        $pdf->Cell(3,$hl2,intval($dataL['quantity']),0,0,'R',0); 
	        $pdf->Cell(11,$hl2,$dataL['product_id'],0,0,'L',0);
	        $pdf->Cell(16,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        $pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);
	        /*
	        $pdf->Cell(26,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        $pdf->Cell(10,$hl2,"[".intval($member_percent)."+".intval($special_percent)."%]",0,0,'L',0);
	        */
	        $pdf->Cell(10,$hl2,number_format($dataL['price'],2),0,0,'R',0);
	        $pdf->Cell(12,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);        
	        $pdf->Ln();
        }        
        //--------- product item ------------------
        $pdf->Ln();
        $pdf->SetFont('CordiaNew','B',10);//B
        $pdf->Cell(24,$hl1,iconv('UTF-8','cp874',"จำนวนชิ้นรวม ="),0,0,'L',0); 
        $pdf->Cell(20,$hl1,intval($this->arr_h[0]['quantity']),0,0,'L',0);
        $pdf->Cell(15,$hl1,"Total",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['amount'],2),0,0,'R',0);
        $pdf->Ln();
        $pdf->Cell(24,$hl1,iconv('UTF-8','cp874',$this->paiddesc),0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,"Discount",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['discount'],2),0,0,'R',0);
        $pdf->Ln();
        $pdf->Cell(24,$hl1,"*** Vat Included ***",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,"Net",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['net_amt'],2),0,0,'R',0);
        $pdf->Ln();
        $pdf->Cell(24,$hl1,"",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,"Received",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['pay_cash'],2),0,0,'R',0);
        
        $pdf->Ln();
        if($this->arr_h[0]['status_no']=='03'){
        	$pdf->Cell(20,$hl1,iconv('UTF-8','cp874',"(คูปองพนักงาน)"),0,0,'L',0); 
		    $pdf->Cell(24,$hl1,"",0,0,'L',0);
        }else if(intval($this->arr_h[0]['redeem_point'])!=0){
         	$total_point_used=$this->arr_h[0]['redeem_point'];
			if(trim($this->arr_h[0]['member_id'])!=''){
		        $pdf->Cell(20,$hl1,iconv('UTF-8','cp874',"คะแนนที่ใช้"),0,0,'L',0); 
		        $pdf->Cell(24,$hl1,"(".$total_point_used.") ".iconv('UTF-8','cp874'," คะแนน"),0,0,'L',0);
			}else{
				 $pdf->Cell(20,$hl1,'',0,0,'L',0); 
		         $pdf->Cell(24,$hl1,'',0,0,'L',0);
			}
        }else if(intval($this->arr_h[0]['point1'])!=0 || intval($this->arr_h[0]['point2'])!=0){
	        $total_point_receive=$this->arr_h[0]['point1']+$this->arr_h[0]['point2'];
			if(trim($this->arr_h[0]['member_id'])!=''){
		        $pdf->Cell(20,$hl1,iconv('UTF-8','cp874',"คะแนนที่ได้รับ"),0,0,'L',0); 
		        $pdf->Cell(24,$hl1,"(".$this->arr_h[0]['point1']."+".$this->arr_h[0]['point2']."=".$total_point_receive.") ".iconv('UTF-8','cp874'," คะแนน"),0,0,'L',0);
			}else{
				 $pdf->Cell(20,$hl1,'',0,0,'L',0); 
		         $pdf->Cell(24,$hl1,'',0,0,'L',0);
			}
        }else{
        	 $pdf->Cell(20,$hl1,'',0,0,'L',0); 
		     $pdf->Cell(24,$hl1,'',0,0,'L',0);
        }
        $pdf->Cell(15,$hl1,"Change",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['change'],2),0,0,'R',0);
        $pdf->Ln();
        $pdf->SetFont('CordiaNew','B',10);
        $pdf->Cell($maxdoc,$hl1,"Customer Satisfaction Guarantee",0,0,'L',0); 
        $pdf->Ln();
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ยินดีรับคืนผลิตภัณฑ์ที่ไม่พึงพอใจในทุกกรณี ภายใน 14 วัน"),0,0,'L',0); 
        $pdf->Ln();
        $pdf->Ln();
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ผู้รับเงิน....................................................................."),0,0,'L',0); 
        $pdf->Ln();
        $pdf->Ln();
        if($this->arr_h[0]['status_no']=='01' || $this->arr_h[0]['status_no']=='02'){
        	$str_bill_desc="";
        	if($this->arr_h[0]['status_no']=='01'){
        		$str_bill_desc="<สมัครสมาชิกใหม่>";
        	}else if($this->arr_h[0]['status_no']=='02'){
        		$str_bill_desc="<ซื้อครั้งแลกส่วนลดพิเศษ>";
        	}
	        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',$str_bill_desc),0,0,'L',0); 	  
	        $pdf->Ln();
        }
        $pdf->Cell(32,$hl1,"www.orientalprincesssociety.com",0,0,'L',0);
        $pdf->Cell(8,$hl1,"",0,0,'L',0); 
        $pdf->Cell(32,$hl1,"Beauty Line : 0-2642-6606",0,0,'L',0);  
        $pdf->Ln();
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"เบอร์โทรศัพท์สาขา : ".$this->arr_h[0]['branch_tel']),0,0,'L',0);
        $name='/billvatshort.pdf';
	    $output=REPORT_PATH.$name;
	    // $output="/var/www/pos/htdocs/sales/report/".$name;
	    @chmod(REPORT_PATH,0777);
	    //$pdf->Output($output);// for test print
	    $pdf->Output($output,'F');
		//echo shell_exec("lp -o media=Letter $output");
		$print2ip=$this->arr_h[0]['print2ip'].":631";
		if($this->arr_h[0]['print2ip']=='LOCAL'){
			echo shell_exec("lp -o media=Letter $output");
		}else{
			echo shell_exec("lp -o media=Letter $output");
			//echo shell_exec("lpr -H $print2ip $output");
		}	
		if(@file_exists($output)){
			echo shell_exec("rm $output");
			//@unlink($output);
		}
?>
