<?php
	include(FPDF_PATH."/fpdf.php");	
	$hl=5;
    $hl1=4;
    $hl2=3;
    $l2br=4;
    $maxdoc=72;
    $logo="/op-logo.gif";
    $pdf=new FPDF('P','mm','a23');
    $pdf->SetThaiFont();
    $pdf->AddPage();
    $startY=2;
	$startX=0;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetMargins(0,2,0); 
    $pdf->SetAutoPageBreak("off",1);
    $pdf->Image(LOGO_PATH.$logo,2,0,65);
    $startY+=8;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  
    $pdf->SetFont('CordiaNew','B',13);
	//--------------------------------------------------------------------  
	 $str_copy="";
     if($this->act=='reprint'){        	
       	$pdf->Cell(2,$hl,"*",0,0,'L',0); 
       	$str_copy="(COPY)";
      }      
	//--------------------------------------------------------------------
     if($this->arr_h[0]['branch_tp']=='F'){
        	if($this->arr_h[0]['title_line1']!=''){
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line1']),0,0,'C',0);     
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);   		
        	}
        	
        	if($this->arr_h[0]['title_line2']!=''){        		
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line2']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}
        	
	       	if($this->arr_h[0]['title_line3']!=''){        		
	        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line3']),0,0,'C',0);   
	        		$startY+=$l2br;
				    $pdf->SetY($startY);
					$pdf->SetX($startX);     		
	        }
        	
       	  	if($this->arr_h[0]['title_line4']!=''){        		
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line4']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}       	
        	
        }else{
			$pdf->Cell(72,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['company_name_print']),0,0,'C',0); 
			$startY+=$hl2;
		    $pdf->SetY($startY);
			$pdf->SetX($startX);      
			$pdf->SetFont('CordiaNew','B',10);
		    $pdf->Cell(72,$hl,"89/1 Soi Ratchataphan,Rachaprarop",0,0,'C',0); 
		    $startY+=$hl2;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 			
		    $pdf->Cell(72,$hl,"Rd. Makkasun Rachatevee Bangkok 10400.",0,0,'C',0); 
		    $startY+=$l2br;
        }
        
        $str_cancel='';
		if($this->arr_h[0]['flag']=='C'){
			$str_cancel='<ยกเลิก>';
			$str_cancel=iconv('UTF-8','cp874',$str_cancel);
		}       
   
    $pdf->SetY($startY);
	$pdf->SetX($startX);    
	$pdf->SetFont('CordiaNew','B',10); 
    $pdf->Cell(72,$hl," $str_cancel TAX INVOICE / RECEIPT $str_copy",0,0,'C',0);        
  
	
	///START
	$str_passport_no=$this->arr_h[0]['idcard'];
	$arr_passport_no=explode(':',$str_passport_no);
	if($arr_passport_no[0]=="PP"){
		$startY+=8;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->SetFont('CordiaNew','B',16);
		$str_passport_print="Passport Number ".$arr_passport_no[1];
		$pdf->Cell($maxdoc,$hl,$str_passport_print,0,0,'C',0);
		$startY+=4;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
	}
	///START
	
	$startY+=$l2br;
	$startY+=$l2br;
	$pdf->SetY($startY);
	$pdf->SetX($startX);
    $pdf->SetFont('CordiaNew','B',10);//B
    $pdf->Cell(10,$hl1,"TAX ID :",0,0,'L',0); 
    $pdf->Cell(25,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
    $pdf->Cell(4,$hl1,"",0,0,'L',0);
    $pdf->Cell(33,$hl1,"POS ID : ".$this->arr_h[0]['pos_id'],0,0,'R',0);   	
    /*
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
    $pdf->Cell(52,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0); 
    $pdf->Cell(12,$hl1,iconv('UTF-8','cp874','Branch No.'.$this->arr_h[0]['branch_seq']),0,0,'R',0); 
    $pdf->Cell(8,$hl1,"#".$this->arr_h[0]['computer_no'],0,0,'R',0);
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	*/
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
    $pdf->Cell(52,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0); 
    $pdf->Cell(12,$hl1,'',0,0,'R',0); 
    $pdf->Cell(8,$hl1,'',0,0,'R',0);
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
    $pdf->Cell(52,$hl1,"Branch No. ".$this->arr_h[0]['branch_seq'],0,0,'L',0); 
    $pdf->Cell(12,$hl1,'',0,0,'R',0); 
    $pdf->Cell(8,$hl1,"#".$this->arr_h[0]['computer_no'],0,0,'R',0);
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
    
	$pdf->Cell(8,$hl1,"Rcpt : ",0,0,'L',0); 
	$pdf->Cell(25,$hl1,$this->arr_h[0]['doc_no'],0,0,'L',0);	
	$pdf->Cell(6,$hl1,"",0,0,'L',0);
	$arr_docdate=explode("-",$this->arr_h[0]['doc_date']);
	$doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
	$pdf->Cell(33,$hl1,$doc_date_show." ".$this->arr_h[0]['doc_time'],0,0,'R',0); 
	
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetFont('CordiaNew','B',10); 
	
	$pdf->Cell(14,$hl1,"Member ID : ",0,0,'L',0); 	
    //$pdf->Cell(34,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
    if(substr($this->arr_h[0]['member_id'],0,2)=='ID'){
    	$str_idcard=$this->arr_h[0]['idcard'];
    	$str_idcard = substr($str_idcard, -4);
    	$str_idcard = "XXXXXXXX-".$str_idcard;
    	$pdf->Cell(34,$hl1,$str_idcard,0,0,'L',0);
       	//$pdf->Cell(34,$hl1,$this->arr_h[0]['idcard'],0,0,'L',0);
       }else{
       	$pdf->Cell(34,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
    }
    
    $pdf->Cell(14,$hl1,"Cashier :",0,0,'R',0); 
    $pdf->Cell(10,$hl1,$this->arr_h[0]['saleman_id'],0,0,'R',0);	
    
    //new 
    $startY+=$l2br;
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->Cell(52,$hl1,"TAX ID : ".$this->arr_h[0]['remark1'],0,0,'L',0);
	if($this->arr_h[0]['remark2']=='-1'){
		$pdf->Cell(20,$hl1,iconv('UTF-8','cp874',"สำนักงานใหญ่"),0,0,'R',0); 
	}else{
		$pdf->Cell(20,$hl1,iconv('UTF-8','cp874',"สาขาที่ ".$this->arr_h[0]['remark2']),0,0,'R',0); 
	}
	//new
    
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','B',10);
    $pdf->Cell(12,$hl1,"Name : ",0,0,'L',0); 
    $name=trim($this->arr_h[0]['name']);
    $name_len=strlen($name);
    if($name!=''){
	    $pdf->SetFont('CordiaNew','',10);
    	if($name_len>50){
        	$name_L1=mb_substr($name,0,50,'utf-8');
        	$name_L2=mb_substr($name,50,50,'utf-8');
        	$pdf->Cell(60,$hl1,iconv('UTF-8','cp874',$name_L1),0,0,'L',0); 
        	 $startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 
			$pdf->Cell(12,$hl1,"",0,0,'L',0);
        	$pdf->Cell(60,$hl1,iconv('UTF-8','cp874',$name_L2),0,0,'L',0); 
        }else{
			$pdf->Cell(60,3,iconv('UTF-8','cp874',$this->arr_h[0]['name']),0,0,'L',0);    
        }
    }
	
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','B',10);
    $pdf->Cell(12,$hl1,"Address : ",0,0,'L',0);     
    if(trim($this->arr_h[0]['address1'])!=''){
	    $pdf->SetFont('CordiaNew','',10);
	    $pdf->Cell(60,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address1']),0,0,'L',0); 
    }    
    if(trim($this->arr_h[0]['address2'])!=''){
	    $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
	    $pdf->Cell(12,$hl1,"",0,0,'L',0); 
	    $pdf->SetFont('CordiaNew','',10);
	    $pdf->Cell(60,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address2']),0,0,'L',0); 
    }
     if(trim($this->arr_h[0]['address3'])!=''){
	    $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
	    $pdf->Cell(12,$hl1,"",0,0,'L',0);
	    $pdf->SetFont('CordiaNew','',10);
	    $pdf->Cell(60,3,iconv('UTF-8','cp874',$this->arr_h[0]['address3']),0,0,'L',0); 
     }
     
    //new
//    $startY+=$l2br;
//    $startY+=$l2br;
//    $pdf->SetY($startY);
//	$pdf->SetX($startX); 
//	$pdf->Cell(52,$hl1,"TAX ID : ".$this->arr_h[0]['remark1'],0,0,'L',0);
//	if($this->arr_h[0]['remark2']=='-1'){
//		$pdf->Cell(20,$hl1,iconv('UTF-8','cp874','สำนักงานใหญ่'),0,0,'R',0); 
//	}else{
//		$pdf->Cell(20,$hl1,iconv('UTF-8','cp874','สาขาที่ '.$this->arr_h[0]['remark2']),0,0,'R',0); 
//	}
	//new
     
    $startY+=$l2br;
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
    
     //--------- product item ------------------
      $pdf->SetFont('CordiaNew','B',10);
      $discount=$this->arr_h[0]['member_percent']+$this->arr_h[0]['special_percent'];
      $member_percent=$this->arr_h[0]['member_percent'];
	  $special_percent=$this->arr_h[0]['special_percent'];
        foreach($this->arr_l as $dataL){
        	$name_product=trim($dataL['name_product']);
       		 //16
        	if(strlen($name_product)>8){
        		$name_product=mb_substr($name_product,0,8,'utf-8');
        		$name_product.="..";
        	}
        	
        	if(intval($dataL['member_discount1'])==0){
        		$chk_member_percent=0;
        	}else{
        		$chk_member_percent=$member_percent;
        	}
        	
        	if(intval($dataL['member_discount2'])==0){
        		$chk_special_percent=0;
        	}else{
        		$chk_special_percent=$special_percent;
        	}
        	
        	$pdf->Cell(3,$hl2,intval($dataL['quantity']),0,0,'R',0); 
	        $pdf->Cell(11,$hl2,$dataL['product_id'],0,0,'L',0);
	        $pdf->Cell(16,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        $pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);	       
	        $pdf->Cell(10,$hl2,number_format($dataL['price'],2),0,0,'R',0);
	        $pdf->Cell(12,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);  
	        $startY+=$l2br;
	    	$pdf->SetY($startY);
			$pdf->SetX($startX); 
        }        
     //--------- product item ------------------
	
	$startY+=$l2br;
    $pdf->SetY($startY);	
    $pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','B',10);
	$pdf->Cell(23,3,iconv('UTF-8','cp874',"Quantity ="),0,0,'L',0);  
	$pdf->Cell(20,3,intval($this->arr_h[0]['quantity']),0,0,'L',0);  
	$pdf->SetFont('CordiaNew','B',10);
	$pdf->Cell(15,3,"Total",0,0,'L',0);  
	$pdf->Cell(14,3,number_format($this->arr_h[0]['amount'],2),0,0,'R',0);  
        
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	if($this->arr_h[0]['paid']=='0002'){	
		$pdf->Cell(23,$hl1,iconv('UTF-8','cp874',$this->paiddesc),0,0,'L',0); 
		$pdf->Cell(20,$hl1,"<".$this->arr_h[0]['credit_no'].">",0,0,'L',0);//credit_no
	}else{
		$pdf->Cell(23,$hl1,"",0,0,'L',0); 
		$pdf->Cell(20,$hl1,"",0,0,'L',0);
	}
	$pdf->Cell(15,$hl2,"Discount",0,0,'L',0);  
	$pdf->Cell(14,$hl2,number_format($this->arr_h[0]['discount'],2),0,0,'R',0);  	
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 

	//$pdf->Cell(23,3,"",0,0,'L',0);  
	//$pdf->Cell(20,3,"",0,0,'L',0);  
	
	//*WR20032017
	if($this->arr_h[0]['credit_tp']=="Alipay"){
		$pdf->Cell(43,$hl1,"Net(RMB)  : ".$this->arr_h[0]['cnyamt'],0,0,'L',0);
	}else{
		$pdf->Cell(43,3,"",0,0,'L',0);  		
	}
	
	$pdf->Cell(15,3,"Net",0,0,'L',0);
	if(intVal($this->arr_h[0]['net_amt'])!=0){		
		$pdf->Cell(14,3,number_format($this->arr_h[0]['net_amt_before'],2),0,0,'R',0);  
	}else{
		$pdf->Cell(14,3,"0.00",0,0,'R',0);  
	}
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	
	//$pdf->Cell(23,3,"",0,0,'L',0);  
	//$pdf->Cell(20,3,"",0,0,'L',0);  
	if($this->arr_h[0]['credit_tp']=="Alipay"){
		$pdf->Cell(43,$hl1,"(1THB = ".$this->arr_h[0]['convrate']."RMB)",0,0,'L',0);
	}else{
		$pdf->Cell(43,$hl1,"",0,0,'L',0);
	}
	
	$pdf->Cell(15,3,"VAT",0,0,'L',0);  
	if(intVal($this->arr_h[0]['net_amt'])!=0){
		$pdf->Cell(14,3,number_format($this->arr_h[0]['vat'],2),0,0,'R',0); 
	}else{
		$pdf->Cell(14,3,"0.00",0,0,'R',0); 
	}
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->Cell(23,3,"",0,0,'L',0);  
	$pdf->Cell(20,3,"",0,0,'L',0);  
	$pdf->Cell(15,3,"Net (INC.VAT)",0,0,'L',0);  
	$pdf->Cell(14,3,number_format($this->arr_h[0]['net_amt'],2),0,0,'R',0);  
	
	
	if($this->arr_h[0]['alipay_last_title']=='A'){
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->SetFont('CordiaNew','',13);//B
		$pdf->Cell($maxdoc,$hl1,"Terms and Conditions:",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* The privilege cannot be redeemed or exchanged for cash.",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* Privilege cannot be used in combination with any other promotion, discount or special offer.",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* In case of any dispute, the matters and subjected to the final decision of Oriental Princess.",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$alipay_img=LOGO_PATH."/alipay_a.jpg";
		$pdf->Image($alipay_img,$startX,$startY,$maxdoc,'','');
		$startY+=40;//50//65
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
	}else if($this->arr_h[0]['alipay_last_title']=='B'){
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',13);//B
		$pdf->Cell($maxdoc,$hl1,"Terms and Conditions:",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* No refund./Product can be exchange,only in case",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"of damage of the product.Can change the same item",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"on the same day of purchase at the same store.",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* Privilege cannot be used in combination with any other",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"promotion,discount or special offer.",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"* In case of any dispute,the matters and subjected",0,0,'L',0);
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$pdf->SetFont('CordiaNew','',11);//B
		$pdf->Cell($maxdoc,$hl1,"to the final decision of Oriental Princess.",0,0,'L',0);
			
			
		$startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX);
			
		$alipay_img=LOGO_PATH."/alipay_b.jpg";
		$pdf->Image($alipay_img,$startX,$startY,$maxdoc,'','');
		$startY+=40;//50//65
		$pdf->SetY($startY);
		$pdf->SetX($startX);
	}else{
			
		//--------------------------------- START ALIPAY --------------------------------------
		if($this->arr_h[0]['credit_tp']=="Alipay"){
				
				//-------------------------------- none pro alipay used type B ----------------------------------------------
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',14);//B
				$pdf->Cell($maxdoc,$hl1,"Terms and Conditions:",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"* No refund./Product can be exchange,only in case",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"of damage of the product.Can change the same item",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"on the same day of purchase at the same store.",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"* Privilege cannot be used in combination with any other",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"promotion,discount or special offer.",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"* In case of any dispute,the matters and subjected",0,0,'L',0);
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$pdf->SetFont('CordiaNew','',12);//B
				$pdf->Cell($maxdoc,$hl1,"to the final decision of Oriental Princess.",0,0,'L',0);
					
					
				$startY+=$l2br;
				$pdf->SetY($startY);
				$pdf->SetX($startX);
					
				$alipay_img=LOGO_PATH."/alipay_b.jpg";
				//$pdf->Image($alipay_img,$startX,$startY,$maxdoc,'','');
				$pdf->Image($alipay_img,$startX,$startY,$maxdoc);				
				
				$startY+=40;//50//65
				$pdf->SetY($startY);
				$pdf->SetX($startX);
				//-------------------------------- none pro alipay used type B----------------------------------------------
			}else{
				//------------------ for idcard ----------------------
				$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX); 
				//*WR27052015 for support idcard
				 if(substr($this->arr_h[0]['member_id'],0,2)=='ID'){
						//*WR27052015 for support idcard
				 		$week_spday=$this->arr_h[0]['special_day'];
				 		$chk_spday=substr($week_spday,0,3);
				 		if($chk_spday=='OPS'){
				 			$str_spday="พฤหัสบดี";
				 		}else if($chk_spday=='OPT'){
				 			$str_spday="อังคาร";
				 		}else{
				 			$str_spday='';
				 		}
				 		$week_spday=substr($week_spday,3,1);
				 		$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"OPS Day ของคุณรับส่วนลด 15% ทุกวัน$str_spday ที่ $week_spday ของทุกเดือน"),0,0,'L',0);
				        
				        $startY+=$l2br;
					    $pdf->SetY($startY);
						$pdf->SetX($startX); 
						$curr_sp_date=$this->arr_h[0]['curr_sp_date'];
						$next_sp_date=$this->arr_h[0]['next_sp_date'];				
						$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"OPS Day  ครั้งถัดไปคือ  $next_sp_date "),0,0,'L',0);
				        $startY+=$l2br;
					    $pdf->SetY($startY);
						$pdf->SetX($startX); 		
		        }//end if
		        $startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX); 
				//------------------ for idcard ----------------------
	
				//------------------ for pro line --------------------
				if($this->arr_h[0]['msg_line']=='Y' && $this->act != 'reprint'){
					$pdf->SetFont('CordiaNew','U',11);
					$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874','พิเศษเฉพาะคุณรับส่วนลด 35%  สินค้าใดก็ได้ในร้าน'),0,0,'C',0);
					$startY+=$l2br;
					$pdf->SetY($startY);
					$pdf->SetX($startX);			
					$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874','ราคาปกติไม่เกิน 2,000 บาทวันนี้ - 30 เม.ย. 60'),0,0,'C',0);
					$startY+=$l2br;
					$pdf->SetY($startY);
					$pdf->SetX($startX);
					$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874','1คน/1สิทธิ์/1ครั้ง'),0,0,'C',0);
					
					$startY+=$l2br;
					$startY+=$l2br;
					$pdf->SetY($startY);
					$pdf->SetX($startX);
				}
				//------------------ for pro line --------------------
	
				$pdf->Cell(72,3,"Customer Satisfaction Guarantee",0,0,'L',0);  
	
				 if($this->arr_h[0]['status_no']=='06'){
			        	$startY+=$l2br;
					    $pdf->SetY($startY);
						$pdf->SetX($startX); 
			        	$pdf->SetFont('CordiaNew','B',10);
				        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"อ้างถึงใบลดหนี้            ").$this->arr_h[0]['refer_doc_no'],0,0,'L',0); 
				        $startY+=$l2br;
					    $pdf->SetY($startY);
						$pdf->SetX($startX); 
				        
				        $pdf->SetFont('CordiaNew','B',10);
				        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"จำนวนเงิน "),0,0,'L',0); 
				         $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['refer_cn_net'],2),0,0,'R',0); 
				        $startY+=$l2br;
				        $startY+=$l2br;
					    $pdf->SetY($startY);
						$pdf->SetX($startX); 
			    }
	
				$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX); 
				$pdf->SetFont('CordiaNew','B',10);
				$pdf->Cell(72,3,iconv('UTF-8','cp874',"ยินดีรับคืนผลิตภัณฑ์ที่ไม่พึงพอใจในทุกกรณี"),0,0,'L',0);  
				
				$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);  
	
				//*WR03032017 for check tour interantional not cn
				if($this->arr_h[0]['cnprivilege']=='Y'){	
					$pdf->Cell(72,3,iconv('UTF-8','cp874',"เพียงท่านแสดงใบเสร็จรับเงินใบนี้พร้อมสินค้าภายใน 14 วัน"),0,0,'L',0);  	
					$startY+=$l2br;
					$startY+=$l2br;
				    $pdf->SetY($startY);
					$pdf->SetX($startX);   
				}
				
				$pdf->Cell(72,3,iconv('UTF-8','cp874',"ผู้รับเงิน................................................................................."),0,0,'L',0);  
	
				//sms message
				$startY+=$l2br;
				$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);  
				if($this->arr_h[0]['status_no']!='01' && $this->arr_h[0]['bfc_code']!=''){
					$arr_line2print=$this->arr_h[0]['promo_message'];
					if(!empty($arr_line2print)){
						foreach($arr_line2print as $dataMsg){
							if($dataMsg['print_code']=='Y'){
								$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',$dataMsg['promo_des']."".$this->arr_h[0]['bfc_code']),0,0,'L',0); 
							}else{
								$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',$dataMsg['promo_des']),0,0,'L',0); 
							}
					        $startY+=$l2br;
						    $pdf->SetY($startY);
							$pdf->SetX($startX);  
						}
					}
				}
				//sms message	
		}//end of non general alipay
	
	//--------------------------------- START ALIPAY (END) --------------------------------------
	
	}
	
	$startY+=$l2br;
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  
	 $pdf->SetFont('CordiaNew','B',11);
	$pdf->Cell(32,3,"www.orientalprincess.com",0,0,'L',0);  
	$pdf->Cell(8,$hl1,"",0,0,'L',0);
	$pdf->Cell(32,3,"Beauty Line : 02-700-5700",0,0,'R',0);  
	
	if($this->arr_h[0]['alipay_last_title']!='A' && $this->arr_h[0]['alipay_last_title']!='B'){
	
		$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
		$pdf->SetFont('CordiaNew','B',10);
		$pdf->Cell(72,3,iconv('UTF-8','cp874',"เบอร์โทรศัพท์สาขา  : ".$this->arr_h[0]['branch_tel']),0,0,'L',0);  
	
	}
	
	$name='/billvattotal.pdf';
    $output=REPORT_PATH.$name;
	@chmod(REPORT_PATH,0777);
	$pdf->Output($output,'F'); 
	$print2ip=$this->arr_h[0]['print2ip'].":631";
	if($this->arr_h[0]['print2ip']=='LOCAL'){
		echo shell_exec("lp -o media=Letter $output");
	}else{
		echo shell_exec("lpr -H $print2ip $output");
	}
	if(@file_exists($output)){
		echo shell_exec("rm $output");
	}
?>