<?php
	include(FPDF_PATH."/fpdf.php");
	$hl=8;
    $hl1=7;
    $hl2=6;
    $l2br=7;
    $maxdoc=203;//210 	
    $logo="/op-logo.gif";
    $pdf=new FPDF('P','mm','A4');
    $pdf->SetThaiFont();
    $pdf->AddPage();
    $startY=2;
	$startX=0;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetMargins(0,2,0); 
    $pdf->SetAutoPageBreak("off",1);   
    $pdf->Image(LOGO_PATH.$logo,2,0,65);
    $startY+=8;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  
    $pdf->SetFont('CordiaNew','',14);
	//--------------------------------------------------------------------  
     if($this->arr_h[0]['branch_tp']=='F'){
        	if($this->arr_h[0]['title_line1']!=''){
        		$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line1']),0,0,'C',0);     
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);   		
        	}
        	
        	if($this->arr_h[0]['title_line2']!=''){        		
        		$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line2']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}
        	
	       	if($this->arr_h[0]['title_line3']!=''){        		
	        		$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line3']),0,0,'C',0);   
	        		$startY+=$l2br;
				    $pdf->SetY($startY);
					$pdf->SetX($startX);     		
	        }
        	
       	  	if($this->arr_h[0]['title_line4']!=''){        		
        		$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line4']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}       	
        	
        }else{
			$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['company_name_print']),0,0,'C',0); 
			$startY+=$hl2;
		    $pdf->SetY($startY);
			$pdf->SetX($startX);      
			$pdf->SetFont('CordiaNew','',14);
		    $pdf->Cell($maxdoc,$hl,"89/1 Soi Ratchataphan,Rachaprarop",0,0,'C',0); 
		    $startY+=$hl2;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 			
		    $pdf->Cell($maxdoc,$hl,"Rd. Makkasun Rachatevee Bangkok 10400.",0,0,'C',0); 
		    $startY+=$l2br;
        }
   
    $pdf->SetY($startY);
	$pdf->SetX($startX);    
	$pdf->SetFont('CordiaNew','B',10); 
    $pdf->Cell($maxdoc,$hl,"TAX INVOICE / RECEIPT",0,0,'C',0); 
    $startY+=$l2br;
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	
    $pdf->SetFont('CordiaNew','',14);//B
    $pdf->Cell(25,$hl1,"TAX ID :",0,0,'L',0); 
    $pdf->Cell(66,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
    $pdf->Cell(39,$hl1,"",0,0,'L',0);
    $pdf->Cell(73,$hl1,"POS ID : ".$this->arr_h[0]['pos_id'],0,0,'R',0);    
    
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
//   $pdf->Cell($maxdoc,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0); 
	$pdf->Cell(25,$hl1,"Branch : ",0,0,'R',0); 
    $pdf->Cell(178,$hl1,$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0); 
     
    
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	
	$pdf->Cell(25,$hl1,"Rcpt : ",0,0,'L',0); 
	$pdf->Cell(72,$hl1,$this->arr_h[0]['doc_no'],0,0,'L',0);	
	$pdf->Cell(43,$hl1,"",0,0,'L',0);
	$arr_docdate=explode("-",$this->arr_h[0]['doc_date']);
	$doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
	$pdf->Cell(63,$hl1,$doc_date_show." ".$this->arr_h[0]['doc_time'],0,0,'R',0); 
	
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);
	$pdf->SetFont('CordiaNew','B',10); 
	
//	$pdf->Cell(14,$hl1,"Member ID : ",0,0,'L',0); 
//    $pdf->Cell(34,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
//    $pdf->Cell(14,$hl1,"Cashier :",0,0,'R',0); 
//    $pdf->Cell(10,$hl1,$this->arr_h[0]['saleman_id'],0,0,'R',0);	
		
    $pdf->Cell(25,$hl1,"Member ID : ",0,0,'R',0); 
    $pdf->Cell(82,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
    $pdf->Cell(57,$hl1,"Cashier :",0,0,'R',0); 
    $pdf->Cell(39,$hl1,$this->arr_h[0]['saleman_id'],0,0,'L',0);		
    
    
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','',14);
    $pdf->Cell(25,$hl1,"Name : ",0,0,'L',0); 
    $name=trim($this->arr_h[0]['name']);
    $name_len=strlen($name);
    if($name!=''){
	    $pdf->SetFont('CordiaNew','',14);
    	if($name_len>50){
        	$name_L1=mb_substr($name,0,50,'utf-8');
        	$name_L2=mb_substr($name,50,50,'utf-8');
        	$pdf->Cell(178,$hl1,iconv('UTF-8','cp874',$name_L1),0,0,'L',0); 
        	 $startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 
			$pdf->Cell(25,$hl1,"",0,0,'L',0);
        	$pdf->Cell(178,$hl1,iconv('UTF-8','cp874',$name_L2),0,0,'L',0); 
        }else{
			$pdf->Cell(178,3,iconv('UTF-8','cp874',$this->arr_h[0]['name']),0,0,'L',0);    
        }
    }
	
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 	
    $pdf->Cell(25,$hl1,"Address : ",0,0,'L',0);     
    if(trim($this->arr_h[0]['address1'])!=''){
	    $pdf->Cell(178,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address1']),0,0,'L',0); 
    }
    
    if(trim($this->arr_h[0]['address2'])!=''){
	    $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
	    $pdf->Cell(25,$hl1,"",0,0,'L',0); 	   
	    $pdf->Cell(178,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address2']),0,0,'L',0); 
    }
     if(trim($this->arr_h[0]['address3'])!=''){
	    $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
	    $pdf->Cell(25,$hl1,"",0,0,'L',0);	  
	    $pdf->Cell(178,3,iconv('UTF-8','cp874',$this->arr_h[0]['address3']),0,0,'L',0); 
     }
     
    $startY+=$l2br;
    $startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);     
     //--------- product item ------------------     
      $discount=$this->arr_h[0]['member_percent']+$this->arr_h[0]['special_percent'];
      $member_percent=$this->arr_h[0]['member_percent'];
	  $special_percent=$this->arr_h[0]['special_percent'];
        foreach($this->arr_l as $dataL){
        	$name_product=trim($dataL['name_product']);
       		 //16
        	if(strlen($name_product)>27){
        		$name_product=mb_substr($name_product,0,27,'utf-8');
        		$name_product.="..";
        	}
        	
        	if(intval($dataL['member_discount1'])==0){
        		$chk_member_percent=0;
        	}else{
        		$chk_member_percent=$member_percent;
        	}
        	
        	if(intval($dataL['member_discount2'])==0){
        		$chk_special_percent=0;
        	}else{
        		$chk_special_percent=$special_percent;
        	}
        	
//        	$pdf->Cell(3,$hl2,intval($dataL['quantity']),0,0,'R',0); 
//	        $pdf->Cell(11,$hl2,$dataL['product_id'],0,0,'L',0);
//	        $pdf->Cell(16,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
//	        $pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);	       
//	        $pdf->Cell(10,$hl2,number_format($dataL['price'],2),0,0,'R',0);
//	        $pdf->Cell(12,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);  
			$pdf->Cell(10,$hl2,intval($dataL['quantity']),0,0,'C',0); 
	        $pdf->Cell(28,$hl2,$dataL['product_id'],0,0,'L',0);
	        $pdf->Cell(60,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        $pdf->Cell(30,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);	       
	        $pdf->Cell(38,$hl2,number_format($dataL['price'],2),0,0,'R',0);
	        $pdf->Cell(37,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);  
	        $startY+=$l2br;
	    	$pdf->SetY($startY);
			$pdf->SetX($startX); 
        }        
     //--------- product item ------------------
	
	$startY+=$l2br;
    $pdf->SetY($startY);	
    $pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','',14);
	$pdf->Cell(66,$hl1,iconv('UTF-8','cp874',"จำนวนชิ้นรวม ="),0,0,'L',0);  
	$pdf->Cell(64,$hl1,intval($this->arr_h[0]['quantity']),0,0,'L',0);  
	$pdf->SetFont('CordiaNew','B',10);
	$pdf->Cell(36,$hl1,"Total",0,0,'L',0);  
	$pdf->Cell(37,$hl1,number_format($this->arr_h[0]['amount'],2),0,0,'R',0);  
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 	
	$pdf->Cell(66,$hl1,"",0,0,'L',0);  
	$pdf->Cell(64,$hl1,"",0,0,'L',0);  
	$pdf->Cell(36,$hl1,"Discount",0,0,'L',0);  
	$pdf->Cell(37,$hl1,number_format($this->arr_h[0]['discount'],2),0,0,'R',0);  
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	

	$pdf->Cell(66,$hl1,"",0,0,'L',0);  
	$pdf->Cell(64,$hl1,"",0,0,'L',0);  
	$pdf->Cell(36,$hl1,"Net",0,0,'L',0);
	if(intVal($this->arr_h[0]['net_amt'])!=0){
		//$net_before=$this->arr_h[0]['net_amt']-$this->arr_h[0]['vat'];
		$pdf->Cell(37,$hl1,number_format($this->arr_h[0]['net_amt_before'],2),0,0,'R',0);  
	}else{
		$pdf->Cell(37,$hl1,"0.00",0,0,'R',0);  
	}
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	
	$pdf->Cell(66,$hl1,"",0,0,'L',0);  
	$pdf->Cell(64,$hl1,"",0,0,'L',0);  
	$pdf->Cell(36,$hl1,"VAT",0,0,'L',0);  
	if(intVal($this->arr_h[0]['net_amt'])!=0){
		$pdf->Cell(37,$hl1,number_format($this->arr_h[0]['vat'],2),0,0,'R',0); 
	}else{
		$pdf->Cell(37,$hl1,"0.00",0,0,'R',0); 
	}	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->Cell(66,$hl1,"",0,0,'L',0);  
	$pdf->Cell(64,$hl1,"",0,0,'L',0);  
	$pdf->Cell(36,$hl1,"Net (INC.VAT)",0,0,'L',0);  
	$pdf->Cell(37,$hl1,number_format($this->arr_h[0]['net_amt'],2),0,0,'R',0);  

	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->Cell($maxdoc,3,"Customer Satisfaction Guarantee",0,0,'L',0);  
	
	 if($this->arr_h[0]['status_no']=='06'){
        	$startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX);         	
	        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"อ้างถึงใบลดหนี้            ").$this->arr_h[0]['refer_doc_no'],0,0,'L',0); 
	        $startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 	        
	        
	        $pdf->Cell(178,$hl1,iconv('UTF-8','cp874',"จำนวนเงิน "),0,0,'L',0); 
	        $pdf->Cell(25,$hl1,number_format($this->arr_h[0]['refer_cn_net'],2),0,0,'R',0); 
	        $startY+=$l2br;
	        $startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 
    }
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	$pdf->SetFont('CordiaNew','B',10);
	$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ยินดีรับคืนผลิตภัณฑ์ที่ไม่พึงพอใจในทุกกรณี"),0,0,'L',0);  
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  
	$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"เพียงท่านแสดงใบเสร็จรับเงินใบนี้พร้อมสินค้าภายใน 14 วัน"),0,0,'L',0);  
	
	$startY+=$l2br;
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);   
	$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ผู้รับเงิน................................................................................."),0,0,'L',0);  
	
	//sms message
	$startY+=$l2br;
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  
	if($this->arr_h[0]['status_no']!='01' && $this->arr_h[0]['bfc_code']!=''){
		$arr_line2print=$this->arr_h[0]['promo_message'];
		if(!empty($arr_line2print)){
			foreach($arr_line2print as $dataMsg){
				if($dataMsg['print_code']=='Y'){
					$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',$dataMsg['promo_des']."".$this->arr_h[0]['bfc_code']),0,0,'L',0); 
				}else{
					$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',$dataMsg['promo_des']),0,0,'L',0); 
				}
		        $startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);  
			}
		}
	}
	//sms message
	
	$startY+=$l2br;
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX);  	
	$pdf->Cell($maxdoc,$hl1,"www.orientalprincesssociety.com",0,0,'L',0);  
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 
	//$pdf->Cell($maxdoc,$hl1,"Call Center : 02-660-8900",0,0,'L',0);  
	$pdf->Cell($maxdoc,$hl1,"Beauty Line : 0-2642-6606",0,0,'L',0);  
	
	$startY+=$l2br;
    $pdf->SetY($startY);
	$pdf->SetX($startX); 	
	$pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"เบอร์โทรศัพท์สาขา  : ".$this->arr_h[0]['branch_tel']),0,0,'L',0);  
	
	$name='/billvattotal.pdf';
    $output=REPORT_PATH.$name;
	@chmod(REPORT_PATH,0777);
	$pdf->Output($output,'F'); 
	//echo shell_exec("lp -o media=Letter $output");
	$print2ip=$this->arr_h[0]['print2ip'].":631";
	if($this->arr_h[0]['print2ip']=='LOCAL'){
		echo shell_exec("lp -o media=Letter $output");
	}else{
		echo shell_exec("lpr -H $print2ip $output");
	}
	if(@file_exists($output)){
		echo shell_exec("rm $output");
		//@unlink($output);
	}
?>