<?php	
	include(FPDF_PATH."/fpdf.php");
        $hl=5;
        $hl1=4;
        $hl2=3;
        $maxdoc=72;
        $l2br=4;
        $logo="/op-logo.gif";
        $pdf=new FPDF('P','mm','a23');
        $pdf->SetThaiFont();
        $pdf->AddPage();
        $startY=2;
        $startX=0;
        $pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->SetMargins(0,2,0); 
        $pdf->SetAutoPageBreak("off",1);       
        $pdf->Image(LOGO_PATH.$logo,2,0,65);
        $startY+=8;
        $pdf->SetY($startY);
        
        $pdf->SetFont('CordiaNew','B',13); 
        if($this->act=='reprint'){        	
        	$pdf->Cell(2,$hl,"*",0,0,'L',0); 
        }
        if($this->arr_h[0]['branch_tp']=='F'){
        	if($this->arr_h[0]['title_line1']!=''){
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line1']),0,0,'C',0);     
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);   		
        	}
        	
        	if($this->arr_h[0]['title_line2']!=''){        		
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line2']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}
        	
	       	if($this->arr_h[0]['title_line3']!=''){        		
	        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line3']),0,0,'C',0);   
	        		$startY+=$l2br;
				    $pdf->SetY($startY);
					$pdf->SetX($startX);     		
	        }
        	
       	  	if($this->arr_h[0]['title_line4']!=''){        		
        		$pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['title_line4']),0,0,'C',0);   
        		$startY+=$l2br;
			    $pdf->SetY($startY);
				$pdf->SetX($startX);     		
        	}       	
        	
        }else{
	        $pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['company_name_print']),0,0,'C',0); 
	        $startY+=$l2br;
	        $pdf->SetY($startY);
        }
		        
        $pdf->SetFont('CordiaNew','B',11); 
        $pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',"89/1 ซอยรัชฏภัณฑ์ ถนนราชปรารภ แขวงมักกะสัน"),0,0,'C',0); 
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        $pdf->SetFont('CordiaNew','B',11); 
        $pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',"เขตราชเทวี กรุงเทพฯ 10400"),0,0,'C',0); 
        
		
        $startY+=$hl;
        $pdf->SetY($startY);
        
//        $str_cancel='';
//		if($this->arr_h[0]['flag']=='C'){
//			$str_cancel='<ยกเลิก>';
//			$str_cancel=iconv('UTF-8','cp874',$str_cancel);
//		}     

        $str_cancel='';
		if($this->arr_h[0]['flag']=='C'){
			$str_cancel="<ยกเลิก>";
			//$str_cancel=iconv('UTF-8','cp874',$str_cancel);
		}       
       
        //$pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',ใบลดหนี้(CREDIT NOTE))",0,0,'C',0);     
        
        $pdf->Cell($maxdoc,$hl,iconv('UTF-8','cp874',"$str_cancel ใบลดหนี้(CREDIT NOTE)"),0,0,'C',0); 
       	$startY+=$l2br;
       	$startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->SetFont('CordiaNew','B',10);
        $pdf->Cell(10,$hl1,"TAX ID :",0,0,'L',0); 
        $pdf->Cell(25,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
        $pdf->Cell(4,$hl1,"",0,0,'L',0);
        $pdf->Cell(33,$hl1,"POS ID : ".$this->arr_h[0]['pos_id'],0,0,'R',0); 
        $startY+=$l2br;
        $pdf->SetY($startY);
        //$pdf->Cell($maxdoc,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0);         
        $pdf->Cell(59,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name']),0,0,'L',0);
        $pdf->Cell(13,$hl1,"#".$this->arr_h[0]['computer_no'],0,0,'R',0);
        
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        $pdf->Cell(8,$hl1,"Rcpt : ",0,0,'L',0); 
		$pdf->Cell(25,$hl1,$this->arr_h[0]['doc_no'],0,0,'L',0);	
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$arr_docdate=explode("-",$this->arr_h[0]['doc_date']);
		$doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
		$pdf->Cell(33,$hl1,$doc_date_show." ".$this->arr_h[0]['doc_time'],0,0,'R',0); 
		
       	$startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(15,$hl1,"Member ID : ",0,0,'L',0); 
        
        if(substr($this->arr_h[0]['member_id'],0,2)=='ID'){
        	$str_idcard=$this->arr_h[0]['idcard'];
        	$str_idcard = substr($str_idcard, -4);
        	$str_idcard = "XXXXXXXX-".$str_idcard;
        	$pdf->Cell(32,$hl1,$str_idcard,0,0,'L',0);
        }else{
        	$pdf->Cell(32,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
        }
        
       // $pdf->Cell(32,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
        
        $pdf->Cell(12,$hl1,"Cashier :",0,0,'R',0); 
        $pdf->Cell(13,$hl1,$this->arr_h[0]['saleman_id'],0,0,'R',0);		
        //--------- member info -----------------
       	$startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"นามผู้ซื้อ : "),0,0,'L',0); 
        $pdf->Cell(57,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['name']),0,0,'L',0);      
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"ที่อยู่ : "),0,0,'L',0); 
        $pdf->Cell(57,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address1']),0,0,'L',0);      
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(15,$hl1,"   ",0,0,'L',0); 
        $pdf->Cell(57,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['address2']),0,0,'L',0);   
       	$startY+=$l2br;
        $pdf->SetY($startY);
        //หมายเหตุ
        $pdf->Cell(18,$hl1,iconv('UTF-8','cp874',"สาเหตุที่ลดหนี้ : "),0,0,'L',0); 
        $pdf->Cell(54,$hl1,iconv('UTF-8','cp874','สินค้าไม่ตรงตามคำพรรณนา'),0,0,'L',0);      
      
       	$startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"เงื่อนไข : "),0,0,'L',0); 
        $pdf->Cell(57,$hl1,iconv('UTF-8','cp874',"เงินสด"),0,0,'L',0);      
        $startY+=$l2br;
       	$startY+=$l2br;
        $pdf->SetY($startY);
        
        //--------- product item ------------------
      	$pdf->SetFont('CordiaNew','',10);
      	$discount=$this->arr_h[0]['member_percent']+$this->arr_h[0]['special_percent'];
		$member_percent=$this->arr_h[0]['member_percent'];
		$special_percent=$this->arr_h[0]['special_percent'];

        foreach($this->arr_l as $dataL){
        	$name_product=trim($dataL['name_product']);
        	//16
        	if(strlen($name_product)>8){
        		$name_product=mb_substr($name_product,0,8,'utf-8');
        		$name_product.="..";
        	}
        	
        	if(intval($dataL['member_discount1'])==0){
        		$chk_member_percent=0;
        	}else{
        		$chk_member_percent=$member_percent;
        	}
        	
        	if(intval($dataL['member_discount2'])==0){
        		$chk_special_percent=0;
        	}else{
        		$chk_special_percent=$special_percent;
        	}
        	
	        $pdf->Cell(3,$hl2,intval($dataL['quantity']),0,0,'R',0); 
	        $pdf->Cell(11,$hl2,$dataL['product_id'],0,0,'L',0);
	        $pdf->Cell(16,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        $pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);
	       
	        $pdf->Cell(10,$hl2,number_format($dataL['price'],2),0,0,'R',0);
	        $pdf->Cell(12,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);        
	        $startY+=$l2br;
        	$pdf->SetY($startY);
        }        
        //--------- product item ------------------
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->SetFont('CordiaNew','B',10);//B
        $pdf->Cell(72,$hl1,iconv('UTF-8','cp874',"ผิด ตก ยกเว้น E.&O.E."),0,0,'L',0); 
        
        $startY+=$l2br;
        $pdf->SetY($startY);      
        $pdf->Cell(24,$hl1,"",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"รวมเงิน"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['amount'],2),0,0,'R',0);
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(24,$hl1,"",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"ส่วนลด"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['discount'],2),0,0,'R',0);
       	$startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell(24,$hl1,"",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,iconv('UTF-8','cp874',"สุทธิ"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['net_amt'],2),0,0,'R',0);
        $startY+=$l2br;
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        
        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"มูลค่าสินค้าตามใบกำกับภาษีเดิม"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['ref_net_amt'],2),0,0,'R',0);
        $startY+=$l2br;
        $pdf->SetY($startY);
              
        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"มูลค่าสินค้าที่ถูกต้อง"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,$this->arr_h[0]['net_amt_valid'],0,0,'R',0);
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"มูลค่าสินค้าที่ลดหนี้"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['net_amt_cn'],2),0,0,'R',0);
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        
        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"ภาษีมูลค่าเพิ่ม"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,$vat_add=number_format($this->arr_h[0]['vat_add'],2),0,0,'R',0);
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        $pdf->Cell(59,$hl1,iconv('UTF-8','cp874',"รวมทั้งสิ้น"),0,0,'L',0); 
        $pdf->Cell(13,$hl1,$this->arr_h[0]['net_amt_total'],0,0,'R',0);
        $startY+=$l2br;
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"อ้างถึงบิลเงินสด/ใบกำกับภาษีอย่างย่อ : ".$this->arr_h[0]['refer_doc_no']),0,0,'L',0); 
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"สถานะ : ".$this->arr_h[0]['status_no']." ".$this->arr_h[0]['cn_description']),0,0,'L',0); 
        $startY+=$l2br;
        $pdf->SetY($startY);
        
       
        $pdf->Cell(18,$hl1,iconv('UTF-8','cp874',"หมายเหตุ : "),0,0,'L',0); 
        $pdf->Cell(54,$hl1,iconv('UTF-8','cp874',$this->arr_h[0]['doc_remark']),0,0,'L',0);      
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        if($this->arr_h[0]['status_no']=='41'){
        	  $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"บัญชี : ".$this->arr_h[0]['acc_name']),0,0,'L',0); 
        	 $startY+=$l2br;
        	 $pdf->SetY($startY);
        	  $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ชื่อธนาคาร : ".$this->arr_h[0]['bank_name']),0,0,'L',0); 
        	 $startY+=$l2br;
       		 $pdf->SetY($startY);
        	 $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"เลขที่บัญชี : ".$this->arr_h[0]['bank_acc']),0,0,'L',0); 
        	 $startY+=$l2br;
        	 $pdf->SetY($startY);
        	 $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"โทรศัพท์ : ".$this->arr_h[0]['tel1']."  ".$this->arr_h[0]['tel2']),0,0,'L',0); 
        	 $startY+=$l2br;
        	 $pdf->SetY($startY);
        }
        
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"ลูกค้า....................................................................."),0,0,'L',0); 
        $startY+=$l2br;
        $startY+=$l2br;
        $pdf->SetY($startY);
        
        $pdf->Cell(32,$hl1,"www.orientalprincess.com",0,0,'L',0);
        $pdf->Cell(8,$hl1,"",0,0,'L',0); 
        $pdf->Cell(32,$hl1,"Beauty Line : 0-2642-6606",0,0,'L',0);  
        $startY+=$l2br;
        $pdf->SetY($startY);
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"เบอร์โทรศัพท์สาขา : ".$this->arr_h[0]['branch_tel']),0,0,'L',0);
        $name='/billcn.pdf';
	    $output=REPORT_PATH.$name;
	    @chmod(REPORT_PATH,0777);
	    //$pdf->Output($output);// for test print	
//	    $pdf->Output($output,'F');
//		echo shell_exec("lp -o media=Letter $output");
//		if(@file_exists($output)){
//			echo shell_exec("rm $output");			
//		}
		$pdf->Output($output,'F');					
		$print2ip=$this->arr_h[0]['print2ip'].":631";		
		if($this->arr_h[0]['print2ip']=='LOCAL'){
			echo shell_exec("lp -o media=Letter $output");
		}else{
			echo shell_exec("lpr -H $print2ip $output");
		}
		if(@file_exists($output)){
			echo shell_exec("rm $output");			
		}	
?>