<?php	
	include(FPDF_PATH."/fpdf.php");
        $hl=5;
        $hl1=4;
        $hl2=3;
        $l2br=4;
        $maxdoc=72;
        $logo="/op-logo.gif";
        $pdf=new FPDF('P','mm','a23');
        $pdf->SetThaiFont();
        $pdf->AddPage();
        $startY=2;
        $startX=0;
        $pdf->SetY($startY);
		$pdf->SetX($startX);
		$pdf->SetMargins(0,2,0); 
        $pdf->SetAutoPageBreak("off",1);
        $pdf->Image(LOGO_PATH.$logo,2,0,65);
        $startY+=8;
        $pdf->SetY($startY);
		$pdf->SetX($startX);
        $pdf->SetFont('CordiaNew','B',13); 
        $str_copy="";
        if($this->act=='reprint'){        	
        	$pdf->Cell(2,$hl,"*",0,0,'L',0); 
        	$str_copy="(COPY)";
        }      
       
        $pdf->Cell($maxdoc-2,$hl,iconv('UTF-8','cp874',$this->arr_h[0]['company_name_print']),0,0,'C',0); 
        $startY+=$l2br;
		$pdf->SetY($startY);
		$pdf->SetX($startX); 
      
		$str_cancel='';
		if($this->arr_h[0]['flag']=='C'){
			$str_cancel='<ยกเลิก>';
			$str_cancel=iconv('UTF-8','cp874',$str_cancel);
		}       
       
        $pdf->Cell($maxdoc,$hl,"$str_cancel TAX INVOICE (ABB.) $str_copy",0,0,'C',0);       
        
        $startY+=$l2br;
      	$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
		
        $pdf->SetFont('CordiaNew','B',11);//B  10
        $pdf->Cell(10,$hl1,"TAX ID :",0,0,'L',0); 
        
         if($this->arr_h[0]['branch_tp']=='F'){
         	$pdf->Cell(25,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
         }else{
        	$pdf->Cell(25,$hl1,$this->arr_h[0]['tax_id'],0,0,'L',0);
         }
        $pdf->Cell(4,$hl1,"",0,0,'L',0);
        $pdf->Cell(33,$hl1,"POS ID : ".$this->arr_h[0]['pos_id'],0,0,'R',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->Cell(59,$hl1,"Branch : ".$this->csh_branch_id." ".iconv('UTF-8','cp874',$this->arr_h[0]['branch_name_e']),0,0,'L',0);
        $pdf->Cell(13,$hl1,"#".$this->arr_h[0]['computer_no'],0,0,'R',0);
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        
        $pdf->Cell(8,$hl1,"Rcpt : ",0,0,'L',0); 
		$pdf->Cell(25,$hl1,$this->arr_h[0]['doc_no'],0,0,'L',0);	
		$pdf->Cell(6,$hl1,"",0,0,'L',0);
		$arr_docdate=explode("-",$this->arr_h[0]['doc_date']);
		$doc_date_show=$arr_docdate[2]."/".$arr_docdate[1]."/".$arr_docdate[0];
		$pdf->Cell(33,$hl1,$doc_date_show." ".$this->arr_h[0]['doc_time'],0,0,'R',0); 
		
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->Cell(15,$hl1,"Member ID : ",0,0,'L',0); 
         if(substr($this->arr_h[0]['member_id'],0,2)=='ID'){
        	$pdf->Cell(32,$hl1,$this->arr_h[0]['idcard'],0,0,'L',0);
        }else{
        	$pdf->Cell(32,$hl1,$this->arr_h[0]['member_id'],0,0,'L',0);
        }
        
        $pdf->Cell(12,$hl1,"Cashier :",0,0,'R',0); 
        $pdf->Cell(13,$hl1,$this->arr_h[0]['saleman_id'],0,0,'R',0);		
     
        $startY+=$hl;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        //--------- product item ------------------
      	
      	$discount=$this->arr_h[0]['member_percent']+$this->arr_h[0]['special_percent'];
		$member_percent=$this->arr_h[0]['member_percent'];
		$special_percent=$this->arr_h[0]['special_percent'];
		$pdf->SetFont('CordiaNew','',11);
        foreach($this->arr_l as $dataL){
        	$name_product=trim($dataL['name_product']);
        	if(strlen($name_product)>11){
        		$name_product=mb_substr($name_product,0,15,'utf-8');
        		$name_product.="..";
        	}
        	if(intval($dataL['member_discount1'])==0){
        		$chk_member_percent=0;
        	}else{
        		$chk_member_percent=$member_percent;
        	}
        	if(intval($dataL['member_discount2'])==0){
        		$chk_special_percent=0;
        	}else{
        		$chk_special_percent=$special_percent;
        	}
	        $pdf->Cell(3,$hl2,intval($dataL['quantity']),0,0,'R',0); 
	        $pdf->Cell(11,$hl2,$dataL['product_id'],0,0,'L',0);
	        $pdf->Cell(16,$hl2,iconv('UTF-8','cp874',$name_product),0,0,'L',0);
	        //$pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."+".intval($chk_member_percent)."%+".intval($chk_special_percent)."%]",0,0,'R',0);	       
	        $pdf->Cell(20,$hl2,"[".number_format($dataL['discount'],2)."]",0,0,'R',0);	     
	        $pdf->Cell(10,$hl2,number_format($dataL['price'],2),0,0,'R',0);
	        $pdf->Cell(12,$hl2,number_format($dataL['net_amt'],2),0,0,'R',0);        
	        $startY+=$l2br;
		    $pdf->SetY($startY);
			$pdf->SetX($startX); 
        }        
        //--------- product item ------------------
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->SetFont('CordiaNew','B',11);
        $pdf->Cell(24,$hl1,iconv('UTF-8','cp874',"Total PCS. ="),0,0,'L',0); 
        $pdf->Cell(20,$hl1,intval($this->arr_h[0]['quantity']),0,0,'L',0);
        $pdf->Cell(15,$hl1,"Total(".iconv('UTF-8','cp874','฿').")",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['amount'],2),0,0,'R',0);
      	$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
		if($this->arr_h[0]['paid']=='0002'){
	        $pdf->Cell(24,$hl1,iconv('UTF-8','cp874',$this->paiddesc),0,0,'L',0);        
	        $pdf->Cell(20,$hl1,"<".$this->arr_h[0]['credit_no'].">",0,0,'L',0);//credit_no
		}else{
			$pdf->Cell(24,$hl1,"",0,0,'L',0);        
	        $pdf->Cell(20,$hl1,"",0,0,'L',0);
		}
        $pdf->Cell(15,$hl1,"Discount(".iconv('UTF-8','cp874','฿').")",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['discount'],2),0,0,'R',0);
       	$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->Cell(24,$hl1,"*** Vat Included ***",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,"Net(".iconv('UTF-8','cp874','฿').")",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['net_amt'],2),0,0,'R',0);
      	$startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->Cell(24,$hl1,"",0,0,'L',0); 
        $pdf->Cell(20,$hl1,"",0,0,'L',0);
        $pdf->Cell(15,$hl1,"Received(".iconv('UTF-8','cp874','฿').")",0,0,'L',0); 
       	$pdf->Cell(13,$hl1,number_format($this->arr_h[0]['pay_cash'],2),0,0,'R',0);        
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
		
     	$pdf->Cell(20,$hl1,'',0,0,'L',0); 
	    $pdf->Cell(24,$hl1,'',0,0,'L',0);
        $pdf->Cell(15,$hl1,"Change(".iconv('UTF-8','cp874','฿').")",0,0,'L',0); 
        $pdf->Cell(13,$hl1,number_format($this->arr_h[0]['change'],2),0,0,'R',0);
        $startY+=$l2br;
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 		
				
        $pdf->SetFont('CordiaNew','BU',11);
        $pdf->Cell($maxdoc,$hl1,"Exchange/No Refund Policy:",0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	    $pdf->SetFont('CordiaNew','',11);//B 10
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"Good can be exchanged within 14 days from purchase upon "),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	     $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"presenting the original receipt. The good must be in original "),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	    $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"condition and can only be exchanged for goods of the same "),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	    $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"or higher value. Any difference must be settled in cash."),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	     $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"No refund for good purchase."),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	     $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',""),0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
	    
        $startY+=$l2br;
        $startY+=$l2br;
	    $pdf->SetY($startY);
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"Cashier....................................................................."),0,0,'L',0);              
        $pdf->Cell(32,$hl1,"www.orientalprincesssociety.com",0,0,'L',0);
        $pdf->Cell(8,$hl1,"",0,0,'L',0); 
        $startY+=$l2br;
	    $pdf->SetY($startY);
		$pdf->SetX($startX); 
        $pdf->Cell($maxdoc,$hl1,iconv('UTF-8','cp874',"Tel. Branch : ".$this->arr_h[0]['branch_tel']),0,0,'L',0);
        $name='/billvatshort.pdf';
	    $output=REPORT_PATH.$name;    
	    
	    @chmod(REPORT_PATH,0777);
	    $pdf->Output($output,'F');
		$print2ip=$this->arr_h[0]['print2ip'].":631";
		if($this->arr_h[0]['print2ip']=='LOCAL'){
			echo shell_exec("lp -o media=Letter $output");
		}else{
			echo shell_exec("lpr -H $print2ip $output");
		}
		if(@file_exists($output)){
			echo shell_exec("rm $output");
		}
?>